### ISSUE TITLE
[Feature request] Working dir in title

### ISSUE THREAD

**Issue by LemonBoy** [thestinger/termite#1]
Im currently using a minimalist PS1 and have no way to quickly know the current working dir, having it in the window title would help making less mistakes on my end :)
I'd roll a patch by myself but don't have time atm :(

**Comment by jeremejevs** [comment]
A relevant section in Arch wiki, for future lurkers: https://wiki.archlinux.org/index.php/Zsh#xterm_title

**Comment by mb720** [comment]
I have this in my `.bashrc` to set the window title (tested with i3 and Sway):

    # After each command finishes, we set the terminal window title to the
    # current working directory. If, for example, Vim sets the window title
    # to the file's name and we exit Vim, the window title becomes the
    # current directory again.
    # There has to be a space between $(pwd) and \007 so the sequence is ended properly,
    # otherwise the window title would only be changed sometimes.
    # These escape sequences are documented in man 4 console_codes.
    # \033 is octal for ESC in ASCII, \007 is BEL
    PROMPT_COMMAND="$PROMPT_COMMAND;echo -ne \"\033]0;\$(pwd) \007\""
