### ISSUE TITLE
Setting the padding

### ISSUE THREAD

**Issue by vixus0** [thestinger/termite#111]
Is there a way to modify the padding used by termite? I think it gets some parameter from the GTK VTE widget, but it's be nice to have a setting in termite's own config.

**Comment by b0o** [comment]
For those reading this in 2017 and beyond, the above solution no longer works.

See #338 for the new solution.

**Comment by praton1729** [comment]
VteTerminal, vte-terminal {
    padding: 15px;
 }

**Comment by cpnfeeny** [comment]
in `~/.config/gtk-3.0/gtk.css `I have

`.termite { padding:3px; background-color:red; }`

Works for me.
