### ISSUE TITLE
unable to 'backspace' in certain ssh sessions

### ISSUE THREAD

**Issue by esn89** [thestinger/termite#113]
I haven't been able to use the backspace on my keyboard (it registers as a spacebar instead) on a school's ssh server.  

i have tried it with xterm and urxvt and the backspace on that has worked fine.

**Comment by akiva** [comment]
This solution does not work for me, and I am a bit baffled by this (I've never encountered it before now). I figured I had to install Termite on the host machine I am SSHing into, but it's headless, so that doesn't really make any sense.

**Comment by polyzen** [comment]
Akiva, sounds like you need to install the terminfo for termite on the
remote.

**Comment by Radivarig** [comment]
If you can't or don't want to edit every remote machine you connect to, you can set
```bash
TERM="xterm-256color"
```
 before connecting. I have mine set in `.bashrc`
