### ISSUE TITLE
zsh - backspace issue

### ISSUE THREAD

**Issue by sygo** [thestinger/termite#123]
First of: hugely excited about termite, thanks for the hard work!

I'm using zsh and it seems I can't get backspace to do it's job, every time I press the key it advances the cursor and doesn't delete the character from the screen. It works fine in bash.

It seems it is effectively deleting the characters and it's more of a visual issue:

five spaces between 9 and 0:

``` bash
atticus% echo "123456789     0"
123456789     0
```

five backspaces between 9 and 0:

``` bash
atticus% echo "123456789     0"
12340
```

I tested this with and without sourcing .zshrc and results were identical.

Versions:
termite v6-39-gf0ff025
vte3-select-text 0.34.7-1
zsh 5.0.2 (x86_64-unknown-linux-gnu)

Thanks again!

**Comment by jarias** [comment]
I'm having the same issue

Ubuntu 15.10
Termite v10-20-g22c1191
ZSH 5.1.1 (x86_64-ubuntu-linux-gnu)
$TERM is not set manually value = xterm-termite

**Comment by jarias** [comment]
Works fine with BASH or SH

**Comment by xPathin** [comment]
I know this is kinda old but I'm havin exactly this issue myself.
Has anyone solved the issue and if yes, how?

**Comment by thestinger** [comment]
The solution is already in the thread: set up zsh bindings correctly using terminfo and setting it to handle application/cursor mode changes.

**Comment by xPathin** [comment]
Yeah sorry, my bad. Working now.
