### ISSUE TITLE
Configure Colors in Separate File?

### ISSUE THREAD

**Issue by baskerville** [thestinger/termite#130]
I don't think that the current configuration file format provides any inclusion directive, isn't it?

**Comment by Ploppz** [comment]
What is the status on this right now?

**Comment by toogy** [comment]
This should be done

**Comment by thestinger** [comment]
So do it.

**Comment by kyrias** [comment]
@toogy: Feel free to either implement it yourself or try to pay someone to do it.

The maintainers aren't working for you, so unless you do either of the above you can't expect anything to be implemented, and certainly shouldn't act so entitled about it.

**Comment by thestinger** [comment]
I'm not interested in implementing this for the time being.

**Comment by marcospb19** [comment]
I made a [fork](https://github.com/marcospb19/termite) with this implemented.
