### ISSUE TITLE
Missing Vim Motions

### ISSUE THREAD

**Issue by baskerville** [thestinger/termite#134]
It seems there's no _f_, _F_, _,_ or _;_ in command mode.

**Comment by languitar** [comment]
`e` is also missing

**Comment by og01** [comment]
This issue can be closed, I have tested the above motions and they are implemented.

**Comment by thestinger** [comment]
They're not implemented yet.

**Comment by teto** [comment]
When neovim get available as a library, it could help termite support every vim move

**Comment by thestinger** [comment]
I doubt that would help.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
