### ISSUE TITLE
Weird spawning issues.

### ISSUE THREAD

**Issue by vodik** [thestinger/termite#141]
When relying on the config `browser` settings only, it seems like there's something weird going on with how termite is spawning processes.

I unset `BROWSER` and configured `browser = epiphany` as a test. Sometimes epiphany would launch, other times it wouldn't. When it doesn't launch, it actually been started, just now defunct:

~~~~
  PID TTY      STAT   TIME COMMAND
11511 ?        Zl     0:00 [epiphany] <defunct>
~~~~

Not sure why, but we're clearly doing something wrong. @azk on `#archlinux` was complaining that `firefox` wouldn't launch in a simillar configuration.

Not sure whats going on and don't have the time to investigate this atm.

**Comment by thestinger** [comment]
This doesn't seem to be a problem anymore.
