### ISSUE TITLE
Controlling the cursor shape using escape sequences.

### ISSUE THREAD

**Issue by jck** [thestinger/termite#148]
Is it possible to control cursor shape/blinking using escape sequences, to implement something like this: http://vim.wikia.com/wiki/Configuring_the_cursor

**Comment by skosch** [comment]
@jck's link says the patch was commited last year. Would this have since made it into vte-ng?

I'd be grateful for any pointers on to how to get it to work with vim :)

**Comment by skosch** [comment]
... never mind me – `let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1` was enough for neovim, although I had to restart it (reloading the config file didn't do it).
