### ISSUE TITLE
[Feature-Request] A possibility to (really) clear the whole buffer

### ISSUE THREAD

**Issue by niko** [thestinger/termite#151]
I know there's the `clear` shell command and the shortcut CTRL-L. But I would love to have the possibility to clear the whole buffer in a way that you can't scroll up to the old content again. Terminal.app and iTerm.app on OSX have that mapped to Command-K and it's the only thing I'm really missing after switching to Termite. I used to clear the buffer before commands with excessive output so it's easier to scroll up to the beginning.

**Comment by dmfay** [comment]
I have a fairly frequent use case where `reset` by itself isn't sufficient: if I'm tailing a log being written at high speed watching for a specific thing, I can kill `tail` _after_ I see it go past but interrupting it to `reset` can result in hundreds or thousands of lines of stuff I'm not interested in and may not be able to search through effectively. iTerm2's cmd+k does exactly what I need in that situation.
