### ISSUE TITLE
Smarter URL regex, matching leading parentheses / quotes

### ISSUE THREAD

**Issue by Earnestly** [thestinger/termite#155]
Would it be possible to detect if someone has quoted a url in parentheses such that the protocol beings with `(`.  I.e. `(http://foo.bar/(baz))`

Then only match the inner url, ignoring the first leading and trailing parenthesis?

Although this may have issues when they quote the beginning and the url has a valid parenthesis at the end.  `(http://wikipedia.org/foobar(baz)`

**Comment by Earnestly** [comment]
[Apparently](http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding) a valid pathologial url: `"http://example.com/:@-._~!$&'()*+,=;:@-._~!$&'()*+,=:@-._~!$&'()*+,==?/?:@-._~!$'()*+,;=/?:@-._~!$'()*+,;==#/?:@-._~!$&'()*+,;=`

Termite stops after the first `:@-` sequence.

**Comment by Markus00000** [comment]
Rarely if ever do I encounter valid pathological URLs or ones that end with parentheses.

However, URLs enclosed in parentheses are ubiquitous, especially in emails and markdown. Almost all URLs of the many I cannot open in Termite are of this format:

    (http://example.com/)
     --------------------

Ignoring the rightmost parenthesis, if there is one in front of `http`, would fix many matches:

    (http://example.com/)
     -------------------

    (http://example.com/())
     ---------------------

It would not fix this case, which does not currently work either:

    (Go to http://example.com/ or http://example.com/)
           -------------------    --------------------

In my case, ignoring all closing parentheses at the end of URLs would work *virtually all the time.* It would correctly match all the above cases but not this rare one:

    http://example.com/()
    --------------------

Are others regularly clicking URLs ending with parentheses? If not, how about ignoring closing parentheses until someone comes up with a better solution or makes it configurable?

**Comment by Earnestly** [comment]
Many wikipedia URLs will end with a parenthesis.

**Comment by lachesis** [comment]
I have this same problem with single quotes because of the tendancy to print urls using python's repr() function. It's probably my number 1 complaint with termite, which just shows how nice of a terminal emulator it really is. :)

**Comment by coldfix** [comment]
Related to this: If a sentence ends with a URL the trailing period will be considered as part of the url. While this may be technically legal, I have never seen an actual URL ending with a period, but lots of sentences ending with URLs. IMO, trailing periods should not be considered part of the URL.

**Comment by boblehest** [comment]
I just noticed this issue when trying to open a link starting with `https://medium.com/@`. It parses `medium.com/` as the username.

This specific issue can be fixed by honoring the following part of [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt):

> Within the user and password field, any ":", "@", or "/" must be encoded.

Currently, the regex accepts all those symbols as part of the username and password. Also, the regex seems to be missing the colon that sits between `username` and `password`.

**Comment by egmontkob** [comment]
Just FYI: `gnome-terminal` has recently changed its behavior to only allow balanced pairs of parentheses. E.g. in `(http://foo.bar/(baz))` the matching part becomes `http://foo.bar/(baz)`.

See https://bugzilla.gnome.org/show_bug.cgi?id=763980.

**Comment by Airblader** [comment]
Here's a small patch that eliminates some trailing stuff. By no means good enough to be merged, but for some people it might alleviate some immediate pain. :-)

```
diff --git a/url_regex.hh b/url_regex.hh
index 2ec6be8..01bbfb2 100644
--- a/url_regex.hh
+++ b/url_regex.hh
@@ -9,7 +9,7 @@
 #define PORT            "(?:\\:[[:digit:]]{1,5})?"
 #define SCHEME          "(?:[[:alpha:]][+-.[:alnum:]]*:)"
 #define USERPASS        USERCHARS_CLASS "+(?:" PASSCHARS_CLASS "+)?"
-#define URLPATH         "(?:/[[:alnum:]\\Q-_.!~*'();/?:@&=+$,#%\\E]*)?"
+#define URLPATH         "(?:/[[:alnum:]\\Q-_.!~*'();/?:@&=+$,#%\\E]*?[^\\Q`!()[]{};:'\".,<>?«»“”‘’\\E]*)?"
 
 const char * const url_regex = SCHEME "//(?:" USERPASS "\\@)?" HOST PORT URLPATH;
 
```

**Comment by exic** [comment]
Are there any plans to target this issue?

@Airblader, thanks, that feels much better already. Probably a test class to fit all the matching/non matching examples would be good?

I removed the `.` to allow url paths with dots in them and needed to add ` \n` (space/newline) to avoid it including too much, still not perfect though :-\
`#define URLPATH         "(?:/[[:alnum:]\\Q-_.!~*'();/?:@&=+$,#%\\E]*?[^\\Q`!()[]{};:'\",<>«»“”‘’\\E \n]*)?"`

**Comment by egmontkob** [comment]
See also https://gitlab.gnome.org/GNOME/vte/issues/114.

**Comment by varac** [comment]
Also, I often have the issue that termite wrongly includes a trailing dot in the url (like the one in the above comment). It should not do this.

Also, an url in parenthesis should exclude the parenthesis, like this one i.e. (https://ix.de).

**Comment by jelly** [comment]
Untrue, a dot can be part of an url

**Comment by coldfix** [comment]
> Untrue, a dot can be part of an url

While that's technically correct, 99% of the time, a trailing dot is part of the sentence not the URL. I run into this issue regularly and t.b.h have never encountered a trailing dot in an URL.

**Comment by varac** [comment]
> > Untrue, a dot can be part of an url

> While that's technically correct, 99% of the time, a trailing dot is part of the sentence not the URL. I run > nto this issue regularly and t.b.h have never encountered a trailing dot in an URL.

I agree - I'd rather manually correct the one-in-a-million URL by somebody who is insane enough to provide a URL with a trailing dot, than those hundreds I already needed to fix manually because the dot ended the sentence. See https://github.com/thestinger/termite/issues/155#issuecomment-485787860 how github i.e. deals with trailing dots after an URL.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
