### ISSUE TITLE
Customizable URL Hint Characters

### ISSUE THREAD

**Issue by noctuid** [thestinger/termite#160]
I apologize if this is has already been mentioned, but I looked through all the url issues and could not find it. Being able to set the characters used for url hinting would be very nice (I like letters, not numbers and I don't use qwerty so asdf.. is uncomfortable for hinting). I don't think this is a current feature?

For example, like in pentadactyl where you can do something like "set hintkeys=rstneifplu"

**Comment by alex3kov** [comment]
> Keeping hints in the home row would be great.  

Yes it would.

**Comment by jelly** [comment]
I'm for making it configurable, patches are welcome!

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
