### ISSUE TITLE
Cannot send keystrokes with xdotool

### ISSUE THREAD

**Issue by fdietze** [thestinger/termite#167]
Hi,

I'd like to reload the config of several termite windows with a script. This is my current approach:

```
WIDS=`xdotool search --onlyvisible --classname "termite"`
for id in $WIDS; do
      echo -n "$id: "
      xdotool getwindowname $id
      xdotool windowactivate --sync $id
      xdotool windowfocus --sync $id
      xdotool key --window $id ctrl+shift+r
done
```

I can focus the windows but no window receives keystrokes. The same is working with mate-terminal.

Is there another way to trigger a config-reload from a script?

I'm using herbstluftwm on Arch Linux.

Thank you
Felix

**Comment by terlar** [comment]
This still seems to be true, there doesn't seem to be a way to send keystrokes via `xdotool`. `termite` also doesn't seem to work with things like http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Util-Paste.html

Any idea why this is? I tried with other things and there it works, also tried with other vte based terminals.

**Comment by terlar** [comment]
The xmonad thing more specifically would be for example:

```haskell
import XMonad
import XMonad.Util.EZConfig (checkKeymap, additionalKeysP)
import XMonad.Util.Paste

myKeys :: [(String, X ())]
myKeys = [("M-b", pasteString "Hello")
                , ("M-v", sendKey shiftMask xK_Insert)
                ]

myConfig = defaultConfig
    { modMask = mod4Mask
    , terminal = "termite"
    } `additionalKeysP` myKeys

main = xmonad myConfig
```

**Comment by tpanum** [comment]
I came across this issue from a Google search, discovering the same issues. Adding some delay to the key presses of `xdotool` helped me. Specifically `--delay 80` works well for me.
