### ISSUE TITLE
8-bit mode support

### ISSUE THREAD

**Issue by darkfeline** [thestinger/termite#168]
Is it possible to add 8-bit mode support?  It seems like termite runs in 7-bit mode, which means that Alt key shortcuts are prefixed with ^] (escape) instead of an actual Alt modifier bit.

Example: press Alt+P
7-bit mode: sends ^]p (escape key followed by p)
8-bit mode: sends 8 bits with top bit set to indicate modifier

I'm not too familiar with terminal protocols though.

**Comment by HaleTom** [comment]
I just pinged the upstream bug [here](https://bugzilla.gnome.org/show_bug.cgi?id=31316#c35)
