### ISSUE TITLE
Consistent behaviour: u, x, and exiting command mode

### ISSUE THREAD

**Issue by SuperFluffy** [thestinger/termite#175]
I would like to bring to attention that there seems to be an inconsistency between using `x` (to activate url hints mode), and `u` (to forward search a URL).

Highlighting a URL with `u` and following it with Enter exits Command Mode. On the other hand, entering Hints Mode with `x` and pressing a number to follow a hinted URL only exits Hints Mode, but Command Mode stays active.

Personally, I expect both operations to be similar in behaviour. I would therefore suggest that after Hints Mode is exited, Command Mode should be exited as well. I would prefer the solution just described, but an alternative might be that finishing the `u` operation leaves termite in command mode.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
