### ISSUE TITLE
Match multi-lines URL

### ISSUE THREAD

**Issue by toogy** [thestinger/termite#184]
I was looking at the issues and was surprised that this was not mentioned.

When a URL is too long to fit in a window, it's displayed on multiple lines, which is normal. But when using `Ctrl + Shift + X` to select the URL and open it in the browser, only the first line is selected (and then just a part of the URL).

Would it be possible to match multi-lines URLs?

**Comment by toogy** [comment]
@Earnestly: I don't see how this is a workaround.

When I click the URL I just get the first line, not the multi-line URL :/

**Comment by Earnestly** [comment]
You do get a multi-line url.  What I suspect is happening is you're using something like `weechat` which will insert a newline when wrapping the url text.  It does this as a consequence of supporting vertical regions and Linux terminals don't have any real understanding of vertical regions themselves.

If this is the case, use `weechat`'s bare-mode feature which will display the contents of the buffer without any alignment or formatting characters and escapes.

**Comment by toogy** [comment]
I'm already using the bare mode technique on weechat. :octocat: 

The problem actually is in Mutt ^.^

But yes, it's not termite's fault then. Thanks!
