### ISSUE TITLE
"no such file or directory  /etc/profile.d/vte.sh"

### ISSUE THREAD

**Issue by esn89** [thestinger/termite#196]
I just got the latest version of termite after one year on this computer.
I wanted to keep the functionality of "ctrl+shift+t" opening a new terminal of the current dir and i added this little blurb to my .zshrc:

if [[ $TERM == xterm-termite ]]; then
  . /etc/profile.d/vte.sh
  __vte_osc7
fi

and when I start termite, I get this message:

http://i.imgur.com/hAWjDAx.png

Looking in this directory, I realized I never had a vte.sh.  So I was wondering how I can work around this problem?  Is this vte.sh found somewhere?

Thanks

**Comment by lotofthink** [comment]
solved!

https://apple.stackexchange.com/questions/139419/fix-terminal-error-message-bash-etc-profile-d-rvm-sh-no-such-file-or-direct
