### ISSUE TITLE
Adding Back True Transparency Breaks W3M/Ranger Image Viewing

### ISSUE THREAD

**Issue by noctuid** [thestinger/termite#199]
With commit 7612e90, images can no longer be displayed in terminal. Image preview isn't supposed to work with transparency, but even with transparency disabled (1 for the alpha channel) it doesn't work.

**Comment by spcmd** [comment]
Any update on this?

**Comment by autrimpo** [comment]
To continue the issues from my pull request - checking all the colors for possible transparency is easy, however it seems that changing the widget's visual [has no effect after it has been created and drawn.](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-visual)
This makes switching between transparent and opaque mode without restarting termite quite difficult.
Maybe recreating the window and the widget after reloading the config could work, however I have no idea what effect it would have on the terminal and its contents (possibly erasing all scrollback?) and if such behaviour is even desirable.

**Comment by thestinger** [comment]
You might have to hide and show the widget again, I'm not sure.

**Comment by autrimpo** [comment]
Unfortunately, hiding and showing the widget does not work.

I understand that you don't want to regress existing functionality, so if anybody wants to use termite with ranger and doesn't care about transparency (or the need to restart) they can use my ranger-fix branch which uses the system visual as long as no color has transparency.

Better, if anybody has an idea how this could be solved, I'd love to work on it some more and see it merged upstream, but right now I can't really see that happening.

**Comment by esn89** [comment]
i really don't care for termite with transparency, i would just like the pictures to show up on ranger.  your ranger-fix does just that?

**Comment by autrimpo** [comment]
Yes, as long as all your colors are using the *#rrggbb* format (rgba(r,g,b,1) will probably work as well).

**Comment by Eisfreak7** [comment]
Does this mean this won't be implemented in the main repo? I also don't really care for transparency but I'd rather not use some fork if it can be avoided.

**Comment by autrimpo** [comment]
In the current state? Most probably not.
I'd love to see this fixed upstream as well, but the current solution does not allow swtiching between "transparent mode" (which does not work with ranger), and "non-transparent mode" (which does), without restarting termite, which @thestinger (rightfully) sees as regression. So until we can find a solution to this, I don't think he will merge my changes.

**Comment by Eisfreak7** [comment]
That's unfortunate. Thanks for your efforts anyway, of course. But I guess then
I will keep using urxvt when I need to view images for now.

**Comment by thestinger** [comment]
FWIW, sxiv has Vim-like keybindings and a nice thumbnail preview mode.

**Comment by noctuid** [comment]
@autrimpo Thanks for the ranger-fix branch! I'll use this for now.

**Comment by andresmrm** [comment]
+1

**Comment by bb010g** [comment]
:+1:

**Comment by fmthoma** [comment]
This is really a bug in w3m (which is used by ranger to display images). See https://github.com/hut/ranger/issues/86 for details.

For Debian users, it has been fixed in the w3m development repo: https://github.com/tats/w3m/commit/e24b4064daf3e022e370788a8c7267db40c37dda.

**Comment by thestinger** [comment]
Thanks for the update, I'll just close this issue then.

**Comment by fmthoma** [comment]
It seems like I was a little too fast with my comment above: There *were* issues with w3m crashing in terminals with 32bit color that now have been resolved, but image display still does not seem to work according to @noctuid.

**Comment by Vintodrimmer** [comment]
Good day,

Is there still no way to fix this in the main repo? I have the transparency option commented out `#background = rgba(63, 63, 63, 0.8)`, but pictures do not show. In some cases it becomes fully transparent and just shows me the wallpaper where the image should probably be. If I turn the compton off, I just get the blackness of the terminal instead of the picture preview.

**Comment by thestinger** [comment]
It's not a Termite issue.
