### ISSUE TITLE
v9 transparency settings break compositors/window frames

### ISSUE THREAD

**Issue by ptrxyz** [thestinger/termite#200]
I am running termite V9 on xmonad and compton (git, 0.1_beta2.27.gef58e4e-1).
With the patches introduced in v9 compton can not draw solid (non-transparent) window borders (which corresponds to other window manager's window decorations/frames). It seems to be an issue with termite being a 32bit-ARGB window inside a 24bit-RGB frame. 

Same happens if i replace xmonad with dwm and compton with xcompmgr. Reverting to V8 solves the problem.

A config flag to get back the old behaviour would be nice.

**Comment by thestinger** [comment]
I think this has to be dealt with by the window manager. I could make it clever enough to use the default visual when no transparent alpha channels are used in theme but working around *this* window manager bug isn't a good enough reason to do it. I don't think there's any way to solve this when alpha channels are actually used.
