### ISSUE TITLE
Keypresses echoed to terminal instead of desired behaviour

### ISSUE THREAD

**Issue by vixus0** [thestinger/termite#201]
When using commands in any terminal app (tmux, vim, etc.) that involve character keys (eg. moving the cursor) the character is echoed to terminal (bright white with an underline) and I need to press return before the action is executed. This happens even if I'm typing on the commandline and the underline only disappears on pressing space.

This seems to happen after sometime, almost like termite is beginning to lag. It occurs across multiple instances of termite.

Config file: http://sprunge.us/XHZX

**Comment by thestinger** [comment]
I can't replicate this. Are you sure the system where you're running these applications has Termite's terminfo file installed?

**Comment by vixus0** [comment]
Hmm well it's been a while since I filed this and at some point my
configuration changed and I no longer noticed the problem. Guess it can be
closed for now.

**Comment by thestinger** [comment]
It might have been a VTE bug that's now fixed.
