### ISSUE TITLE
Using <S-F{1-4}> mappings to work in vim

### ISSUE THREAD

**Issue by pablox-cl** [thestinger/termite#203]
I just found out, that in vim, with the default termcap/terminfo:

```
echo &term
xterm-termite
```

`<S-F1>` trough `<S-F4>` doesn't work, I solved it mapping the correct key in vim with:

``` viml
if &term =~ 'termite$'
  execute "set <S-F1>=\e[1;2P"
  execute "set <S-F2>=\e[1;2Q"
  execute "set <S-F3>=\e[1;2R"
  execute "set <S-F4>=\e[1;2S"
endif
```

I'm not sure if this is actually a termite problem, or we should add a note about this workaround somewhere.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
