### ISSUE TITLE
Output of commands exectuted with "-e" missing until you add some break.

### ISSUE THREAD

**Issue by ptrxyz** [thestinger/termite#204]
I want to run "ls -la" in a single termite window and keep the window open for the user to close it.
For a first test I simpley use:
     termite --hold -e "/usr/bin/ls"
However I just get a blank, empty window. No output.

To make it more complex:
     /bin/termite --hold -e "/bin/bash -c '/bin/ls'" <-- Still no output.
     /bin/termite --hold -e "/bin/bash -c '/bin/ls; /bin/sleep 1'" <-- Yey! Output!

If I add "Sleep 1" to the commands to be executed, I get output - even after the 1 second passed, the output won't disappear although it shouldn't have to do something with it. I suspect a bug here...

**Comment by erossetto** [comment]
xterm -e man termite <-- works
urxvt -e man termite <-- works
termite -e man termite <-- :(

**Comment by thestinger** [comment]
@erossetto: That works fine here and wouldn't be related to this issue if it didn't. You need quotes around the arguments to `-e` because it doesn't treat it differently from other arguments (and won't).

**Comment by Earnestly** [comment]
@erossetto: xterm and urxvt emply some pretty heavy handed hacks to try and
determine if the arguments given "look like" a command-line and wrap it
appropriately in a call to `sh -c`.  It's quite ugly imo.  Vte just does an
`execve()`, so as @thestinger said, wrap the command-line in quotes and it'll
just work.

**Comment by erossetto** [comment]
I see, ok, good to know -- thanks.

Maybe add a note to the man page? As this changes the expected behavior compared to the other term emulators.

**Comment by thestinger** [comment]
I'm not going to document it because it's just how switches work in command-line applications. There are some very rare exceptions where programs do their own parsing instead of using something like `getopt`, but that's not *expected* at all. Most terminal emulators handle these switches the normal way, not with an ugly hack.

**Comment by thestinger** [comment]
This works fine for me. It was probably a VTE bug.
