### ISSUE TITLE
No color in cmake makefile build process

### ISSUE THREAD

**Issue by Eyenseo** [thestinger/termite#207]
Hello,

I recently switched from urxvt to termite and noticed that the make process is not colored when using cmake makefiles - errors from clang are colored which is nice.

OS: Arch Linux
Kernel: x86_64 Linux 3.17.6-1-ARCH
Termite: v9

**Comment by vodik** [comment]
@Eyenseo http://review.source.kitware.com/#/c/18743/

Once the patch gets through this, it'll land in CMake.

**Comment by Eyenseo** [comment]
@vodik Thank you again!
