### ISSUE TITLE
Would it be possible to implement a line-height option?

### ISSUE THREAD

**Issue by cju** [thestinger/termite#209]
Hi,

is there any chance for this? The only terminal emulator who has this seems to be urxvt, but I don't like it for several reasons (handling of buffer etc.), so I wonder if termite could provide such option.

The use-case is the usage of pretty but way too tall fonts like M+ 1m…

**Comment by thestinger** [comment]
It's not possible for Termite to support this because it's not doing font rendering itself. You can probably get what you want by using a font alias and then configuring it as desired with fontconfig. I've never done something like that before so I'm not sure about the specifics.

**Comment by alerque** [comment]
Same issue, similar issues with `urxvt`, and same request here. Has anybody actually worked up a solution for this or other VTE3 terminals using `fontconfig` (or any other hack) yet?

**Comment by egmontkob** [comment]
This has just been implemented in VTE (forthcoming 0.52), using the new API method `vte_terminal_set_cell_height_scale()`.

**Comment by jelly** [comment]
Fixed in 4aa842245f7abb9328bf37d48f814c7b749e8516
