### ISSUE TITLE
Smooth scrolling.

### ISSUE THREAD

**Issue by ptrxyz** [thestinger/termite#210]
Just wondering: 
Do you have any plans to implement "smooth scrolling" in contrast to current "per-line-scrolling"?

**Comment by skoftoby** [comment]
I'd love something like this. +1

**Comment by jjryan** [comment]
That's something that would have to be implemented in VTE; if I'm not mistaken. Relevant VTE bug: https://bugzilla.gnome.org/show_bug.cgi?id=746690

**Comment by thestinger** [comment]
Yeah, this is an upstream issue in VTE rather than something for Termite to solve.
