### ISSUE TITLE
Add an option to disable italics

### ISSUE THREAD

**Issue by baabelfish** [thestinger/termite#212]
I would really like this feature because italics look really bad with terminus font.

**Comment by thestinger** [comment]
VTE doesn't have a way to do this so I can't expose an option for it. It's already possible to do what you want with fontconfig either Terminus. You can even do per-application configuration in fontconfig by using aliases if you want application-specific font settings. I think that's enough but if VTE does add it, I will be willing to expose an option for it.

**Comment by baabelfish** [comment]
Thanks for the answer!
