### ISSUE TITLE
expose_select_text.patch breaks vte 0.40 compile

### ISSUE THREAD

**Issue by abrouwers** [thestinger/termite#213]
(Sorry in advance :( )  Testing the 0.39.92 tarball, I get:

## -------------- ##

Configuration for libvte 0.39.92 for gtk+-3.0
	GNUTLS: yes
	Installing Glade catalogue: no
	Debugging: no
	Introspection: yes
        Vala bindings: yes
        Test application: yes
	PTY helper: no
make  all-recursive
make[1]: Entering directory '/tmp/makepkg/vte3/src/vte-0.39.92'
Making all in src
make[2]: Entering directory '/tmp/makepkg/vte3/src/vte-0.39.92/src'
  GEN      box_drawing.h
  GEN      marshal.h
  GEN      marshal.c
  GEN      vtetypebuiltins.c
  GEN      stamp-vtetypebuiltins.h
  GEN      vteresources.c
make  all-am
make[3]: Entering directory '/tmp/makepkg/vte3/src/vte-0.39.92/src'
  CC       libvte_2_91_la-caps.lo
  CC       libvte_2_91_la-debug.lo
  CC       libvte_2_91_la-iso2022.lo
  CC       libvte_2_91_la-keymap.lo
  CC       libvte_2_91_la-matcher.lo
  CC       libvte_2_91_la-pty.lo
  CC       libvte_2_91_la-ring.lo
  CC       libvte_2_91_la-table.lo
  CC       libvte_2_91_la-vte.lo
  CC       libvte_2_91_la-vteaccess.lo
  CC       libvte_2_91_la-vteconv.lo
  CC       libvte_2_91_la-vtedraw.lo
vte.c: In function 'vte_terminal_emit_adjustment_changed':
vte.c:1742:15: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
   if (current != v) {
               ^
vte.c:1755:15: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
   if (current != v) {
               ^
vte.c: In function '_vte_terminal_adjust_adjustments_full':
vte.c:1865:8: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if (v != 1) {
        ^
vte.c:1876:8: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if (v != terminal->pvt->row_count) {
        ^
vte.c:1888:8: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if (v != terminal->pvt->row_count) {
        ^
vte.c: In function '_vte_terminal_set_background_alpha':
vte.c:2426:19: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
         if (alpha == pvt->background_alpha)
                   ^
vte.c: In function 'vte_terminal_style_updated':
vte.c:4659:20: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
         if (aspect != terminal->pvt->cursor_aspect_ratio) {
                    ^
vte.c: In function 'vte_terminal_key_press':
vte.c:4781:24: warning: unused variable 'output' [-Wunused-variable]
  char *normal = NULL, *output;
                        ^
vte.c: In function 'vte_terminal_set_cursor_position':
vte.c:6321:23: error: 'struct _VteScreen' has no member named 'cursor_current'
  terminal->pvt->screen->cursor_current.col = column;
                       ^
vte.c:6322:23: error: 'struct _VteScreen' has no member named 'cursor_current'
  terminal->pvt->screen->cursor_current.row = row;
                       ^
Makefile:1426: recipe for target 'libvte_2_91_la-vte.lo' failed
make[3]: *** [libvte_2_91_la-vte.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
vtedraw.c: In function 'context_equal':
vtedraw.c:555:48: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  return pango_cairo_context_get_resolution (a) == pango_cairo_context_get_resolution (b)
                                                ^
make[3]: Leaving directory '/tmp/makepkg/vte3/src/vte-0.39.92/src'
Makefile:1100: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/makepkg/vte3/src/vte-0.39.92/src'
Makefile:549: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/makepkg/vte3/src/vte-0.39.92'
Makefile:457: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EvanPurkhiser** [comment]
Looks like this was fixed in the version on the AUR, but doesn't appear like update is available in this repository just yet.

Though, upgrading to 0.40.0 appears to break other things: https://github.com/thestinger/termite/issues/219

**Comment by thestinger** [comment]
You need to use 0.40.0, not 0.39.92.

**Comment by lethalman** [comment]
@thestinger that error happens also with 0.40.0.
