### ISSUE TITLE
Command mode toggle doesn't work with bépo keymap

### ISSUE THREAD

**Issue by mpo-lacl** [thestinger/termite#214]
I finally found out why I couldn't go into command mode in termite (and consequently why I couldn't dynamically change the size of the font) :-) . It is because I am using the bépo keymap.
In the bépo keymap, the combination of `SHIFT` and `SPACE` yields a non breakable space character such as " ". Thus, entering `CTRL`+`SHIFT`+`SPACE` actually generates the key sequence `CTRL`+`NOBREAKSPACE`.

A workaround for users of bépo such as myself is to change in `termite.cc`, in the switch over `gdk_keyval_to_lowercase`, `GDK_KEY_space` for `GDK_KEY_nobreakspace`.

In the hope it will be useful.

**Comment by thestinger** [comment]
Thanks, fixed.

**Comment by mpo-lacl** [comment]
I opened an issue because a pull request could not easily fix this for everyone.
The only proper change to bring to the code of termite would be to add the ability to specify the shortcuts in the configuration file, which would require a lot of changes. This is intended to stay as a helper note for users in my case.

_I am hereby closing this issue, so please consider this issue closed._

**Comment by thestinger** [comment]
It's not really ideal to have two keycodes for it but I searched and found that other software (Firefox) hard-wires the same thing so why not :P.
