### ISSUE TITLE
 hints for copying lines/words/urls to clipboard

### ISSUE THREAD

**Issue by fdietze** [thestinger/termite#215]
I'd like to have something to copy command line output which is faster than using the mouse. In Selection mode I have to press too many keys to reach and select the piece of text I want.

**Comment by thestinger** [comment]
It would help if the Vim support was more capable too.

**Comment by thestinger** [comment]
You could just use search though.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
