### ISSUE TITLE
Newest vte3-select-text 0.40.0-1 fails to support 256 colors?

### ISSUE THREAD

**Issue by esn89** [thestinger/termite#218]
Just did an upgrade to that latest version and all of a sudden my terminal seems to not be able to display 256 colors.  Did the new vte3 fuck up some older features of itself?

here is the before and after:
http://i.imgur.com/5G4eObT.png

the weird part is that, in the same terminal with the ugly colors, if I start up vim, it has no issues displaying my original colorset:
http://i.imgur.com/zKoTXxb.png

**Comment by thestinger** [comment]
It's fine in master, I just haven't tagged a release.

**Comment by esn89** [comment]
I'll try updating termite, thanks.

**Comment by thestinger** [comment]
In the past, using 256 colors was broken due to an off-by-one error in their range check so I used 255. It was fixed and then they forced the full palette to be set, so the old code stopped working.

**Comment by esn89** [comment]
Thanks for the clarification.  Master works, as I have just updated.
