### ISSUE TITLE
vte3-select-text 0.40.0 breaks colors

### ISSUE THREAD

**Issue by EvanPurkhiser** [thestinger/termite#219]
Upgrading to `vte3-select-text` version 0.40.0 breaks terminal colors. Downgrading to 0.38.3 fixes things.

![image](https://cloud.githubusercontent.com/assets/1421724/7130900/809e4c4a-e22c-11e4-9204-80fa8f1d3972.png)

(left: with vte3-select-text 0.38.3, right: with vte3-select-text 0.40.0)

**Comment by thestinger** [comment]
You need to update Termite too. The old versions don't support 0.40.0.

**Comment by toogy** [comment]
Had the same issue. `yaourt -S termite-git` worked :)
