### ISSUE TITLE
Feature request: Margins

### ISSUE THREAD

**Issue by osum4est** [thestinger/termite#220]
Hello! I'm loving termite but it is missing one thing that I loved from URxvt. Margins, or an internal border. Basically blank space around the text so it doesn't feel so cramped. I think it would be an amazing addition!

**Comment by holomorph** [comment]
IIRC you can do this with gtk css

**Comment by jschx** [comment]
I agree. This is the only thing I'm missing from urxvt.

**Comment by jschx** [comment]
Actually, I just found issue #202, maybe something should be included in the documentation about that. Extra config options probably aren't needed, then.
