### ISSUE TITLE
termite no longer starts after system update

### ISSUE THREAD

**Issue by Markus00000** [thestinger/termite#222]
Error message:

>**
>Vte:ERROR:vtestream-file.h:805:_vte_boa_init: assertion failed (gnutls_cipher_get_iv_size(VTE_CIPHER_ALGORITHM) == VTE_CIPHER_IV_SIZE): (0 == 12)

* Arch Linux
* termite 10-1
* gnutls-3.4.0-1-x86_64.pkg.tar.xz

**Comment by holomorph** [comment]
not a termite bug. rebuild vte

**Comment by Markus00000** [comment]
If it is not a termite bug and vte has been installed from the official repository, then it is an Arch bug, correct?
