### ISSUE TITLE
Error since gnutls latest update

### ISSUE THREAD

**Issue by c0m3tx** [thestinger/termite#223]
Since latest gnutls update today, termite crashes on load with 
`termite: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory`

Reverting `gnutls` allows me to launch termite again. I'm on Arch and I'm using the AUR `termite-git` package, but if I try to recompile it a get a unrecoverable error.

Is the code on github "newer"? Should I download it manually and compile it?

Thank you very much.

**Comment by LinuCC** [comment]
Rebuilding vte3-select-text will solve the problem, you dont need to revert gnutls.
With pacaur, `pacaur -S vte3-select-text` solved it for me.

**Comment by thestinger** [comment]
Yeah, it's vte3-select-text that needs to be recompiled. Life would be a lot easier if upstream just provided the necessary functionality.

**Comment by c0m3tx** [comment]
Thanks guys, it worked.
