### ISSUE TITLE
Error in terminfo

### ISSUE THREAD

**Issue by Ploppz** [thestinger/termite#225]
Hi.

I had the problem that when I would specify bolded dark red colour (colour number 1), it would show up as bold *bright* red in termite. Someone guided me through fixing this, and the error was in [termite.terminfo](https://github.com/thestinger/termite/blob/master/termite.terminfo), where these lines:
```
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
```
need to be substituted by:
```
	setab=\E[48;5;%p1%dm,
	setaf=\E[38;5;%p1%dm,
```

**Comment by purpleKarrot** [comment]
#245 also refers to this issue.

**Comment by thestinger** [comment]
It's supposed to be this way. Using an incorrect terminfo definition to "add" a feature isn't a sane approach. You should get the feature added in VTE as an option if you want it.
