### ISSUE TITLE
Issues with ssh 

### ISSUE THREAD

**Issue by yungstorm** [thestinger/termite#229]
[~] clear                                                              
'xterm-termite': unknown terminal type.

The box i'm connecting to is running debian 8 jessie and this happens with every shell that i use in this box. Anyone have any ideas ?

**Comment by holomorph** [comment]
install the terminfo to the remote

**Comment by thestinger** [comment]
`tic -x termite.terminfo` will install it to the per-user terminfo database, or globally if run as root.

**Comment by influenza** [comment]
Installing on the remote is not a solution.

**Comment by thestinger** [comment]
You don't need to install Termite on the remote.

**Comment by da-n** [comment]
> You don't need to install Termite on the remote.

Can you please explain exactly what the solution is to avoid this message showing whilst SSH to remote? The following:

`tic -x termite.terminfo`

Only produces an error on both client and server:

`tic: termite.terminfo No such file or directory`

Thanks.

**Comment by jelly** [comment]
tic expects a termite.terminfo file which does not exist in your current working directory. On your client you can either copy the one from the package or generate it with infocmp

```
infocmp > termite.terminfo
```

Then copy it to the server and tic -x termite.terminfo.

**Comment by da-n** [comment]
OK thanks that's appreciated. Am I correct in assuming the above would need to be repeated for every remote server I connect to over SSH? Is there a way to permanently prevent this error from the client end only?

**Comment by velovix** [comment]
Is there any reason why the TERM value needs to be something custom like this? Every other terminal I know of masquerades as xterm or xterm-256colors which seems to work fine and avoids this issue.

**Comment by thestinger** [comment]
It needs to be a custom value since xterm/xterm-256color are not entirely correct for VTE and are also missing some features.
