### ISSUE TITLE
Urgency hint should probably be unset when losing focus

### ISSUE THREAD

**Issue by dubhater** [thestinger/termite#23]
If the urgency hint is set before I switch to another tag, termite's tag is still marked urgent (awesome window manager).

**Comment by beanaroo** [comment]
Is this considered not a bug?

When an SSH connection dies, urgent hint gets set but it never gets unset.

**Comment by thestinger** [comment]
It's unset when the window has window. If it's not working, that sounds like a window manager problem. This is primarily a VTE feature, not a Termite feature.

**Comment by beanaroo** [comment]
Interesting. Thanks for the prompt response. When running tmux, urgent hint is set/unset as expected.
