### ISSUE TITLE
[Q] line spacing: how to?

### ISSUE THREAD

**Issue by gaydenko** [thestinger/termite#232]
Hi!

How to set line spacing?

**Comment by thestinger** [comment]
Termite isn't responsible for font rendering so it doesn't offer this feature. I would expose it if VTE offered it, but it doesn't. I would merge a *simple* patch implementing it in [vte-ng](https://github.com/thestinger/vte-ng) but not something non-trivial to maintain.

**Comment by thestinger** [comment]
I think it's possible to configure this with fontconfig, but I don't know how to do it anymore.

**Comment by Earnestly** [comment]
Fontconfig isn't able to adjust line-height via its configuration, it would need to be handled by the program in question.

**Comment by gaydenko** [comment]
@Earnestly , I'd want to increase line height rather to reduce it :)
A working area padding can be adjusted with `gtk.css`. I have guessed there is an opportunity to adjust line spacing also, but all my attempts have failed.

**Comment by Earnestly** [comment]
That unfortunately lies in the domain of the terminal emulator then.

**Comment by madx** [comment]
Hi!

I'd really like this feature as well.

Maybe there is something interesting in this thread: https://bugzilla.gnome.org/show_bug.cgi?id=738781

**Comment by josswright** [comment]
There's been some significant-looking movement on this on the vte side -- is this still a possibility in termite if vte implements it?

Discussion here: https://bugzilla.gnome.org/show_bug.cgi?id=781479

**Comment by dshoreman** [comment]
@thestinger @jelly Support for line spacing was added to vte in GNOME/vte@26c79c6dc93aae4d4f787f36b594cac151df0f07, could that be merged into vte-ng to reopen this issue?

Looks like vte-ng is a bit behind compared to the main vte repo though so I'm not sure how easy it'd be to update it.

**Comment by jelly** [comment]
Latest vte-ng is  0.50.2.a-1 which is the latest vte release

**Comment by dshoreman** [comment]
The latest I'm seeing is 0.48.2, am I looking in the wrong place? Still pretty new to Termite/VTE-ng

**Comment by jelly** [comment]
Yes, it's not selected as default branch.

**Comment by jelly** [comment]
Pushed https://github.com/thestinger/vte-ng/tree/0.50.2-ng

**Comment by josswright** [comment]
Is there a way to control line spacing now, then?

**Comment by jelly** [comment]
No, since nobody has made a pull request to implement this new feature.

**Comment by jelly** [comment]
Fixed in 4aa842245f7abb9328bf37d48f814c7b749e8516

**Comment by binaryplease** [comment]
Reducing the line space is not working for me:
I added: 
```
cell_height_scale = 0.5
```

to my config but that does nothing. Adding values greater than one works just nothing lower. 
I also tried setting it to `1.9` which also works fine, so it seems it's not limited to integer values.

**Comment by dtzWill** [comment]
Vte enforces these limits, see the source and probably api docs for more info.
