### ISSUE TITLE
The termite-git AUR package needs to be updated

### ISSUE THREAD

**Issue by deiwin** [thestinger/termite#233]
[The current package](https://aur.archlinux.org/packages/termite-git/) references `vte3-select-text` as a dependency, but apparently the package doesn't exist anymore and has been replaced by [vte3-ng](https://www.archlinux.org/packages/community/i686/vte3-ng/), available from the community repository.

I don't have an account on aur.archlinux.org, and due to the current migration to AUR4 I am unable to create one. Because of this, I can't mark the package outdated on AUR myself.

**Comment by deiwin** [comment]
Okay, my bad. I'm just now learning that *termite* itself is also [being moved to the community repository](https://www.archlinux.org/packages/community/i686/termite/). So I guess this is already being taken care of.

**Comment by thestinger** [comment]
It doesn't matter because vte3-ng provides vte3-select-text.
