### ISSUE TITLE
Core dump on resize in mutt

### ISSUE THREAD

**Issue by mpo-lacl** [thestinger/termite#234]
Hi, I'm having a core dump while changing the zoom in termite, only with some applications running, for instance mutt.

Steps to reproduce:

1. In termite, launch an applcation
```
$ mutt
```
2. Press the combination of key CTRL+MAJ+SPACE to enter selection mode
3. Press `+` or `-` to increase or decrease font size
4. Press ESC to leave selection mode
5. Press any other key and it crashes with
```
**
Vte:ERROR:ring.c:394:_vte_ring_thaw_one_row: assertion failed: (ring->start < ring->writable)
[1]    13030 abort (core dumped)  termite
```

**Comment by thestinger** [comment]
Closing in favour of #194.
