### ISSUE TITLE
Build problem on Debian testing

### ISSUE THREAD

**Issue by rapha8l** [thestinger/termite#236]
Hi,

vte-ng is installed and many dev libraries, though I get this error at make time :

g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v10-13-geb1628c\" -pthread -I/usr/local/include/vte-2.91 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/p11-kit-1   -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lgnutls  -o termite
termite.cc: In function ‘int main(int, char**)’:
termite.cc:1503:10: warning: ‘GtkWidget* gtk_alignment_new(gfloat, gfloat, gfloat, gfloat)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:79) [-Wdeprecated-declarations]
          gtk_alignment_new(0, 0, 1, 1),
          ^
termite.cc:1503:38: warning: ‘GtkWidget* gtk_alignment_new(gfloat, gfloat, gfloat, gfloat)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:79) [-Wdeprecated-declarations]
          gtk_alignment_new(0, 0, 1, 1),
                                      ^
termite.cc:1530:5: warning: ‘void gtk_alignment_set_padding(GtkAlignment*, guint, guint, guint, guint)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:91) [-Wdeprecated-declarations]
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
     ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from termite.cc:31:
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:38:46: warning: ‘GType gtk_alignment_get_type()’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:77) [-Wdeprecated-declarations]
 #define GTK_TYPE_ALIGNMENT                  (gtk_alignment_get_type ())
                                              ^
/usr/include/glib-2.0/gobject/gtype.h:2186:61: note: in definition of macro ‘_G_TYPE_CIC’
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                             ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:46: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                              ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:81: note: in expansion of macro ‘GTK_TYPE_ALIGNMENT’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                                                                 ^
termite.cc:1530:31: note: in expansion of macro ‘GTK_ALIGNMENT’
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                               ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:38:70: warning: ‘GType gtk_alignment_get_type()’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:77) [-Wdeprecated-declarations]
 #define GTK_TYPE_ALIGNMENT                  (gtk_alignment_get_type ())
                                                                      ^
/usr/include/glib-2.0/gobject/gtype.h:2186:61: note: in definition of macro ‘_G_TYPE_CIC’
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                             ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:46: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                              ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:81: note: in expansion of macro ‘GTK_TYPE_ALIGNMENT’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                                                                 ^
termite.cc:1530:31: note: in expansion of macro ‘GTK_ALIGNMENT’
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                               ^
termite.cc:1530:74: warning: ‘void gtk_alignment_set_padding(GtkAlignment*, guint, guint, guint, guint)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:91) [-Wdeprecated-declarations]
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                                                                          ^
#      

Thanks

**Comment by thestinger** [comment]
There's no error there, just a warning about GtkAlignment being deprecated. I haven't had time to migrate to the new system for adding padding yet.

**Comment by rapha8l** [comment]
Ok, I missed my copy/paste, here it comes

g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v10-13-geb1628c\" -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/p11-kit-1 -I/usr/include/vte-2.91   -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc -L/usr/lib/x86_64-linux-gnu -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lgnutls  -o termite
termite.cc: In function ‘void update_selection(VteTerminal*, const select_info*)’:
termite.cc:403:85: error: ‘vte_terminal_set_selection_block_mode’ was not declared in this scope
     vte_terminal_set_selection_block_mode(vte, select->mode == vi_mode::visual_block);
                                                                                     ^
termite.cc:410:60: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      cursor_col, cursor_row);
                                                            ^
termite.cc:413:74: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      select->begin_col, select->begin_row);
                                                                          ^
termite.cc:419:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc:425:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc: In function ‘void enter_command_mode(VteTerminal*, select_info*)’:
termite.cc:432:41: error: ‘vte_terminal_disconnect_pty_read’ was not declared in this scope
     vte_terminal_disconnect_pty_read(vte);
                                         ^
termite.cc: In function ‘void exit_command_mode(VteTerminal*, select_info*)’:
termite.cc:439:81: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, select->origin_col, select->origin_row);
                                                                                 ^
termite.cc:440:38: error: ‘vte_terminal_connect_pty_read’ was not declared in this scope
     vte_terminal_connect_pty_read(vte);
                                      ^
termite.cc: In function ‘void move(VteTerminal*, select_info*, long int, long int)’:
termite.cc:489:92: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
                                      clamp(cursor_row + row, first_row(vte), last_row(vte)));
                                                                                            ^
termite.cc: In function ‘void move_to_row_start(VteTerminal*, select_info*, long int)’:
termite.cc:496:49: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, 0, row);
                                                 ^
termite.cc: In function ‘void open_selection(char*, VteTerminal*)’:
termite.cc:503:68: error: ‘vte_terminal_get_selection’ was not declared in this scope
         auto selection = make_unique(vte_terminal_get_selection(vte), g_free);
                                                                    ^
termite.cc: In function ‘void move_backward(VteTerminal*, select_info*, F)’:
termite.cc:555:65: error: there are no arguments to ‘vte_terminal_set_cursor_position’ that depend on a template parameter, so a declaration of ‘vte_terminal_set_cursor_position’ must be available [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc:555:65: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
termite.cc: In function ‘void set_cursor_column(VteTerminal*, const select_info*, long int)’:
termite.cc:601:61: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, column, cursor_row);
                                                             ^
termite.cc: In function ‘void move_forward(VteTerminal*, select_info*, F)’:
termite.cc:667:65: error: there are no arguments to ‘vte_terminal_set_cursor_position’ that depend on a template parameter, so a declaration of ‘vte_terminal_set_cursor_position’ must be available [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In function ‘int main(int, char**)’:
termite.cc:1503:10: warning: ‘GtkWidget* gtk_alignment_new(gfloat, gfloat, gfloat, gfloat)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:79) [-Wdeprecated-declarations]
          gtk_alignment_new(0, 0, 1, 1),
          ^
termite.cc:1503:38: warning: ‘GtkWidget* gtk_alignment_new(gfloat, gfloat, gfloat, gfloat)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:79) [-Wdeprecated-declarations]
          gtk_alignment_new(0, 0, 1, 1),
                                      ^
termite.cc:1530:5: warning: ‘void gtk_alignment_set_padding(GtkAlignment*, guint, guint, guint, guint)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:91) [-Wdeprecated-declarations]
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
     ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from termite.cc:31:
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:38:46: warning: ‘GType gtk_alignment_get_type()’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:77) [-Wdeprecated-declarations]
 #define GTK_TYPE_ALIGNMENT                  (gtk_alignment_get_type ())
                                              ^
/usr/include/glib-2.0/gobject/gtype.h:2186:61: note: in definition of macro ‘_G_TYPE_CIC’
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                             ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:46: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                              ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:81: note: in expansion of macro ‘GTK_TYPE_ALIGNMENT’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                                                                 ^
termite.cc:1530:31: note: in expansion of macro ‘GTK_ALIGNMENT’
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                               ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:38:70: warning: ‘GType gtk_alignment_get_type()’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:77) [-Wdeprecated-declarations]
 #define GTK_TYPE_ALIGNMENT                  (gtk_alignment_get_type ())
                                                                      ^
/usr/include/glib-2.0/gobject/gtype.h:2186:61: note: in definition of macro ‘_G_TYPE_CIC’
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                             ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:46: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                              ^
/usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:39:81: note: in expansion of macro ‘GTK_TYPE_ALIGNMENT’
 #define GTK_ALIGNMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ALIGNMENT, GtkAlignment))
                                                                                 ^
termite.cc:1530:31: note: in expansion of macro ‘GTK_ALIGNMENT’
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                               ^
termite.cc:1530:74: warning: ‘void gtk_alignment_set_padding(GtkAlignment*, guint, guint, guint, guint)’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkalignment.h:91) [-Wdeprecated-declarations]
     gtk_alignment_set_padding(GTK_ALIGNMENT(info.panel.panel), 5, 5, 5, 5);
                                                                          ^
termite.cc: In instantiation of ‘void move_backward(VteTerminal*, select_info*, F) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]’:
termite.cc:562:44:   required from here
termite.cc:555:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In instantiation of ‘void move_backward(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:566:70:   required from here
termite.cc:555:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
termite.cc: In instantiation of ‘void move_forward(VteTerminal*, select_info*, F) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]’:
termite.cc:674:43:   required from here
termite.cc:667:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In instantiation of ‘void move_forward(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:678:69:   required from here
termite.cc:667:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
termite.cc: In instantiation of ‘void move_first(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:808:86:   required from here
termite.cc:591:76: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
         vte_terminal_set_cursor_position(vte, iter - codepoints, cursor_row);
                                                                            ^
Makefile:36: recipe for target 'termite' failed
make: *** [termite] Error 1

**Comment by thestinger** [comment]
It looks like vte-ng isn't installed. It's using the vanilla VTE header.

**Comment by rapha8l** [comment]
Ok, It was not on the same box.
It works well.
Sorry for the noise and thanks for helping
