### ISSUE TITLE
Pseudo-transparency Alternative?

### ISSUE THREAD

**Issue by Anon72521** [thestinger/termite#237]
Since VTE no longer supports pseudo-transparency, would it be possible for you to give me the source for version 7 so I can downgrade? I'm using Archlinux, and when I upgraded from version 7 to version 9, version 7 got wiped out completely and I'm not even able to downgrade.

Thanks

**Comment by thestinger** [comment]
It's at https://github.com/thestinger/termite/releases/tag/v7 but it will have known bugs and probably won't run with GTK 3.16.
