### ISSUE TITLE
feature to have an option to disable italics

### ISSUE THREAD

**Issue by jasonsmith0** [thestinger/termite#244]
Due the screen bug which rears its head a lot when using tmux (italics is displayed when doing reverse search in less) it would be nice if one could disable italic support directly in the clients terminal.

Something like:
```
allow_italic = false
```

I know one can fix the source of the bug and that is to create a new terminfo file but for many reasons one may prefer to simply disable italics support in the clients terminal directly.

**Comment by thestinger** [comment]
VTE doesn't support this and I'm not interested in writing/maintaining a patch for it. I think you should just fix the issue properly instead of working around it.

**Comment by Earnestly** [comment]
@jasonsmith0 This is a bug in tmux (although they claim it's not) -- see their FAQ for how to hack around it: https://github.com/tmux/tmux/blob/master/FAQ#L355
