### ISSUE TITLE
Feature request: "intensityStyles" equivalent

### ISSUE THREAD

**Issue by tpict** [thestinger/termite#245]
urxvt has an "intensityStyles" parameter which when set to false allows bold fonts to be drawn without having their colour changed. As far as I know, termite doesn't have an option like this, so for example bold text intended to be drawn in color0 is drawn in color8 instead.

[Here](http://dl.dropboxusercontent.com/u/25718506/tpic/300715-181016_s.png) is an example showing the difference between urxvt with intensityStyles=false and termite.

**Comment by arkrost** [comment]
It seems that it is not supported by VTE. Maybe it can be added in vte-ng.

vte.cc
```c
void
VteTerminalPrivate::determine_colors(...) 
{
    /* Handle bold by using set bold color or brightening */
	if (attr->bold) {
		if (fore == VTE_DEFAULT_FG)
			fore = VTE_BOLD_FG;
		else if (fore >= VTE_LEGACY_COLORS_OFFSET && fore < VTE_LEGACY_COLORS_OFFSET + VTE_LEGACY_COLOR_SET_SIZE) {
			fore += VTE_COLOR_BRIGHT_OFFSET;
		}
	}
...
}
```

**Comment by thestinger** [comment]
You should submit it upstream. I'm not going to maintain features I don't use in vte-ng.

**Comment by thestinger** [comment]
This can be supported if and when VTE supports it.

**Comment by Gomme-** [comment]
@thestinger : VTE seems to support that ( in Gnome-terminal ) "vte_terminal_set_bold_is_bright".  Would be really nice to have that feature in Termite :)

**Comment by egmontkob** [comment]
VTE added this feature just recently, in 0.52.

**Comment by dstokes** [comment]
[Here's the VTE commit adding `vte_terminal_set_bold_is_bright`](https://github.com/GNOME/vte/commit/6c44229d130dd1d5cdb218e897ec6f245e96d538)

**Comment by carloabelli** [comment]
Let me know if there is anything I missed in the PR. I'd love to see this feature
