### ISSUE TITLE
fullscreen option missing in man page

### ISSUE THREAD

**Issue by soapsurfer** [thestinger/termite#248]
fullscreen option is not documented in man 5 termite.config

**Comment by EliteTK** [comment]
In fact, modify_other_keys is also undocumented.

Additionally, the options "resize_grip" and "visible_bell" are documented but don't seem to be read. (at least not from my tests) "visible_bell" definitely doesn't make anything flash and "resize_grip" doesn't seem to show a resize grip.

I can make a pull request with a corrected config and termite.config man page.
