### ISSUE TITLE
--geometry can't place windows on second monitor

### ISSUE THREAD

**Issue by oatberry** [thestinger/termite#249]
Hi, I have two 1920x1080 monitors side-by-side. When I try to have termite open a window with an X,Y coord that is on the second monitor, it opens the terminal at an equivalent position on the first monitor.

[Here's](https://ptpb.pw/Os5C.mp4) a short video demonstration. Thanks!

**Comment by thestinger** [comment]
What's the output of that `slop` command when used on each monitor?

**Comment by thestinger** [comment]
I can't reproduce this, so I'll have to assume it's not an issue anymore.
