### ISSUE TITLE
--geometry

### ISSUE THREAD

**Issue by cinelli** [thestinger/termite#25]
It'd be nice if it reacted to --geometry flag.

**Comment by reisub0** [comment]
Is --geometry still implemented in Termite, or was there a recent commit that removed it? My scripts that relied on it recently stopped working with the following error
```
option parsing failed: Unknown option --geometry
```

**Comment by jelly** [comment]
It was removed in https://github.com/thestinger/termite/commit/8f6ce5239fbc635755e3ac23d79579ee057f7993 since that feature was deprecated by VTE.

**Comment by polyzen** [comment]
@reisub0, this project has recently started using release notes:
https://github.com/thestinger/termite/releases/tag/v14
