### ISSUE TITLE
Terminal window opens, then closes immediately 

### ISSUE THREAD

**Issue by xhevahir** [thestinger/termite#250]
So, I've installed termite on Linux Mint using [this script](https://github.com/Corwind/termite-install), and things seem to be installed OK, but calling termite from the shell causes a terminal window to open and then immediately close. I tried also to set my default shell to termite, and to set up a launcher on the desktop, but always with the same result. Is there some step to the configuration that I may have omitted? (I'm on fish shell; maybe that's a common source of problems?)

Edit: forgot to add that piping the output and stderr resulted in an empty file.

**Comment by thestinger** [comment]
I don't think this is caused by a bug in Termite. I'm not able to provide technical support for a distribution I don't use. All I can say is that it works for me, there's an official package in Arch Linux and it seems to work for other people on Ubuntu and Linux Mint (but I've never tested myself).
