### ISSUE TITLE
Inconsulata under Arch

### ISSUE THREAD

**Issue by favetelinguis** [thestinger/termite#251]
Im trying to get Inconsulata bold 15 working under Arch Linux. fc-list finds inconsulata installed as such:
/usr/share/fonts/OTF/Inconsolata.otf: Inconsolata:style=Medium
However im not sure if termite is rendering the font correct. Im getting overlapping characters for example "m00m" looks terrible.

Im referencing as such:
font = inconsulata bold 16

Am I referencing it with the wrong name or am is there an issue with termite?

**Comment by favetelinguis** [comment]
It seems that I can use whatever name i want in:
font = adfsasdfa bold 16
and the only thing termite picks up is the font size and then uses some default font?? Not sure it enven uses inconsulata?

**Comment by thestinger** [comment]
Fontconfig will fall back to another font if it doesn't find the one that's set. It's probably picking a proportional one rather than a monospace font so that's why it the layout is screwed up.

Does this work?

```
font = Inconsolata Bold 16
```

**Comment by favetelinguis** [comment]
No it makes no difference. Why is the size picked up for oter fonts but not bold?

**Comment by thestinger** [comment]
It's part of the name, not a modifier.

**Comment by Earnestly** [comment]
https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-from-string

**Comment by favetelinguis** [comment]
Is there a way to se the startup log in termite to try and figure out what is happening when trying to access the font?

**Comment by Earnestly** [comment]
The fonts-conf(5) lists debugging environments such as FC_DEBUG.

**Comment by favetelinguis** [comment]
It was a typo causing the error. Sorry, been at it many hours installing arch for the first time, needed som sleep :)
