### ISSUE TITLE
Losing history on 'resize'?

### ISSUE THREAD

**Issue by SRGOM** [thestinger/termite#252]
Steps:
1) Open a termite session and output long lines. 
2) Resize the window to a very small width such that the long lines are wrapped, as much as possible. Its not possible to go back in history now too far.

**Comment by thestinger** [comment]
This sounds like a VTE issue, although I can't see to replicate it. Does it happen for you in gnome-terminal?

**Comment by SRGOM** [comment]
Sorry, I really hadn't given any information.
I compiled termite using this script: https://github.com/Corwind/termite-install
My termite version is: termite v10-13-geb1628c
`git rev-parse  HEAD` on code that I compiled: a233b27595c24cee90de0b8fbf207a475cefa91f
`uname -a` Linux OldAndHeavy 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:30:01 UTC 2014 i686 i686 i686 GNU/Linux

gnome-terminal and konsole don't have it, but it may be because they don't try to wrap lines when the size changes dynamically (fwiw I love the termite way to wrap lines on resize) 

Please let me know if I can provide more information.

**Comment by thestinger** [comment]
gnome-terminal does wrap lines in the same way. It's a property of VTE. If your copy isn't wrapping, then you're not comparing the same VTE version.

**Comment by thestinger** [comment]
You should just make the history longer. The line rewrapping is a normal property of VTE.
