### ISSUE TITLE
What mouse functions are supported?

### ISSUE THREAD

**Issue by mindstormer12** [thestinger/termite#253]
I'm new to Linux and was wondering what mouse functions exist for termite. The only thing I found was that you can highlight and then middle-click to paste, but only at where the cursor is (which seems can only be dictated by the arrow keys on the keyboard). Why can't I left-click on the terminal to dictate which line the cursor will be in? Also, how can I change the middle-click paste to a right-click paste, since the right-click seems to have no function on termite?

I apologize if this is not the right place to ask this type of question (I'm not sure where to ask otherwise,  new to github). Thanks!

**Comment by thestinger** [comment]
Termite doesn't provide any mouse bindings itself beyond setting up clickable links. It's just whatever is provided by GTK+ and VTE and can be configured to the extent that they support it. Middle-click for pasting the X11 selection is just basic GTK+ functionality that's also supported by nearly every other X11 application.  It could support using the mouse in command mode for moving the cursor but it would be fairly pointless. If you're using the mouse, you can just do the text selection with it directly.

Outside of Termite's command mode (see the README), you're interacting with the programs in the terminal (like the shell) when you're using the arrow keys. Terminal programs can also grab mouse input if they want it.

**Comment by thestinger** [comment]
In insert mode, the only keybindings that are interacting with Termite rather than being passed through to the program in the terminal are the ones listed in the README for insert mode (if there is some VTE binding not listed there, I'll happily add it).
