### ISSUE TITLE
termite lacks support for OSC 52 (clipboard operation) escape sequences

### ISSUE THREAD

**Issue by Celti** [thestinger/termite#254]
Certain terminals (mlterm, hterm) and recent versions of tmux have full support for OSC52 escape sequences for implementing copy/paste to the system clipboard over, e.g., SSH sessions without requiring full X forwarding. The best description of OSC 52 I can find publically available is [here](https://git.chromium.org/gitweb/?p=chromiumos/platform/assets.git;a=blob;f=chromeapps/nassh/doc/faq.txt;h=e86f86e77126a1bc4470febe933bb7aab4879c40;hb=HEAD#l589). I am not sure if this is more properly a libvte request or a termite request — apologies if it should be the other.

**Comment by wiwo192** [comment]
+1.
I am hesitating to migrate away from good old urxvt because of this.

**Comment by thestinger** [comment]
AFAIK this is a VTE deficiency, not one in the Termite frontend.

**Comment by thestinger** [comment]
This can be supported if and when VTE supports it.

**Comment by FranklinYu** [comment]
VTE feature request for OSC 52: https://gitlab.gnome.org/GNOME/vte/-/issues/125
