### ISSUE TITLE
font styles do not seem to be supported

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [thestinger/termite#255]
I've tried various ways to select the font style for Termite. There does not seem to be an option to set font styles, if there is I have yet to find it anywhere online or in the man page for Termite. For example, I love using the Source Code Pro for Powerline font, but I want to set it to medium because it makes it a bit easier to read for me.

Since Termite uses fontconfig to set fonts, it would seem to be simple to add if that ability isn't hidden away somewhere, I think.

**Comment by thestinger** [comment]
Does `font = Source Code Pro Medium 10` work?

**Comment by DerVerruckteFuchs** [comment]
That was one of the ways I've tried it. I opened up Konsole, which has Source Code Pro set to medium, to compare with Termite after setting the font that way. The font in Termite seemed to either be plain Source Code Pro or the default font. I also used `font = Source Code Pro medium 10`, and `font = Source Code Pro 10` with `font-weight = medium`. Neither of those worked either. I've even tried logging out and back in again.

**Comment by Earnestly** [comment]
@DerVerruckteFuchs https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-from-string

The format is essentially `family style size`.   Add the optional comma it discusses thus: `font = Foo Bar Family, Medium 10`

See if that works.

**Comment by DerVerruckteFuchs** [comment]
So I've tried `font = Source Code Pro, Medium 10` and `font = Source Code Pro, medium 10` reloaded my `~/.config/termite/config` and the font weight stayed the same.

**Comment by thestinger** [comment]
Using either `font = Source Code Pro Medium 10` or `font = Source Code Pro, Medium 10` works for me. The difference is subtle but it's easy to tell when using `ctrl-shift-r` to reload the configuration.

**Comment by DerVerruckteFuchs** [comment]
So I've double checked after reloading. It did change the font to medium when comparing to an older Termite window that I've left open this whole time that had been set to regular. What threw me off was using Konsole to compare the fonts between the different terminal windows during config reloads. Konsole makes the medium font appear thicker or maybe a bit whiter for some reason. I do have font smoothing turned on in Konsole. Also I'm using the default Zenburn theme included with Konsole, while I got the colors copypasted from my old ~/.Xresources file for my Termite config. It was just slightly different enough to bug me that I looked at it a bit too hard and thought it went to the default font in Termite or something.

And I used `font = Source Code Pro for Powerline, Medium 10`, btw. I would also like to suggest that explicitly stating how to use font styles in Termite's man page would be helpful for future reference. Thanks for your help.

**Comment by Earnestly** [comment]
Since you've changed the typeface, try seeing which styles it actually contains, for example:

```teapot earnest %i master ~ fc-list -f '%{style}\n' "Source Code Pro"       
Black Italic,Italic
Medium,Regular
Bold
Medium Italic,Italic
ExtraLight Italic,Italic
Semibold,Regular
Bold Italic,Bold
Regular
Light Italic,Italic
Italic
Semibold Italic,Italic
Light,Regular
Black,Regular
ExtraLight,Regular
```

**Comment by DerVerruckteFuchs** [comment]
output of `fc-list -f '%{style}\n' "Source Code Pro"`:
Medium,Regular
ExtraLight,Regular
Bold
Semibold,Regular
Black,Regular
Regular
Light,Regular

output of `fc-list -f '%{style}\n' "Source Code Pro for Powerline"`
Medium,Regular
Regular
Black,Regular
Light,Regular
Bold
Medium,Regular
ExtraLight,Regular
Black,Regular
Light,Regular
Semibold,Regular
Semibold,Regular
Bold
ExtraLight,Regular
Regular


Since I have both installed.

**Comment by Earnestly** [comment]
While this is fixed; your Source Code Pro looks quite wrong.

**Comment by DerVerruckteFuchs** [comment]
I was fiddling with getting powerline working with urxvt and had been trying all the appropriate fonts to get the powerline glyphs to show up. I did install the pre-patched fonts, but it still didn't work so I attempted to patch the ones previously installed. It was taking a very long time and I kinda gave up in the middle of patching, so I ctrl-c'ed out of the process. That's probably what caused Source Code Pro to look wrong.

I went and re-installed both Source Code Pro and the pre-patched version for powerline.

 `fc-list -f '%{style[0]}\n' "Source Code Pro"`

Light Italic
Medium
Italic
Medium Italic
Semibold Italic
ExtraLight
Bold Italic
Bold
Semibold
Black
Regular
Light
ExtraLight Italic

`fc-list -f '%{style}\n' "Source Code Pro for Powerline"`

Medium,Regular
Regular
Black,Regular
Light,Regular
Bold
Medium,Regular
ExtraLight,Regular
Black,Regular
Light,Regular
Semibold,Regular
Semibold,Regular
Bold
ExtraLight,Regular
Regular


Source Code Pro for Powerline still looks about the same, probably because it's a patched font. That  would also explain why the regular Source Code Pro fonts looked wrong, since it was an interrupted patch.

I'll probably need to re-install some other fonts later that got interrupted in the middle of a patch, since they look quite a bit mangled in Konsole.

**Comment by DerVerruckteFuchs** [comment]
So I've tried out different fonts, and ctrl-shift-R doesn't seem to be changing the font based on what I've put into the config. I did make sure I was in insert mode. I've only been able to change the fonts once from default, to regular weight Source Code Pro, and now I'm stuck  back at default. To add, I've reinstalled my fonts and am on Fedora using i3, if that helps. Is there a command I can use to make sure I'm resetting my fonts properly?

**Comment by thestinger** [comment]
You only need `ctrl-shift-r` to reload the configuration without opening a new terminal. Not really sure what you mean.

**Comment by DerVerruckteFuchs** [comment]
I'm not seeing any live changes when I use ctrl-shift-r. My config is saved to `~/.config/termite/config`. I'm honestly not sure why it's not working on my end. I've made sure to choose monospaced fonts, but Termite still stays on the default font.

**Comment by thestinger** [comment]
But closing and re-opening the terminal does load the new configuration, right? I'm not sure if you're reporting an issue with dynamic configuration reloading not working or something else.

**Comment by DerVerruckteFuchs** [comment]
Closing and re-opening doesn't seem to load the configuration. Rebooting might have done it though. I'm going to try an obviously different font to check.

**Comment by DerVerruckteFuchs** [comment]
Switched to Anonymous Pro, rebooted, and still default.
My config assuming that will reveal anything:


[options]

allow_bold = true
browser = firefox
clickable_url = true

[colors]
color0: #3f3f3f
color1: #cc9393
color2: #7f9f7f
color3: #d0bf8f
color4: #6ca0a3
color5: #dc8cc3
color6: #93e0e3
color7: #dcdccc
color8: #000000
color9: #dca3a3
color10: #bfebbf
color11: #f0dfaf
color12: #8cd0d3
color13: #dc8cc3
color14: #93e0e3
color15: #ffffff

[hint]
font = Anonymomous Pro 10

I'm going to turn off the `allow_bold` option to see if that does anything.

**Comment by DerVerruckteFuchs** [comment]
Getting rid of `allow_bold` didn't do anything. Now I comment out the colors and Termite went back to the default black & white color scheme, so ctrl-shift-r does actually work. But the fonts are still not changing for some reason.

**Comment by Earnestly** [comment]
Erm, `[hint]` fonts?  You do realise that it defines the font for hints, as in, `C-S-x` and not the font for the terminal itself?

**Comment by DerVerruckteFuchs** [comment]
I realized that after looking around and comparing my config file to some others online. I did move the font line and reloaded, same issue with the font still not changing to the one I set.

My current config:

[options]

browser = firefox
clickable_url = true
font = Source Code Pro, Medium 10

[colors]
color0: #3f3f3f
color1: #cc9393
color2: #7f9f7f
color3: #d0bf8f
color4: #6ca0a3
color5: #dc8cc3
color6: #93e0e3
color7: #dcdccc
color8: #000000
color9: #dca3a3
color10: #bfebbf
color11: #f0dfaf
color12: #8cd0d3
color13: #dc8cc3
color14: #93e0e3
color15: #ffffff

[hints]


Also I installed Termite from a copr repository:
https://copr.fedoraproject.org/coprs/abrouwers/abrouwers_packages/builds/

Just in case it helps to have the same pre-compiled binary to compare with to see if it's the package itself that may be the issue.

**Comment by DerVerruckteFuchs** [comment]
I think I'm closer to figuring out what's going on. I'm checking out my KDE and QT font settings, and the Oxygen fonts selected by default seem to match what is showing up in Termite, specifically Oxygen-Sans in the Sans-Book style with a point size of 10. The KDE and/or QT font settings may be affecting Termite's font settings, some other folks have had issues where they needed to delete their `~/.kde` folder. I've also had previous issues where I needed to delete my `~/.cache` folder to get things to boot up properly. Continuously deleting folders seems a bit extreme, so I'm going to look for a solution that is a bit more conservative.

**Comment by DerVerruckteFuchs** [comment]
So I've looked at the packages themselves and the copr repo is using vte3 and vte-ng is nowhere to be seen. From what I can tell that shouldn't be an issue though, since it's only for browser and text selection stuff.

I'm still at a loss as to what to do. In the meantime I recompiled urxvt to have the 256color and unicode3 options so I can load the fonts I want, so that works for me for now until I manage to get Termite sorted out.

**Comment by thestinger** [comment]
I'm just going to assume there's something wrong with your system. If there's an issue that occurs in Termite but not GNOME Terminal, then report a bug. Otherwise, it's just some problem on your end.

**Comment by DerVerruckteFuchs** [comment]
So while I was testing config changes with `~/.Xresources` and `~/.config/termite/config`, after a reboot the font changed to what was set. I tried it out a again by setting it to a different font and it went back to that thin default font. I was also playing around with my `~/.bashrc` and `~/.zshrc` between reboots. I also have a modified `~/.bash_profile` that I haven't touched.

I think I have a weird set of configs confusing things somewhere. I'll have to test with a fresh install to be certain. It works sort-of, just not quite as it could in my setup.

**Comment by DerVerruckteFuchs** [comment]
Even though this has been closed for months now, I've sorted out the issue. It turns out the color section requires a specific syntax. The old way I had the color section written would allow the colors to show up, but it was impossible to load fonts. Another interesting wrinkle is that the browser setting would not seem to load, or it was getting ignored entirely as the `clickable_url` option would cause an error as if the option was not set and disable clickable URLs when opening termite. Based on these two quirks, I think an improperly configured `[colors]` section causes the `[options]` section to either not get loaded or ignored by termite.

```[options]
audible_bell = false
mouse_autohide = false
allow_bold = false
dynamic_title = true
clickable_url = true
scrollback_lines = 1000
search_wrap = true
cursor_blink = system
browser = firefox

font = Office Code Pro Medium 10

[colors]
color0: #3a3a3a
color1: #cc9393
color2: #7f9f7f
color3: #d0bf8f
color4: #6ca0a3
color5: #dc8cc3
color6: #93e0e3
color7: #dcdccc
color8: #7f9f7f
color9: #d78787
color10: #bfebbf
color11: #f0dfaf
color12: #8cd0d3
color13: #dc8cc3
color14: #93e0e3
color15: #ffffff

[hints]
```

I was playing around with configs on the terminal.sexy site and found that I could export to a termite config after importing an `~/.Xresources` config. The color section in the export had a different syntax and allowed the font and browser to be set like you are supposed to.

```[options]
font = Office Code Pro Medium 10
audible_bell = false
mouse_autohide = false
allow_bold = false
dynamic_title = true
clickable_url = true
scrollback_lines = 1000
search_wrap = true
cursor_blink = system
browser = firefox


[colors]

# special
foreground      = #dcdccc
foreground_bold = #dcdccc
cursor          = #dcdccc
background      = #3a3a3a

# black
color0  = #3a3a3a
color8  = #7f9f7f

# red
color1  = #cc9393
color9  = #d78787

# green
color2  = #7f9f7f
color10 = #bfebbf

# yellow
color3  = #d0bf8f
color11 = #f0dfaf

# blue
color4  = #6ca0a3
color12 = #8cd0d3

# magenta
color5  = #dc8cc3
color13 = #dc8cc3

# cyan
color6  = #93e0e3
color14 = #93e0e3

# white
color7  = #dcdccc
color16 = #ffffff
```
                  
I'm not sure why color syntax is so touchy. If the color syntax is supposed to be this specific, then it would be helpful to include that in the documentation and man pages as it does not seem to be there. If the syntax is not supposed to be this specific, it may be a bug.

**Comment by steelcowboy** [comment]
I've been playing around with this myself and am having similar issues with color and font.
