### ISSUE TITLE
Support to center the text?

### ISSUE THREAD

**Issue by ghost** [thestinger/termite#256]
It'd be pretty neat if we could make the text in the window centered instead of having overflow on the right and lower sides.

**Comment by Narrat** [comment]
This sounds like the issue https://github.com/thestinger/termite/issues/174

**Comment by thestinger** [comment]
There are *always* going to be gaps when size hints are disabled (or just not respected by the window manager). It's not a bug. The gaps are just not supposed to be there when size hints are in use.

**Comment by thestinger** [comment]
I don't really understand what's being requested here.
