### ISSUE TITLE
termite cant exec curses programs using -e

### ISSUE THREAD

**Issue by kevinclevenger** [thestinger/termite#259]
When starting a new termite instance with '-e <curses program>' it fails to launch

fails:
  termite -e ncmpcpp
  termite -e weechat

works fine (not linked to curses):
  termite -e vim
  termite -e mc

$ ldd /usr/bin/weechat | grep curses
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007fc4fe5fe000

Current termite git and vte-ng

**Comment by thestinger** [comment]
That doesn't sound like a Termite bug. Not enough information to go from regardless of whether it is.

**Comment by kevinclevenger** [comment]
All of gnome-terminal, xterm, and urxvt spawn a new terminal with a curses application on the same system with no issues. If not termite, then is this a vte-ng issue? 

I'm happy to provide any additional information you need.

**Comment by thestinger** [comment]
> If not termite, then is this a vte-ng issue?

Running weechat with `termite -e weechat` works fine for me so I don't think it's a problem with either. If you have vte-ng installed, then it's also going to be what gnome-terminal is using too.

> I'm happy to provide any additional information you need.

Error logs or something like that. I can't reproduce the problem (`termite -e weechat` works fine) so it's something on your end. You could try using the default Termite configuration but I don't think the problem is being caused by Termite at all.

**Comment by thestinger** [comment]
`termite -e htop` and `termite -e ncmpcpp` also work fine here.

**Comment by kevinclevenger** [comment]
I compiled vte-ng and termite from current git on LMDE2, Fedora 23 Beta, and Arch and they all exhibit exactly the same failure behavior WRT curses applications. 

The only thing that did work was vte-ng 0.40.2 community and termite installed from AUR on Arch, I'll keep looking into it.

**Comment by thestinger** [comment]
Does this still happen with vte-ng 0.42.1?

**Comment by kevinclevenger** [comment]
Yes, it does.

**Comment by auscompgeek** [comment]
vim and mc do link with ncurses though, so whatever it is, it's definitely not what's been speculated here.

**Comment by kevinclevenger** [comment]
No, vim and mc don't link to ncurses

$ ldd /usr/bin/mc
        linux-vdso.so.1 (0x00007ffd7b5d8000)
        libslang.so.2 => /lib/x86_64-linux-gnu/libslang.so.2 (0x00007f8402e67000)
        libgpm.so.2 => /usr/lib/x86_64-linux-gnu/libgpm.so.2 (0x00007f8402c61000)
        libext2fs.so.2 => /lib/x86_64-linux-gnu/libext2fs.so.2 (0x00007f8402a1b000)
        libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f84027f2000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f84025ee000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f84022df000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f84020c2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8401d19000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8401b15000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8401814000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f8401610000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f84013f5000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f8401113000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8400ea5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8403520000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f8400c93000)

$ ldd /usr/bin/vim
        linux-vdso.so.1 (0x00007ffd77735000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa6af152000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fa6aef28000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fa6aed03000)
        libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007fa6aeafa000)
        libgpm.so.2 => /usr/lib/x86_64-linux-gnu/libgpm.so.2 (0x00007fa6ae8f4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa6ae6f0000)
        liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007fa6ae4bd000)
        libperl.so.5.20 => /usr/lib/x86_64-linux-gnu/libperl.so.5.20 (0x00007fa6ae0ff000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa6adee2000)
        libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fa6ad95d000)
        libtcl8.6.so => /usr/lib/x86_64-linux-gnu/libtcl8.6.so (0x00007fa6ad5a6000)
        libruby-2.1.so.2.1 => /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1 (0x00007fa6ad12a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6acd81000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa6acb13000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa6af8c7000)
        libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007fa6ac90e000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fa6ac6d7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa6ac4bc000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa6ac2b9000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fa6ac036000)

**Comment by auscompgeek** [comment]
Dunno what kind of vim and mc binaries you could possibly have then. Mine most certainly do.

```console
% ldd =vim
	linux-vdso.so.1 (0x00007ffdaf676000)
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007f656ffdb000)
	libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x00007f656fd25000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f656faff000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f656f8b4000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f656f662000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f656f354000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0x00007f656f14c000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0x00007f656ef2f000)
	libXt.so.6 => /usr/lib/libXt.so.6 (0x00007f656ecc6000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f656e984000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f656e686000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f656e419000)
	libacl.so.1 => /usr/lib/libacl.so.1 (0x00007f656e210000)
	libgpm.so.2 => /usr/lib/libgpm.so.2 (0x00007f656e009000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f656de05000)
	liblua.so.5.3 => /usr/lib/liblua.so.5.3 (0x00007f656dbcc000)
	libperl.so => /usr/lib/perl5/core_perl/CORE/libperl.so (0x00007f656d7ea000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f656d5cd000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f656d229000)
	libpython3.5m.so.1.0 => /usr/lib/libpython3.5m.so.1.0 (0x00007f656cd5c000)
	libruby.so.2.2 => /usr/lib/libruby.so.2.2 (0x00007f656c8e1000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f656c6dd000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f656c4d0000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f656c2ca000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f656c0a4000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f656bd75000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f656b9f6000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f656b7e0000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f656b59c000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f656b392000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f656b18f000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f656af7f000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f656ad74000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f656ab69000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f656a966000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f656a763000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f656a551000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f656a31c000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007f656a11a000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f6569f11000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f6569d08000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f6569a98000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f6569893000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f6569670000)
	libattr.so.1 => /usr/lib/libattr.so.1 (0x00007f656946b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f657061d000)
	libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007f6569233000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f6569030000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f6568d9d000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f6568b3b000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f6568874000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f65685c9000)
	libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007f65683a1000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f656819d000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f6567f93000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f6567d7d000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f6567ae5000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f65678dd000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f65676c6000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f656749c000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f6567294000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f6567090000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f6566e8a000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f6566c5f000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f6566a4f000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f656684d000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f6566648000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007f6566440000)
	libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0x00007f656623c000)
	libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007f656602e000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f6565e20000)
	libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007f6565c0e000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f65659ff000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f65657d1000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f65655b7000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f65653b4000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f65651b1000)
	libxcb-randr.so.0 => /usr/lib/libxcb-randr.so.0 (0x00007f6564fa3000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f6564d9c000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f6564b99000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f6564993000)
% ldd =mc
	linux-vdso.so.1 (0x00007ffe6b599000)
	libslang.so.2 => /usr/lib/libslang.so.2 (0x00007f4e3c312000)
	libgpm.so.2 => /usr/lib/libgpm.so.2 (0x00007f4e3c10b000)
	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f4e3bedf000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f4e3bcdb000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f4e3b9cd000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f4e3b785000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f4e3b568000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f4e3b1c4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f4e3afc0000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f4e3acc2000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f4e3aa55000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f4e3a7db000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f4e3a364000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f4e3a14e000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f4e39ede000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f4e39c9c000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f4e39a97000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f4e3988f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4e3c681000)
```

**Comment by rafaelndev** [comment]
termite -e ncmpcpp, htop, ranger, ncdu, calcurse, wavemon, nmtui (all ncurses i think) works normally for me.

**Comment by kevinclevenger** [comment]
I'm on LMDE 2 so that may account for the difference in which libs are linked

**Comment by thestinger** [comment]
@kevinclevenger Try the vte-2.91 utility shipped with the VTE used by Termite.

**Comment by thestinger** [comment]
Works for me. Not going to keep a bug open that I can't reproduce. It must be a problem on your system.
