### ISSUE TITLE
Question: support for tabs

### ISSUE THREAD

**Issue by suedi** [thestinger/termite#261]
Any plans on adding tabs to termite?

**Comment by thestinger** [comment]
Not really. I'm not really against doing it, but I would expect it to offer something not provided by window manager tabbing if I was going to merge it. It's not a feature I need myself, so I'm likely not going to implement it.

**Comment by suedi** [comment]
Thanks for the answer 

Guess I am just used to work with tabs and misses them.

closing issue.....

**Comment by pandada8** [comment]
the wm tabbed terminal got overlapping background when using a
semi-transparent background. This is something tabbing can provide.

suedi <notifications@github.com>于2015年10月9日周五 21:11写道：
