### ISSUE TITLE
Fallback Fonts

### ISSUE THREAD

**Issue by SageEx** [thestinger/termite#262]
Is there any support for fallback fonts if the current font does not support a given glyph ?
In URxvt, I could set up multiple fonts in order of preferences 
This is useful while using powerline in vim. For example, I could use a normal font & a powerline font in fallback - so no need to repatch any fonts. 
Also it helps adding glyphs in config files from fonts like fontawesome.
Basically, no need to repatch a font.
Is there any option to do that, and if not any plans to add this functionality ?

**Comment by thestinger** [comment]
FreeType / Fontconfig already provide full fallback support and the preferred order is configurable.. It's not something Termite has to deal with.
