### ISSUE TITLE
How i can create new tab?

### ISSUE THREAD

**Issue by DeadNumbers** [thestinger/termite#267]
subj

**Comment by thestinger** [comment]
There isn't support for tabs right now. It's currently expected that it will be used with a window manager like i3 with support for tabbed and/or stacked containers at a window manager level. It might make sense to add tabbing support, but it's not something I would use myself unless it offered advantages over window manager tabbing so it's unlikely that I'd actually implement it.

**Comment by polyzen** [comment]
Another option is to use tmux inside termite. Tmux windows are equivalent to tabs, and tmux panes to tiles

**Comment by DeadNumbers** [comment]
Tmux is that russian programmers called "crutch". Termite very nice emulator, but really is not enough tabs or (analog) terminator's frames. I will wait and monitor the development of the project.

**Comment by polyzen** [comment]
In soviet russia, terminal tab you.

**Comment by DeadNumbers** [comment]
It's was long long time ago ;)

**Comment by nishantvarma** [comment]
Can I use tabbed with termite?

**Comment by polyzen** [comment]
I've never used tabbed, but I don't see why not.

**Comment by KarthikNayak** [comment]
@thestinger It would be nice to have tabs, even with windowing managers. For my personal use case, I prefer having termite and emacs next to each other on a window, with tabs it allows for multiple terminals without the loss of screen space.

**Comment by wsdjeg** [comment]
no need, you can use i3wm, it will be easy for you to manager windows.

**Comment by CrashyBang** [comment]
Out of curiosity has anybody got termite working with [tabbed](http://tools.suckless.org/tabbed/)?

**Comment by pjhalsli** [comment]
even though this issue have been closed for some time now I have to say this:

seriously if tabs are so freakin important use tmux or another terminal. Termite is "almost" perfect as it is

**Comment by binex-dsk** [comment]
cant use `tabbed` with this on wayland
