### ISSUE TITLE
Any way to clear history?

### ISSUE THREAD

**Issue by SRGOM** [thestinger/termite#269]
Is there a shortcut key/any other way to clear history? 

Why?
There are times when you search for a particular string that was there multiple times in the history and you want to make sure it doesn't occur anymore. 
Basically, it helps in going back through history..

**Comment by thestinger** [comment]
You can use `reset` but it's not bound to a key right now.

**Comment by SRGOM** [comment]
Thanks

**Comment by mrbaloghakos** [comment]
I found a way to delete the history:

- Close Termite
- Navigate to `C:\Users\USER\AppData\Roaming\Termite\Termite.ini`
- Open the file, delete the entries under `[History]`, then save.
- Open Termite and your input history should be empty.

**Comment by thestinger** [comment]
This wasn't ever a Windows application...
