### ISSUE TITLE
No output when invoking short-running commands via --hold -e foo

### ISSUE THREAD

**Issue by eigengrau** [thestinger/termite#271]
I’ve noticed that `termite --hold -e "echo foo"` produces no output (on 22c1191). On the other hand, when invoking a long-running command like `locate \*`, the output will be shown. Could this be some sort of timing-issue? `--hold -e 'zsh -c ls'` yields an empty termite window for me, while `--hold -e 'zsh -c "sleep 0.1; ls"'` correctly shows the ls output.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
