### ISSUE TITLE
URLs with ending brace end with an error

### ISSUE THREAD

**Issue by ndalliard** [thestinger/termite#272]
When I've an URL especially in emails (I use mutt), which end with a ending brace like this:

`(http://google.com/)`

then the first brace is ignored, but the end brace is added to the url which ends in an error.

Has anyone an easy fix for that?

**Comment by EliteTK** [comment]
Technically, that's a valid character to have in a URI.

**Comment by thestinger** [comment]
https://github.com/thestinger/termite/issues/155
