### ISSUE TITLE
Update config in real time (without starting a new termite instance)

### ISSUE THREAD

**Issue by toogy** [thestinger/termite#273]
Would it be possible for termite to react to changes in the `~/.config/termite/` folder and update itself in real-time?

I think nothing is impossible!

**Comment by terlar** [comment]
You can use `killall -USR1 termite` to reload the config in all your termite sessions. You don't need to start a new instance. You could use `inotifywait` or any similar tools too achieve this.

**Comment by thestinger** [comment]
It could definitely watch the configuration file and reload automatically.

**Comment by thestinger** [comment]
Not entirely sure if it's a good idea though. And doing it properly is complicated. You need to watch the whole path leading to the configuration file. And it's worse if it needs to watch all of the possible paths.

**Comment by polyzen** [comment]
I wonder if it would be feasible to change colorschemes on-the-fly If #130 is implemented as well.

**Comment by terlar** [comment]
Not sure if you are interested in work-arounds, but currently I do something similar, I have two different commands that switches out a symlink to the termite config (two different color schemes) and then sends the USR1 signal to all termite sessions. It works pretty well.

- https://github.com/terlar/dotfiles/blob/master/local/bin/brighside
- https://github.com/terlar/dotfiles/blob/master/local/bin/darkside

**Comment by polyzen** [comment]
@terlar, interesting. I've been using keybindings to call termite with different configs, then reattaching dtach/tmux

**Comment by kousu** [comment]
:+1: for inotifywait + pkill -USR1.
This doesn't belong in termite. It's not Unix custom to reload configs automatically.

**Comment by thestinger** [comment]
agreed, I don't really want to do this

**Comment by ducklin5** [comment]
Is the point of Unix the fact that you can do anything.. just saying

**Comment by ducklin5** [comment]
I dont change colorschemes often, but in the rare case when im working on a new one I like to be able to see the colors. So I just use this now untill Im done messing around with the config:
```while true; do killall -USR1 termite  ; sleep 5; done```

**Comment by tgy** [comment]
@ducklin5 isn't it faster to do

1. `:w` in the Vim instance where you modify the colorscheme
2. switch to the termite instance where you test your colorscheme
3. press ctrl+shift+r

I think this takes less than a second and it has the advantage to only load the termite config for the terminal where you are testing the colorscheme. With your solution, I imagine the termite instance where I'm modifying the colorscheme having its config reloaded; and if you broke something in the colors, having your colorscheme in Vim broken too and not being able to comfortably modify the code.

(this of course assumes you are using a CLI text editor)

**Comment by teto** [comment]
found https://github.com/NearHuscarl/termite-color-switcher that worked great.
