### ISSUE TITLE
overwrite property of current term

### ISSUE THREAD

**Issue by scampi** [thestinger/termite#277]
Is it possible to overwrite a property for the current term, for example the background color ?

**Comment by thestinger** [comment]
Yes, you can reload the configuration file.

**Comment by scampi** [comment]
But this means I need to change the configuration file. I was looking for a more "temporary" approach. Something that sets the property just for the current term, without messing the configuration file.

**Comment by thestinger** [comment]
In theory, each terminal could open a socket and listen for configuration changes over it... but it's not something that I'm going to implement. It would be far too complicated. It's a small project and half the code would end up dealing with IPC to support a niche feature that I'd never use.

**Comment by scampi** [comment]
Ok I understand. Thanks for the feedback @thestinger!

Just to give some context to the issue, and maybe you can then point me to the right direction ;o)
The reason for this question was that some commands output to stdout some colored text. However, the color of the text doesn't work with the background color I was using, and so I couldn't see that text.
Did you have such a problem ?
