### ISSUE TITLE
Feature request: Add daemon mode

### ISSUE THREAD

**Issue by Chrysostomus** [thestinger/termite#282]
Would it be feasible to add daemon mode similar urxvt, gnome-terminal and xfce4-terminal? Feature wise termite is the most desireable terminal for tiling enviroment, but running multiple instances of it quickly increases ram usage beyond even that of gnome-terminal. Server-client model used by urxvt could get around this problem.

**Comment by thestinger** [comment]
I'm not interested in adding this kind of complexity. I don't like the idea of tying together all of the terminals. Terminal emulators and complex and therefore not entirely stable... one big process increases the chance of a crash / corruption and will bring them all down. VTE is far from robust, and the same thing applies to other terminal emulators written in C. I doubt any of them is even ASan/UBSan clean...

**Comment by Chrysostomus** [comment]
Okay, thanks for respose! This is good to know.

**Comment by natostanco** [comment]
tried gnome-terminal/terminix both based on vte, multiple terminals share the same process/threads, with termite each terminal has its own process, 500mb just for just 10 terminals.

**Comment by thestinger** [comment]
There's not going to be a daemon mode. Bogus memory measurements won't convince me of that.
