### ISSUE TITLE
Foreground colour of cursor

### ISSUE THREAD

**Issue by ichbean** [thestinger/termite#284]
There is an [identical issue](https://github.com/thestinger/termite/issues/34) closed due to upstream. Now foreground colour setting seems to be [supported by VTE](https://mail.gnome.org/archives/commits-list/2015-November/msg05845.html), it'd be awesome to get it in Termite.

**Comment by jelly** [comment]
I can't find any support for it in the current vte3 package (0.42.1) and the tarball of 0.43 does not seem to include it either.. so I guess it's only in vte3's git repo.
