### ISSUE TITLE
n/N do not move the cursor?

### ISSUE THREAD

**Issue by zhou13** [thestinger/termite#287]
I found that when doing search in the selection mode, n/N does not move the cursor (while the cursor moves in vim).  Is this intended?

**Comment by thestinger** [comment]
It isn't something I thought about. Feel free to submit a patch.

**Comment by niko** [comment]
Would love that, too. Typical workflow: Search, then copy.

Not fluent enough in C++ to implement patch myself, though. :(

Other that that: Great work! Thanks a lot!

**Comment by ixjlyons** [comment]
@thestinger: This isn't possible without touching vte, correct? I implemented `vte_terminal_get_selection_position()` and was then able to move the cursor along to match the first column of the search selection with pretty minimal changes to termite itself. I'm not sure if there's a better way to do it though (i.e. one that doesn't involve further changes to vte).

**Comment by ixjlyons** [comment]
Here are the changes I mentioned:

* [vte](https://github.com/ixjlyons/vte-ng/commit/c92084c13fbfe343cf8c97222f78681609e7a694)
* [termite](https://github.com/ixjlyons/termite/commit/2697cf8d8c0594921478c8bb449ba3678616d5d9)

**Comment by taralbass** [comment]
I just started using termite. I really love it, but this is the one feature I would really like to see. @thestinger , any chance of getting feedback on @ixjlyons changes (and hopefully merging them)?

**Comment by jelly** [comment]
@taralbass Well that would mean patching vte3 again, which is troublesome.

**Comment by max-b** [comment]
@jelly it looks like they've closed your request as WONTFIX in vte https://bugzilla.gnome.org/show_bug.cgi?id=679658#c17. Are you still holding out hope they'll change their minds? 

Is it troublesome because you're just rebasing your set of commits on top of each version of vte? Would you have to revisit each branched version of vte and add another commit? Does that break anything?

**Comment by Warepire** [comment]
I rebased @ixjlyons patch on vte3 0.56.2 as vte3 changed internally, breaking the patch.

Rebased patch: https://gist.github.com/Warepire/5877fe8fbdbfcc78921878bcff199c61

**Comment by wizeman** [comment]
I improved the [patch from @ixjlyons](https://github.com/thestinger/termite/issues/287#issuecomment-207836220) to also move the cursor when you first do the search (or reverse search), not just when you press n/N to search again.

The patch is available here: https://gist.github.com/wizeman/bb2a9caccbfa167ba2cde38ad66ac8a7

**Comment by hannasm** [comment]
This really seems like a must have feature. Thank you very much for the patches.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
