### ISSUE TITLE
Mode Overlay

### ISSUE THREAD

**Issue by DaveDavenport** [thestinger/termite#288]
I made a small patch on my branch that shows an overlay indicating what mode is active:

![overlay](http://images.sarine.nl/termite-overlay2.png)

It can be disabled in config and toggled live using 'ctrl-o'.

Is there interrest? if so I will make a PR.

**Comment by kapsh** [comment]
That's great! I am interested. It is hard to spot in which mode termite working (e.g. you didn't enter visual mode for some reason or accidentaly or vice versa - accidentaly enter this mode). 

I open this project page to post issue with this idea. :)

**Comment by DaveDavenport** [comment]
It is on my branch https://github.com/DaveDavenport/termite/.
Including a indicating about yanking and opening selection.

**Comment by kapsh** [comment]
Thanks, I installed your version and it looks good. 
And one thing: it would be handy if url hints mode will have separate mark (now it shows "command" as in wainting command mode).

**Comment by DaveDavenport** [comment]
good idea, please make a issue on my repo.

**Comment by kapsh** [comment]
Sorry, but it seems that forked repos doesn't allow using of this feature - there are no "Issues" link in your repo.

**Comment by DaveDavenport** [comment]
aah, annoying.

**Comment by kapsh** [comment]
Create Pr anyway, this is a good feature.

**Comment by DaveDavenport** [comment]
Lets first try to get my keybinding thing in.

**Comment by hurricanehrndz** [comment]
Yes the overlay is. I would really like as well.

**Comment by DaveDavenport** [comment]
I added a small yank overlay popup too and a open link popup. will see to make a small gif later.

**Comment by thestinger** [comment]
I think it would make more sense to change the color or shape of the cursor based on the mode. 
it isn't possible with the current version of VTE yet but it did land in master: https://mail.gnome.org/archives/commits-list/2015-November/msg05845.html. I want to hold off until it can be done that way.

**Comment by thestinger** [comment]
See https://github.com/thestinger/termite/issues/241.
