### ISSUE TITLE
Numeric keyboard's dot emits comma in Termite

### ISSUE THREAD

**Issue by ineu** [thestinger/termite#289]
In 
```
> $ termite --version
termite v10
```
installed from the Archlinux repos there's an issue with dot button on the numeric keyboard: when I press it, termite draws comma instead of dot. This button is displayed in xev as `KP_DECIMAL` and is handled correctly by any other application I've tried.
I see this issue on two different machines: laptop and desktop, different manufacturers, but same distribution: latest Archlinux.
Please let me know if I can provide more debug info.

**Comment by thestinger** [comment]
Can you try the termite-git AUR package to see if the issue is still present in master?

**Comment by ineu** [comment]
Done. Looks like the issue is still there.
```
> $ termite --version                                                                                                                                                                         
termite v10-30-g850a77d
```

**Comment by jelly** [comment]
I actually can't reproduce this with my keyboard's numlock which is a dot.

**Comment by thestinger** [comment]
This works fine for here. Does it happen for you in VTE's vte-2.91 test application?

**Comment by ineu** [comment]
@thestinger Sorry, don't understand. What is a vte-2.91 test application?

**Comment by thestinger** [comment]
The vte-2.91 program shipped with VTE.

**Comment by ineu** [comment]
Yes, it's also happening in vte-2.91. Though xev reports it as 
```
KeyPress event, serial 32, synthetic NO, window 0x2a00001,
    root 0xd6, subw 0x0, time 22702224, (12,526), root:(976,577),
    state 0x10, keycode 91 (keysym 0xffae, KP_Decimal), same_screen YES,
    XKeysymToKeycode returns keycode: 129
    XLookupString gives 1 bytes: (2e) "."
    XmbLookupString gives 1 bytes: (2e) "."
    XFilterEvent returns: False
```

I'm using ArchLinux with
```
community/termite 10-2
    A simple VTE-based terminal
extra/vte-common 0.42.4-1
    Common files used by vte and vte3
community/vte3-ng 0.42.1.a-1
    Enhanced Virtual Terminal Emulator widget for use with GTK3
```

**Comment by ineu** [comment]
And it's not vte-ng specific. I've just installed vte and it has the same issue.

**Comment by thestinger** [comment]
You should report it upstream (just based on either vte-2.91 or gnome-terminal): https://bugzilla.gnome.org/page.cgi?id=browse.html&product=vte.
