### ISSUE TITLE
Ctrl+Shift+Space doesn't work when CapsLock is used as a Control

### ISSUE THREAD

**Issue by ineu** [thestinger/termite#290]
I am using CapsLock key as an additional control key:
```
setxkbmap -option ctrl:nocaps
```
Unfortunately it doesn't seem to work in Termite. I'm trying to enter selection mode. When I press CapsLock+Shift+Space, nothing happens. When I press Ctrl+Shift+Space, it works.
From xev my rebound CapsLock is recognized as
```
    state 0x10, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
```
and left Control is recognized as
```
    state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
```
That is: same keysym, but different keycodes.

**Comment by terlar** [comment]
I am also using Caps-Lock key as an additional control key through `setxkbmap` with `ctrl:nocaps`. And Caps-Lock+Shift+Space works for me. 

Caps-Lock:
```
state 0x0, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
state 0x4, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
```

Left Control Press/Release:
```
state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
```

So essentially the same as you except the states, however keycodes are different and still works, so that is not the problem.

**Comment by ineu** [comment]
@terlar Thanks for sharing. I've just tried it on desktop with external keyboard: CapsLock+Shift+Space seems to work here, but CapsLock+Shift+x does not. Will check on my laptop later today.

**Comment by ineu** [comment]
So, checking it on my laptop:
CapsLock+Shift+x: works
CapsLock+Shift+r: works
CapsLock+Shift+c/v: works
CapsLock+Shift+u: works
CapsLock+Tab: works
CapsLock+Shift+Space: does not work
CapsLock+Shift+t: works
CapsLock+Shift+up/down: works
Shift+PageUp/PageDown: works, though it doesn't involve CapsLock.

**Comment by ineu** [comment]
It is even more weird: CapsLock+Right Shift+Space: works

**Comment by ineu** [comment]
It doesn't look like execution hits this branch in case of CapsLock+Shift: https://github.com/thestinger/termite/blob/master/termite.cc#L916. Can it be a GTK issue?

**Comment by thestinger** [comment]
It looks like a GTK bug, but it could be a problem at another layer of the stack. It doesn't seem like Termite is doing anything wrong though.

**Comment by ineu** [comment]
Now I've tested it with a new user in i3 and xfce: still the same behavior, so it's not related to my settings. Maybe this issue is specific to archlinux.
Anyway, it's not too important, I think the issue can be closed.

**Comment by thestinger** [comment]
Feel free to submit a workaround, but I don't want this to be a GTK3 bug tracker.

**Comment by spijet** [comment]
Found this after I filed #358, so I'll repost it here and close #358.

I'm running Gentoo amd64, and using latest live-versions of Termite and VTE-ng. Hitting Caps+Shift+X (which maps to L_Ctrl+Shift+X in my case) does nothing, while R_Ctrl+Shift+X works well. L_Ctrl+Shift+X doesn't work too, since L_Ctrl acts as CapsLock when swap is used.

I swap L_Ctrl and CapsLock using this config for Xorg:
```
Section "InputClass"
        Identifier "keyboard"
        MatchIsKeyboard "on"
        Option "xkb_layout" "us,ru"  
        Option "xkb_options" "grp:alt_shift_toggle,grp:switch,ctrl:swapcaps"  
EndSection
```
I also use Termite with VTE-ng on ArchLinux on my other PC, will post here once I check if the behaviour is the same there.

**Comment by aleprovencio** [comment]
Hello guys, any updates on this?

I also have `ctrl:nocaps`, and the only way I can get to URL hints mode is using `Caps+Shift+Space` and then hitting `x`, because I can't directly use `Caps+Shift+x`. It works when doing `L/R_Ctrl+Shift+x`

**Comment by duckdalbe** [comment]
I see the same behaviour as @aleprovencio and also would love to see any kind of solution. If this is a GTK-bug, could someone point to a bug-report? I didn't find anything.

**Comment by JanKoppe** [comment]
Same issue here. running termite in i3 on Arch linux, using `ctrl:nocaps`. Caps+Shift+x does not work, L_Ctrl+Shift+x and R_Ctrl+Shift+x does.

```
$ cat /etc/X11/xorg.conf.d/00-keyboard.conf
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbVariant" "altgr-intl"
        Option "XkbOptions" "ctrl:nocaps"
EndSection
```

**Comment by ngkz** [comment]
Same issue here, too. I'm running termite in sway on Arch Linux, using `ctrl:nocaps`.
