### ISSUE TITLE
I'd like to have URLs highlighted in a colour other than the foreground colour. Is this possible?

### ISSUE THREAD

**Issue by krompus** [thestinger/termite#291]
I recently switched from urxvt, and this is one of the only things I miss; it was nice having URLs highlighted in a custom colour, and underlined.

I couldn't find anything in the docs. If this is not possible already, then I have a feature request!

(As an aside, thank you so much for this excellent terminal emulator; after one hour, I knew I had found my new workhorse!)

**Comment by kapsh** [comment]
You mean **always** highlight URLs? Can't remember how it is in urxvt.

**Comment by krompus** [comment]
[Here's what I'm referring to](https://ptpb.pw/Ds1R.png): In Urxvt, you can use a Perl extension [(documented in the ArchWiki)](https://wiki.archlinux.org/index.php/Rxvt-unicode#Clickable_URLs) to enable passive URL colouring and underline, similar to syntax highlighting.

Termite is much more intuitive, in my opinion, for actually handling these URLs with keyboard control, but I like that they're highlighted in Urxvt so I can pick them out in a big mess of text -- when I'm in a busy IRC channel, for example. It's mostly aesthetic, but it's also functional

**Comment by thestinger** [comment]
This would need to be implemented in VTE, not Termite. It doesn't simply require exposing a small API for Termite, so it needs to be addressed upstream.
