### ISSUE TITLE
Provide default config

### ISSUE THREAD

**Issue by kapsh** [thestinger/termite#292]
There are no config template in default installation. Can you include it to install target? 
Now new user start with no config and can't figure out how it should look like and which syntax must be used (e.g. I had to copy it from git repo which isn't userfriendly).

**Comment by beanaroo** [comment]
I just installed termite for the first time and there exists a default configuration in `/etc/xdg/termite/config`

**Comment by kapsh** [comment]
@beanaroo Do you have Arch Linux? I think the maintainer of your distro had create this file. But it is missing in Makefile targets.

**Comment by thestinger** [comment]
I would accept a patch adding it to the Makefile's install target. I'm not planning on making any further changes that aren't based on own needs myself though.
