### ISSUE TITLE
Quotes in filenames with spaces -- new feature or a bug?

### ISSUE THREAD

**Issue by barwinko** [thestinger/termite#293]
just compiled master branch and what I see:
![](http://i.imgur.com/WHft6Id.png)
but these filenames with spaces do not have quotes in reality!

Is this new feature or a bug?

termite from master branch, vte-0.42.1 with termite patch. Thanks.

**Comment by thestinger** [comment]
I doubt this is related to Termite. It's not responsible for any of that.

**Comment by polyzen** [comment]
ls now quotes file names unambiguously and appropriate for use in a shell,
  when outputting to a terminal.


http://lists.gnu.org/archive/html/coreutils-announce/2016-01/msg00000.html

**Comment by barwinko** [comment]
@polyzen thanks! this is new default feature of coreutils-8.25, but we can avoid it:
```bash
alias ls='ls --color --quoting-style=literal'
```
