### ISSUE TITLE
License.

### ISSUE THREAD

**Issue by hurricanehrndz** [thestinger/termite#294]
Can you please License your code. MIT or GPL2 would be good.

**Comment by thestinger** [comment]
It's LGPL 2 or later to make it possible to move code from here into VTE. I added a license header to termite.cc quite some time ago but forgot to add the corresponding COPYING file to the repository in that commit. I'll get around to it at some point.

**Comment by varac** [comment]
> but forgot to add the corresponding COPYING file to the repository in that commit. I'll get around to it at some point.

Please add a LICENCE file so it's obvious which licence this while project uses, so it makes adoption into OS packaging easier.

**Comment by thestinger** [comment]
It's already marked as being LGPL 2 or later as it was when this issue was opened. If you want there to be a LICENSE file with a copy of the license, submit a pull request with it. I don't care enough to do it.
