### ISSUE TITLE
Scrollback save to file

### ISSUE THREAD

**Issue by msvalina** [thestinger/termite#297]
Is it possible to save scrollback to file?

So I can have one more layer of backup.

**Comment by thestinger** [comment]
No, but IIRC this is something VTE might support doing. If so, it could be implemented. I'm not interested in the feature so someone will need to step up to implement it though. If it's not implemented by VTE, then you would need to ask them.

**Comment by lenormf** [comment]
Could you reconsider? This is a very valuable feature when trying to debug very verbose software, and the lack of it in `termite` is virtually the only thing that makes me use another terminal emulator that implements it (`kitty`).

**Comment by thestinger** [comment]
We'll accept a clean implementation when @jelly finds time to review one, but someone needs to implement it.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
