### ISSUE TITLE
Difficulties using Termite as the default external editor for Pentadactyl (possibly other programs as well).

### ISSUE THREAD

**Issue by krompus** [thestinger/termite#298]
When I was using `urxvt`, I had `set editor='urxvt -e vim'` in my `.pentadactylrc` file.

When I would launch the external editor from a text entry box, it would copy the text from the field, paste it into the editor, and make a swap file, [like so](https://ptpb.pw/13qA.png).

When I use `set editor='termite -e vim'`, an instance of vim inside termite opens up, but there is no text, or associated swap file.

Is there a workaround for this? Thanks!

**Comment by miseran** [comment]
It works for me if I provide a file placeholder: `set editor='termite -e "vim <file>"'`.
No idea why this isn't needed for urxvt.

**Comment by krompus** [comment]
Oh, dude! Awesome! Thanks a bunch!

**Comment by thestinger** [comment]
Termite treats `-e` like any other option. It takes a single mandatory argument, not multiple arguments that it then passes along. It's required for sane command-line parsing.
