### ISSUE TITLE
Problem with printing text and images in ncurses interfaces like ranger and ncmpcpp

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [thestinger/termite#299]
ncurses programs have issues printing text, particularly with non Latin characters, Japanese specifically.
While scrolling in ncmpcpp's playlist view, Japanese gets a bit mangled along with running time in the same line.
![termite-ncmpcpp](https://cloud.githubusercontent.com/assets/12420381/12968696/544d7002-d043-11e5-80ed-3ce20e0f020d.png)

Browsing images and text at the same time in ranger gets a screwed up as well. Note that this is with w3mimgdisplay in ranger. Text previews by themselves seems to not be an issue. Images seem to screw things up for rendering. 

On workspace 3 I'm using ranger in termite, and on workspace 4 I'm using ranger in urxvt for comparison. While using termite there seem to some scanlines in images, and text gets printed strangely in the presence of images.
![screencast](https://cloud.githubusercontent.com/assets/12420381/12968846/a9e6b1f2-d045-11e5-8abf-370ac2e6aecf.gif)

**Comment by DerVerruckteFuchs** [comment]
The banding in the images seem to be an alpha channel issue with the terminal and compton. Like the issue [#438 for ranger](https://github.com/hut/ranger/issues/438). It does not affect urxvt, but affects termite and st for someone else. Disabling compton gets rid of the banding in image previews in termite.

While compton is disabled the text lines overlap the images like in my gif. A big difference is that instead of my desktop background showing up behind my text and images there is a black background instead.

![termite-ranger-2](https://cloud.githubusercontent.com/assets/12420381/12989639/25990b54-d0d4-11e5-9c46-a08d8b1270db.png)

![termite-ranger-3](https://cloud.githubusercontent.com/assets/12420381/12989642/2b3c54bc-d0d4-11e5-951f-f58af11c20d6.png)

**Comment by thestinger** [comment]
Did you set urxvt to use 32-bit depth? That's why this happens in Termite, but 32-bit depth is not going away. It's a bug elsewhere.

**Comment by DerVerruckteFuchs** [comment]
Not as far as I know, I don't have `URxvt*depth: 32` in my `~/.Xresources`. I do have `rxvt-unicode-patched` installed from the AUR, so that may have something to do with it.

**Comment by thestinger** [comment]
Try setting a 32-bit depth there and see if it breaks. Termite supports dynamically enabling transparency so it uses a 32-bit depth by default.

**Comment by DerVerruckteFuchs** [comment]
So `URxvt*depth: 32` does indeed break and causes nasty issues with alpha channel banding in urxvt. Is there a way to set a lower bit depth in termite?

**Comment by thestinger** [comment]
Not right now. I think the root cause of the bug is what should be focused on, but I have no idea what it is. It's not specific to any terminal or even toolkit. It seems to be either a generic X11 bug or an issue with how w3m draws the overlays.

**Comment by DerVerruckteFuchs** [comment]
I figured that the alpha channel bug was probably a separate issue to the ncurses bug, but wasn't certain.

What can be done about the ncurses issue? I can get by with ascii image previews for now, but ncurses getting a bit mangled puts a small wrench into things. Using ascii previews instead of full images seems to get around the issues I have in ranger, like with the weird text overlap and exposed desktop background. I don't see the issues at all with ascii previews. I can't help but think that's a separate issue though. ncmpcpp is still an issue though. Bit of a pain since I love using it.

**Comment by thestinger** [comment]
I don't have issues like that here. Try with the latest vte-ng version (0.42.4) and Termite's master branch.

**Comment by DerVerruckteFuchs** [comment]
I've updated vte-ng and am using the termite-git AUR package. The issue still presents itself. I even rebuilt fontconfig's cache a few times during testing to see if that would fix it.

**Comment by thestinger** [comment]
Try using the vte-2.91 test program shipped with VTE.

**Comment by DerVerruckteFuchs** [comment]
I ran 'vte-2.91 -c ncmpcpp` and the text got messed up in the same way when scrolling.

**Comment by thestinger** [comment]
Make sure it happens with vte3 rather than vte3-ng and then you can report the bug to them. It's not an issue in Termite.

https://bugzilla.gnome.org/page.cgi?id=browse.html&product=vte

**Comment by DerVerruckteFuchs** [comment]
It shows up in vte3 as well as vte3-ng. So it is definitely a vte3 bug.

**Comment by DerVerruckteFuchs** [comment]
Bug report for reference:

https://bugzilla.gnome.org/show_bug.cgi?id=762052
