### ISSUE TITLE
Support FocusLost (for improved vim support)

### ISSUE THREAD

**Issue by teto** [thestinger/termite#306]
In vim, type `:au FocusLost echom "focus lost"`and then focus another WM window. I would like to catch this signal to autosave files on lost focus.

**Comment by thestinger** [comment]
Termite isn't responsible for terminal emulation. If it's simply a matter of modifying the terminfo file, then it can be addressed here. If VTE doesn't support it, then you're asking in the wrong place. I don't need this feature so someone will need to contribute it for it to happen.

**Comment by teto** [comment]
vte seems to support it:
```
$ ag Focus  
src/mev.c
132:	fprintf(stdout, "I - Focus tracking.\r\n");

src/vteseq.cc
745:		/* 1004: Focus tracking. */

src/vte.cc
7696:vte_terminal_focus_in(GtkWidget *widget, GdkEventFocus *event)
7700:	_vte_debug_print(VTE_DEBUG_EVENTS, "Focus in.\n");
7726:vte_terminal_focus_out(GtkWidget *widget, GdkEventFocus *event)
7729:	_vte_debug_print(VTE_DEBUG_EVENTS, "Focus out.\n");
```
For future reference the neovim patch to bring back support for this https://github.com/neovim/neovim/pull/3488 . If I understand correctly, just adding the correct info in terminfo could allow vte to autoamtically take care of it ?

**Comment by thestinger** [comment]
VTE is already taking care of it it's supported. Vim just doesn't know about it. I'll happily merge a pull request adding the required terminfo entries.

**Comment by teto** [comment]
Appears it works out of the box, my vim trigger missed a * : `:au FocusLost * echom "focus lost"`works fine :s
