### ISSUE TITLE
Zsh history search not working

### ISSUE THREAD

**Issue by binaryplease** [thestinger/termite#307]
Hello,

When entering some characters and pressing the up arrowkey in other terminals, the history is searched for commands starting with these characters. This does not work in termite for me, instead ALL past commands are shown without filtering. 

My termite config file is pretty much unchanged. I'm using Zsh on arch linux.

**Comment by thestinger** [comment]
Set up your keybindings properly. It's not a Termite-specific issue or a bug (unless you consider the lack of a proper default setup a Zsh bug). See https://github.com/thestinger/dotfiles/blob/master/.config/zsh/.zshrc for an example.

**Comment by binaryplease** [comment]
I have set up my .zshrc according to the arch linux wiki and added the lines
```
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-beginning-search-forward
```

That works for other terminals. Are there config options specific to termite?

**Comment by thestinger** [comment]
It's nothing specific to Termite, you just need to use terminfo. See the keybindings in the linked file.

**Comment by binaryplease** [comment]
Ok, I got it working. In case anyone else wants to know I added the lines:
```

#substring search
bindkey "$terminfo[kcuu1]" up-line-or-beginning-search
bindkey "$terminfo[kcud1]" down-line-or-beginning-search
```
