### ISSUE TITLE
Allow arguments to programs executed with --exec

### ISSUE THREAD

**Issue by MachFour** [thestinger/termite#308]
I've been having trouble getting terminal applications to open files correctly in Termite (e.g Neovim) when opened from a .desktop file (i.e. one with Terminal=true and Exec=/path/to/program %f or similar). I think it's because Termite doesn't allow arguments to be passed when a program is specified by --exec. 

Would it be possible to add an 'execute with args' option to termite? It could be as simple as an option like '--' or '-x' that treats all following arguments as the argv of the program to execute with Termite. (cf xfce4-terminal's -x option for a very similar idea).

**Comment by thestinger** [comment]
It does allow arguments to be passed. You just need quotes.

**Comment by MachFour** [comment]
That's true, however if termite is used implicitly in a .desktop file with the Terminal=true key (and my preferred terminal is set to Termite) I don't think there's a way of specifying quotes around both the program that is executed as well as its own arguments, when that string is passed to termite -e. It would be much easier if there was a way to execute arbitrary commands without quoting.

Would you accept a pull request with this feature implemented?

**Comment by MachFour** [comment]
I've implemented this in #310, please let me know if this is suitable

**Comment by MachFour** [comment]
Second try in #311

**Comment by coldfix** [comment]
Hey, I'd highly appreciate this feature as well. I tested termite and it's great - the only thing keeping me from using it is that you can't simply forward arbitrary arguments without worrying about quoting, i.e. correctly passing a string that needs quoting as one of the arguments to the command you want to execute inside termite is non-trivial.

I guess the solutions in #310/#311 are fine. But if you want to be clean (what about executing programs whose names look like options to termite?) and if you don't want to change the behaviour of `-e`, you could also introduce another command line option. E.g., like in terminator:

```
       -e, --command=COMMAND
              Runs the specified command instead of your default shell  or  profile
              specified command. Note: if Terminator is launched as x-terminal-emu‐
              lator -e behaves like -x, and the longform becomes --execute2=COMMAND

       -x, --execute COMMAND [ARGS]
              Runs the rest of the command line instead of your  default  shell  or
              profile specified command.
```

**Comment by schoettl** [comment]
I also miss this option. It's implemented in xterm, uxterm and terminator and others.

For example, I cannot use termite as terminal for the [Albert launcher](https://github.com/albertlauncher/albert) for this reason.

**Comment by Jesin** [comment]
It works just fine with backslashes.

**Comment by thestinger** [comment]
I've already explained how this would need to be implemented to be accepted in the past. No one wants to do that, so it's not being provided.
