### ISSUE TITLE
Invisible equal sign with Monoid font

### ISSUE THREAD

**Issue by siddharthist** [thestinger/termite#315]
When using 
```
$ termite --version
termite v11
```
when I type "=", nothing shows up. When I type "=>", only after I type the ">" does the "=" appear. If I type "<>", I get "=>" (but if copied to the clipboard, "<>" comes out). Any ideas on why this is happening? Or how I can disable this behavior? 

Here's my config:
```
$ cat ~/.config/termite/config 
[options]
font = Monoid 9

[colors]
background = #F9F9F9
foreground = #383838
foreground_bold = #B58900
foreground_dim = #675B83
cursor = #4B7CD7

# black dark/light
color0 = #DFDAEB
color8 = #F9F9F9

# red dark/light
color1 = #EB6466
color9 = #A31416

# green dark/light
color2 = #859900
color10 = #586E75

# yellow dark/light
color3 = #B58900
color11 = #675B83

# blue dark/light
color4 = #268BD2
color12 = #839496

# magenta dark/light
color5 = #D33682
color13 = #6C71C4

# cyan dark/light
color6 = #2AA198
color14 = #93A1A1

# white dark/light
color7 = #EEE8D5
color15 = #FDF6E3
```

**Comment by siddharthist** [comment]
Turns out, this only happens with the "Monoid" font.

**Comment by polyzen** [comment]
Could it have something to do with ligatures? I was going to suggest trying the default colorscheme (if that's not already it).

**Comment by siddharthist** [comment]
@polyzen I'll bet that's right.

**Comment by siddharthist** [comment]
@polyzen It does seem to have something to do with ligatures. It happens with the default color scheme as well.

**Comment by siddharthist** [comment]
From the [Monoid readme](https://github.com/larsenwork/monoid): "Monoid uses calt and Monoisome uses calt + liga which aren't supported by all programs."

**Comment by thestinger** [comment]
Please test in another VTE3 terminal, such as the vte-2.91 test application shipping with VTE.

**Comment by siddharthist** [comment]
Can confirm that it does work with the non-ligatured version of Monoid.

**Comment by thestinger** [comment]
It's unlikely that this is Termite-specific rather than a VTE issue.

**Comment by siddharthist** [comment]
@thestinger or @polyzen, Could you file an issue with them about ligatures? I don't have a bugzila.

**Comment by felixsanz** [comment]
@thestinger Happens here in Fira Code too.

If its the font fault, why it doesn't happen on other terminals?

**Comment by thestinger** [comment]
I didn't say it was the font's fault, I say it was a VTE issue. It's not in the scope of Termite.
