### ISSUE TITLE
Cursor waits before changing shape in neovim

### ISSUE THREAD

**Issue by teto** [thestinger/termite#316]
I have `  let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1` in my neovim config. It makes the cursor changing from block to caret mode on insertion. 
In termite, I have to hit at least one key for the cursor to update its shape.

I've tested in urxvt and upon entering insert mode, the cursor changes shape immediately hence I think it's a termite problem.

EDIT: it works correctly in termite when entering insert mode via 'a' or 'A' since I suppose it moves the cursor, contrary to 'i'

**Comment by teto** [comment]
I obtain the same behavior with the test utility shipped in VTE.

2016-03-01 18:25 GMT+01:00 Daniel Micay <notifications@github.com>:

**Comment by thestinger** [comment]
It needs to be reported upstream then: https://bugzilla.gnome.org/page.cgi?id=browse.html&product=vte.

**Comment by teto** [comment]
There seem to be a similar report https://bugzilla.gnome.org/show_bug.cgi?id=753645, here is my report anyway https://bugzilla.gnome.org/show_bug.cgi?id=762963
