### ISSUE TITLE
Odd behavior with fish

### ISSUE THREAD

**Issue by ixjlyons** [thestinger/termite#317]
Sorry for the vague issue title (please edit if you can think of a more specific one). I have an issue with i3wm + fish + termite. When I open several terminals side-by-side, my fish prompt gets replicated in seemingly random ways as I create more splits.

Here is an image that illustrates the issue:

![i3-fish-termite_issue](https://cloud.githubusercontent.com/assets/943602/13591444/804832b4-e49d-11e5-8f31-0aa3c59569a1.png)

I brought this up in the fish IRC channel, and they suggested it might be termite's fault.

I'm on Arch using the termite-git package from the AUR. [Here](https://github.com/ixjlyons/dotfiles/blob/master/fish/functions/fish_prompt.fish) is my fish prompt script for reference.

**Comment by jelly** [comment]
Is it also an issue with any other VTE terminal?

**Comment by ixjlyons** [comment]
It does not occur with lxterminal or xfce4-terminal.

**Comment by Narrat** [comment]
Well, a problem with this comparison could be, those terminal emulators use vte for gtk2, whereas termite uses vte3 for gtk3.
Other terminals which use vte3 would be for example roxterm, sakura, lxterminal with explicit gtk3, gnome-terminal, or the vte3 test utility. Probably best to check with one of those.

**Comment by ixjlyons** [comment]
Sorry, didn't think of that. The issue indeed occurs with the gtk3-based terminal emulators (tried roxterm and sakura). It would seem this is an upstream issue then.
