### ISSUE TITLE
Can you support FiraCode?

### ISSUE THREAD

**Issue by PaBLoX-CL** [thestinger/termite#318]
FiraCode is an amazing programming font:

https://github.com/tonsky/FiraCode

I tried to use it on termite, and doesn't work. Is it possible to support it? What could be needed to implement support for it?

Regards :)

**Comment by vodik** [comment]
I toyed with a similar font, [Monoid](https://github.com/larsenwork/monoid) and I'm afraid there's nothing we can do on our side to turn it on, it all comes down to the internals of how libvte does rendering. Its not something Termite handles.

Fixes for this should be done upstream with libvte.

**Comment by PaBLoX-CL** [comment]
Ok, I'll look into libvte then! Thanks for your clarification.
