### ISSUE TITLE
Text disappears when activating URL hints mode

### ISSUE THREAD

**Issue by AladW** [thestinger/termite#320]
Screencast:
https://ptpb.pw/cKT2

I'm using termite from master (4d8974829f11f47baa5e0a6915f82f3b0c474602), with vte3-ng 0.42.4.a-1 on Arch. Above behavior is in XFCE and i3, both with and without window compositing.

My termite config:
https://ptpb.pw/56o3

**Comment by kyrias** [comment]
Using the XIM input method causes it due to compositing layers in X being silly. Switch to something like UIM instead if you want XCompose to still work.

**Comment by jelly** [comment]
Thanks for the info @kyrias. It can be reproduced by using:

```
GTK_IM_MODULE=xim termite
```

**Comment by kyrias** [comment]
(Also see #89)

**Comment by thestinger** [comment]
My understanding is that this is a bug in GTK or X11. I don't think there's anything Termite can do to fix it.

**Comment by AladW** [comment]
This now seems to work with xim, GTK 3.20.3 and vte3-ng 0.44.1.a-1.
