### ISSUE TITLE
Termite ignores $SHELL 

### ISSUE THREAD

**Issue by AKuederle** [thestinger/termite#324]
I was trying to keep bash as my login shell and switch to zsh for all other interactive shells by running ```export SHELL=/bin/zsh``` at the end of my ```~/.bash_profile```. This solution works perfectly for many terminal emulators, but not for termite. Termite seems to ignore the $SHELL env-var. I know this is probably expected behavior and not a bug, but is there a way to make termite respect the $SHELL variable or a workaround to achieve what I was aiming for?

**Comment by ixjlyons** [comment]
The command returned by `vte_get_user_shell()` (which in turn seems to retrieve the user's login shell) takes precedence over `$SHELL` [[1]]. Perhaps this should be reversed?

For now, you could just use `termite -e /bin/zsh`

[1]: https://github.com/thestinger/termite/blob/2a87f8dd6399c1ecff972b8f9508f719dd863da0/termite.cc#L1460-L1464

**Comment by AKuederle** [comment]
Tanks for the fast reply! I will work with the suggested solution for the time being. But I think it should be changed (as it is probably not much effort, and I can't think of any situation, where the current situation would preferable)

**Comment by 0xItx** [comment]
This is somewhat hackish but you could also set zsh as your default shell and run `exec bash` in login shells (e.g. by adding `[[ -o login ]] && exec bash` to your .zshrc)
