### ISSUE TITLE
display pictures in terminal

### ISSUE THREAD

**Issue by teto** [thestinger/termite#326]
I've no idea how big an undertaking this can be (does it depend on libvte ?) but I miss seeing pictures in terminal as I could with urxvt and ranger.

**Comment by jelly** [comment]
Do you mean displaying with imlib2? Does this work with plain VTE, for example gnome-terminal?

Are we talking about:
https://github.com/hut/ranger/wiki/Image-Previews

**Comment by thestinger** [comment]
It's not a Termite bug: https://github.com/thestinger/termite/issues/199.
