### ISSUE TITLE
Cycling links with u and U while in selection mode no longer functions.

### ISSUE THREAD

**Issue by krompus** [thestinger/termite#327]
Only the top link (upon pressing `u`) or bottom link (upon pressing `U`) will be highlighted.

**Comment by polyzen** [comment]
@krompus, what version are you using? master?

**Comment by krompus** [comment]
[I installed your AUR package.](https://aur.archlinux.org/packages/termite-git/)

**Comment by jelly** [comment]
I can't reproduce this issue myself at work, but I can now at home I'm guessing it has something todo with the way urls are shown.

Can you take a screenshot of the situation?

**Comment by krompus** [comment]
Yep! [Here is a section with four URLs.](http://i.imgur.com/HtInNnR.png?1)

When I enter selection mode with `Ctrl-Shift-Space`, I can press `u` to select the imgur one on the top, and if I press `U`, the vim one on the bottom is selected. Successive presses of either key are unresponsive; I can only select the top and bottom displayed links.

Number hinting for links with `Ctrl-Shift-x` still works, so I'll be using that for the time being, but it would be nice have link cycling back, as I've trained muscle memory for it, and I find it more comfortable and intuitive than typing the number hint.

**Comment by jelly** [comment]
Hmm this also might be yet another VTE bug, since downgrading seems to fix it. Seems they broke vte_terminal_search_find_previous and vte_terminal_search_find_next slightly.

**Comment by krompus** [comment]
Lovely. :)

Would you mind sharing your versions of termite and VTE? I think I might downgrade for now.

**Comment by dkasak** [comment]
@krompus If you're still bothered by this, see #333, I think it's the same problem.
