### ISSUE TITLE
Padding gone 

### ISSUE THREAD

**Issue by eigengrau** [thestinger/termite#331]
Not sure whether this belongs in vte3-ng rather; but I’ve noticed that after updating to vte3-ng 0.44.0.a, vte-common 0.44.0, internal padding defined in `gtk.css` isn’t applied anymore.

**Comment by thestinger** [comment]
Likely neither, it would be an upstream VTE issue.

**Comment by eigengrau** [comment]
I did find [this](https://git.gnome.org/browse/vte/commit/?id=f34c6fb8e9c795eec6ea993372625b094f2b3c51) change which relates to the CSS. Is the change in `VTE_TERMINAL_CSS_NAME` something that’s picked up by termite?

**Comment by thestinger** [comment]
It's based on VTE, so any change in VTE is going to have an impact. The vte-ng project only has a few small API extensions. It makes *zero* changes to the underlying code. Anything not related to those API extensions is a VTE issue.

**Comment by eigengrau** [comment]
Okay, thanks, refiling this with Gnome.

**Comment by thestinger** [comment]
They probably intentionally changed something in a backwards incompatible way. I wouldn't expect it to be a bug.
