### ISSUE TITLE
Previous search match key (N) is often not working

### ISSUE THREAD

**Issue by Ape** [thestinger/termite#333]
When doing a search (`/` or `?`) I can always scroll through the results with `n`. However `N` (for previous match) is often not doing anything. Sometimes it will go one or some results backwards and then stops doing anything.

**Comment by ixjlyons** [comment]
I have noticed this as well. I'm pretty sure it's an upstream issue.

**Comment by dkasak** [comment]
It appears the previous match is only selected if it is in the line immediately preceding the line of the current match. As soon as selecting the previous match would require skipping over a few lines without matches, it stops working.

**Comment by dkasak** [comment]
This seems to be the [relevant upstream ticket](https://bugzilla.gnome.org/show_bug.cgi?id=769400).
