### ISSUE TITLE
Cycle fonts with a key

### ISSUE THREAD

**Issue by Ape** [thestinger/termite#334]
I'd like to have two fonts defined (with both name and size) and then change between them runtime using some keybinding.

**Comment by polyzen** [comment]
How would this be useful?

**Comment by Ape** [comment]
I like to use a very small bitmap font on my terminal. It's perfect for me, but hard to read for others, especially from any distance. I would like to quickly switch to another font.

**Comment by polyzen** [comment]
Just in case you weren't aware:  current alternatives are increasing the font-size on-the-fly, or editing the config and reloading termite. The latter could be done via a script and keybinding -- we never did convince the author on a better way of this :p (see #273).

**Comment by Ape** [comment]
Thanks for the tips. I guess changing the config file and using `USR1` signal to reload the config is the best workaround for me currently.

**Comment by thestinger** [comment]
I don't want to support this as a special cased feature. It's much too niche.
