### ISSUE TITLE
Highlight matches in scrollback completion (ctrl-tab)

### ISSUE THREAD

**Issue by Ape** [thestinger/termite#335]
I sometimes want to quickly search if the scrollback has some string in it. `ctrl-tab` will find that string if it's there. It would be useful if it would also highlight the matches when doing scrollback completion to see exactly where the match is.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
