### ISSUE TITLE
Scale bitmap fonts only with integer factors and without smoothing

### ISSUE THREAD

**Issue by Ape** [thestinger/termite#336]
Bitmap fonts do not scale font size well. This is expected limitation. However, bitmap fonts can be scaled nicely with integer factors (2x, 3x, ...). I propose that with bitmap fonts `+` would only use the integer steps.

Additionally, currently some kind of smoothing filtering is used when scaling bitmap fonts. It would look better (with integer scaling factors) if no filtering was performed, i.e. nearest-neighbor.

**Comment by thestinger** [comment]
Font rendering isn't implemented by Termite.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
