### ISSUE TITLE
Padding no longer works

### ISSUE THREAD

**Issue by jmauss** [thestinger/termite#337]
I am currently running arch, and before I updated my machine today, padding worked totally fine. I did notice an update to vte-common (no idea if its related), and since then, the padding does not change from default no matter what I change in gtk.css

**Comment by Narrat** [comment]
Same issue as https://github.com/thestinger/termite/issues/331 ?

**Comment by jmauss** [comment]
So it is a gtk issue itself.. thanks for the reference.
