### ISSUE TITLE
Padding not working after gtk 3.20 update

### ISSUE THREAD

**Issue by TaylanTatli** [thestinger/termite#338]
It was ok but after update it's not working. I didn't change anything. I recompiled vte-ng against gtk 3.20 because it was showing an error about it. But it's still same. There is only warning but i don't think it's padding related:

```
(termite:8470): Vte-WARNING **: (vtegtk.cc:1718):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
```

**Comment by TaylanTatli** [comment]
Ok, i solved my problem. After rebuilding against 3.20, added this code to gtk.css
```
VteTerminal, vte-terminal {
padding: 4px;
}
```
Related bug reports:
https://bugs.archlinux.org/task/48876?project=5&cat[0]=33&string=vte3-ng
https://bugzilla.gnome.org/show_bug.cgi?id=763538

**Comment by wimstefan** [comment]
Thanks for that solution - it works beautifully! :smirk:  :+1:
