### ISSUE TITLE
VtePadding selector has changed with GTK 3.20

### ISSUE THREAD

**Issue by frebib** [thestinger/termite#339]
The CSS selector has supposedly changed to `vte-terminal` from `VteTerminal` in GTK 3.20, although I can't get it to work either way. I'm not sure if there is anything you have to change/update to make it work or the documentation is wrong, but either way the padding isn't working as of right now.

**Comment by Narrat** [comment]
See issues #338 #337 #331 
And the reason it's not working should be the fact, that vte3-ng needs a rebuild against gtk-3.20.

On the Arch Bugtracker is an issue for this
