### ISSUE TITLE
Cursor is hard to spot while moving on selection/visual mode

### ISSUE THREAD

**Issue by michelesr** [thestinger/termite#340]
When moving in selection mode (without visual mode) I can't see the cursor (with blinking set to on), and also there are some blank squares in its previous positions.  

![termite](https://cloud.githubusercontent.com/assets/2516077/14469517/4e66e47a-00e5-11e6-9b62-e83a4ace7820.png)

The cursor is visible (blinking) when not moving.

**Edit**: this description is **inaccurate**, please **read below**.

**Comment by michelesr** [comment]
I changed the title because it happens also with GTK 3.18.3-1

**Comment by Ape** [comment]
Can you see the cursor at all if blinking is set to off?

**Comment by michelesr** [comment]
> Can you see the cursor at all if blinking is set to off?

Nope.

**Comment by michelesr** [comment]
If the cursor is blank and you perform a move (for example pressing `j`) the previous spot maintain the current status (blank), while if it's invisible (has the background color) and you move, the previous spot is not marked. Transition states also leave a half blank cursor, like this:

![termite](https://cloud.githubusercontent.com/assets/2516077/14471361/853463ca-00ee-11e6-81b4-b9d3b9bc9f37.png)

Seems like that the status of the previous spot needs to be reset to invisible.

**Comment by jelly** [comment]
Which vte version do you have installed?

**Comment by michelesr** [comment]
> Which vte version do you have installed?

vte-ng: 0.44.0.a-2

**Comment by jelly** [comment]
Ah this bug is fully reproducible, doesn't seem to happen with VTE3 0.44.2

**Comment by Ape** [comment]
I can reproduce this with 0.44.0.a and 0.44.1.a. I haven't tested 0.44.2.

**Comment by nzinov** [comment]
I have this with vte3-ng 0.44.1.a-1

**Comment by michelesr** [comment]
My first description is inaccurate.

What really happens:

- With `cursor_blink = off` the cursor is not visible while moving in selection and visual mode

- With `cursor_blink = on` the cursor blinks even while moving in selection and visual mode, so it's hard to track its movements. 

In order to improve usability the cursor should be always visible (not blinking) while moving in selection/visual mode.

Also when you move the cursor to a new location, the previous location doesn't resets their background color (maybe a dedicated issue should be opened for this)

**Comment by LNQ** [comment]
Can confirm, after downgrading to vte3-ng-0.42.4.a-1 the cursor is perfectly visible.
Archlinux, termite  v11-10-gc252d4b

**Comment by quartz55** [comment]
Can also reproduce that this happens in 0.44 and not on 0.42

I've also noticed the following warning while launching termite on 0.44:
`
(termite:7616): Vte-WARNING **: (vtegtk.cc:1718):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
`

This doesn't show up on 0.42. Not sure if it's related but might be worth a try :stuck_out_tongue_winking_eye:

**Comment by thestinger** [comment]
The cursor issues are fixed by vte3-ng 0.44.1b.
