### ISSUE TITLE
Glitched cursor in selection/visual mode

### ISSUE THREAD

**Issue by michelesr** [thestinger/termite#341]
If the cursor is blank and you perform a move (for example pressing `j`) the previous spot maintain the current status (blank), while if it's invisible (has the background color) and you move, the previous spot is not marked. Transition states also leave half blank squares, like this:

![termite](https://cloud.githubusercontent.com/assets/2516077/14471361/853463ca-00ee-11e6-81b4-b9d3b9bc9f37.png)

Seems like that the status of the previous spots needs to be reset to invisible.

**Comment by quozd** [comment]
any progress on this, guys?

**Comment by thestinger** [comment]
No. Each VTE release introduces new issues and Termite isn't in very active development. Maybe the problem will go away in a new VTE release, maybe it won't. If it requires changes to the patches or something like that, someone will need to step up to do it.

**Comment by jelly** [comment]
This has been a mistake in a patch I ported to the new vte release which didn't invalidate the cursor position. vte3-ng 0.44.1.b fixes this bug.
