### ISSUE TITLE
Adding padding to Termite

### ISSUE THREAD

**Issue by realcomplex** [thestinger/termite#342]
Hey!

I am trying to add inner padding to the borders of my termite terminal. I have looked at the proposed solution in #111, but this does not seem to work for me at all. I have the file `~/.config/gtk-3.0/gtk.css` with the following contents:
```
VteTerminal {
    -VteTerminal-inner-border: 20px;
}
```
But it is not working, even after a reboot and everything. I have also tried to set the `padding` property, also with no outcome. What am I doing wrong? Is it even possible to set the padding?

Thanks in advance for any help.

**Comment by Narrat** [comment]
The solution there is propably to old. GTK changed some of the values.
https://github.com/thestinger/termite/issues/338 would be an issue where it was talked about with gtk-3.20

**Comment by realcomplex** [comment]
Okay, that works, thanks!
