### ISSUE TITLE
Custom hotkeys in order to start programs

### ISSUE THREAD

**Issue by zunder** [thestinger/termite#344]
Is there any way to define custom hotkeys in the config file? I am coming from urxvt, where you can use keysym like in `URxvt.keysym.C-q: ranger \015`, which would start ranger in the current folder. As I do want to move to termite, such a feature would be appreciated.

**Comment by polyzen** [comment]
This is probably blocked-by/dupe-of #62

**Comment by zunder** [comment]
You are right, I'll follow the one.
