### ISSUE TITLE
Powerline glyphs not rendered properly

### ISSUE THREAD

**Issue by rhssk** [thestinger/termite#347]
*termite 11-3
*NVIM 0.1.4 with Airline plugin (https://github.com/vim-airline/vim-airline)
*using Source Code Pro patched with https://github.com/powerline/fontpatcher

Powerline glyphs seem to be rendered incorrectly, or rather the rectangular parts of Airline are simply not high enough. This (https://i.imgur.com/M3AjmOy.png) is what the glyphs look like on Termite and this is how they look on urxvt (https://i.imgur.com/mZXG2Uf.png). On urxvt it is drawn almost perfectly. Tried different fonts, got the same result.

After a bit of digging around, I stumbled upon this, which is maybe describing my issue: 
https://bugzilla.gnome.org/show_bug.cgi?id=682635
If it is really a problem with VTE then I know that you can't do anything about it, just want be be sure.

**Comment by wsdjeg** [comment]
@rhssk you need change your font size，I get same issue .but has been fixed.
you can have a look at my dotfiles

**Comment by rhssk** [comment]
I tried different font sizes but the problem remains.

**Comment by thestinger** [comment]
Font rendering is done by VTE via Pango.
