### ISSUE TITLE
Ctrl+C makes terminal unusable

### ISSUE THREAD

**Issue by Airblader** [thestinger/termite#349]
Sometimes when I cancel a command via Ctrl+C, the terminal is in an unusable state afterwards. By that I mean that while sending another Ctrl+C will work, any other input simply doesn't show up. I haven't found any way to "repair" the terminal and have to end up closing it.

This only happens sometimes (but frequently), not everytime.

**Comment by thestinger** [comment]
Maybe using `reset`? Seems like this would probably be a VTE bug.

**Comment by funeralismatic** [comment]
Sometimes it happens if you kill ncurses programm (or if segmentation fauld is happen?) via Ctrl+C. Cursor is invisible, sometimes it possible to typing, sometimes not. Sometimes it breaks newlines.

**Comment by thestinger** [comment]
This is an upstream issue. You can confirm it happens with VTE3.
