### ISSUE TITLE
Build keeps failing in the same spot

### ISSUE THREAD

**Issue by cbf305** [thestinger/termite#359]
I built this on Ubuntu 16.04 upgraded from 14.04 a few days after 16.04's release.  I am trying to build it on a fresh Ubuntu 16.04 VM and the build is failing in the same spot each time.  I setup a second 16.04 VM and it also fails in the same spot.

[termite-error.txt](https://github.com/thestinger/termite/files/261280/termite-error.txt)

Thanks for any insight you can provide!

**Comment by jelly** [comment]
This is introduced in VTE3 0.44 if I recall correcly. So your ubnut 16.04 probably needs a newer VTE. Do you use vte3-ng?

**Comment by cbf305** [comment]
I was cloning your repo thestinger/vte-ng.  When I grabbed that specific branch it then worked.  Thank you!
