### ISSUE TITLE
Use C++14 features to replace make_unique from <util/memory.hh>

### ISSUE THREAD

**Issue by jelly** [thestinger/termite#360]
C++14 brings [make_unqiue](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique) which can replace util/memory.hh.
- Change the Makefile to compile with c++14
- Replace make_unique with std::make_unique
- Investigate the compiler warnings

**Comment by dotdash** [comment]
As I've written in #568 make_unique in util/memory.hh is a completely different function than std::make_unique. You can't replace one by the other.

You could replace the current `make_unique(...)` calls by `std::unique_ptr<gchar, decltype(&g_free)>(...)`. That's somewhat ugly, but at least avoids the confusion of having two functions with the same name but wildly different semantics. Or go and rename `make_unique` into `into_unique` or so. Names are hard :)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
