### ISSUE TITLE
Cursor changes color when being over colored text.

### ISSUE THREAD

**Issue by ivegotasthma** [thestinger/termite#365]
Hello,

I noticed that the cursor changes its color from white to whatever the color of the text it is over. Here's a short [demonstration](https://vid.me/CkL6) of the issue. In the demo I'm using neovim.

OS: Arch
Termite: v11

**Comment by wsdjeg** [comment]
I think it is a good featue. and why it is a issue?

**Comment by wsdjeg** [comment]
I say it is good feature,because as we know in nvim, at the cursor position, we have two colors, bg and fg, we do not know what the bg is, if the cursor has same  color as fg will make it easy to find the cursor.
for example, sometimes I use white as my background color, and the text color is green, so if the corsur is white, how could I find my cursor?

**Comment by ivegotasthma** [comment]
@wsdjeg I haven't seen this mentioned as a feature.

It's behavior is different from that of `urxvt` but similar to `xterm`, `lxterminal` and `qterminal`. I guess it's standard.

The switching of the color distracts me, that's why I'm considering it as an issue but you do raise a good point.

**Comment by jelly** [comment]
I'm not sure if VTE offers an option to get rid of this behavior, if it has a config option would be the solution.

**Comment by ivegotasthma** [comment]
@jelly I looked at their most recent API documentation and they have options for setting the color of the cursor in a few ways. [doc](https://developer.gnome.org/vte/0.43/VteTerminal.html#vte-terminal-set-color-cursor-foreground)

**Comment by ixjlyons** [comment]
`cursor` is already a config option, and if set, it overrides this behavior. Perhaps there should be a comment in the default config describing this behavior when `cursor` is not set, like for the `highlight` option.
