### ISSUE TITLE
Make fullscreen keybinding configurable

### ISSUE THREAD

**Issue by wimstefan** [thestinger/termite#369]
Would it be possible to make the keybinding for fullscreen configurable? F11 is clashing with keybindings of other CLI apps as for example weechat ...

**Comment by jelly** [comment]
This is a duplicate of #62

**Comment by wimstefan** [comment]
My apologies - that's embarrassing :unamused:  
I was only searching for 'F11' and 'fullscreen' hence my presumption that question didn't raise yet ...
Thanks for pushing me in the right direction! :sunglasses:
