### ISSUE TITLE
Font size changing impossible under some keyboard layouts

### ISSUE THREAD

**Issue by quasisphere** [thestinger/termite#371]
On the Finnish keyboard layout plus is obtained without pressing shift (unlike the US layout). Since the modifier masks are hard coded in termite.cc in such a way that pressing shift is necessary, emitting the keybinding ctrl-+ to termite is impossible. The same applies to the keybinding ctrl-=, just the other way around: In Finnish layout pressing shift is necessary, while in the US layout it is not.

In effect, it is only possible to decrease the font size, which is of course funny but a little bit inconvenient at the same time.

**Comment by jelly** [comment]
I guess this really calls for user-configurable keybindings, which I have the feeling we really need by now. I'll look into it this week hopefully.

**Comment by f-koehler** [comment]
I fixed it for German keyboard layout (https://github.com/thestinger/termite/compare/master...f-koehler:fix371). Maybe you can adopt this as a workaround for the Finnish layout as well.
I still hope we will jave configurable keybindings soon :smile:

**Comment by jelly** [comment]
The ctrl + 0 idea for resetting the font size is a nice idea, chrome does the same thing. Except I guess this will still cause an issue for Ctrl + for increasing the font size on finnish keyboard layouts?

I'm also not sure if any cli app uses ctrl + 0 for something, which still concludes that we need configurable keybindings.

**Comment by f-koehler** [comment]
I consider the thing I did there as a temporary workaround, hope to see configurable keys soon :)

**Comment by dmarcoux** [comment]
It is also not working on a Canadian Multilingual keyboard layout.

**Comment by jelly** [comment]
@dmarcoux  yes, we are aware of the issue that's why I'm working on making keyboard shortcuts configurable.

**Comment by carnager** [comment]
Either the hotkeys have changed or it doesn't work at all anymore in latest termite. I have us layout but C-S-Space followed by -/+ does not do anything anymore.

**Comment by manu09** [comment]
It doesn't even work on US keyboard layouts.
