### ISSUE TITLE
How can you disable the flow-control feature (Ctrl-s/Ctrl-q)?

### ISSUE THREAD

**Issue by wimstefan** [thestinger/termite#372]
Well the title says it all.
If I for example try to invoke the spell auto-completion in vim with Ctrl-x Ctrl-s the terminal freezes and it took me quite some time to find out what causes that. I'm now able to un-freeze the terminal with Ctrl-q but I'd like to be able to either switch this feature off or at least configure the keybindings for that.

**Comment by wsdjeg** [comment]
@wimstefan ctrl-s works will in neovim with termite.maybe you can have a try with neovim

**Comment by thestinger** [comment]
This isn't a Termite issue. The flow control keybindings control the kernel's terminal infrastructure.

**Comment by wimstefan** [comment]
I see. Thanks a lot for pushing me in the right direction! :smile:
