### ISSUE TITLE
Respect GTK_THEME environment variable to allow 'dark mode'

### ISSUE THREAD

**Issue by grtlr** [thestinger/termite#373]
It would be great if ``termite`` would respect the ``GTK_THEME`` environment variables. This would, for example, allow users to switch the theme of the terminal window to dark mode. More information can be found [here](http://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis).

Another way to set the dark mode should be the ``_GTK_THEME_VARIANT(UTF8_STRING) = "dark"`` window property. Maybe a ``use_dark_mode = true`` could be added to the config file?

**Comment by thestinger** [comment]
What do you mean by respect? If it's a standard GTK+ feature, then it already supports it.

**Comment by grtlr** [comment]
For some reason I could neither set ``_GTK_THEME_VARIANT(UTF8_STRING)`` nor use ``GTK_THEME`` with termite. One answer in the link i provided reads: `as per the first line in my post, this works for systems/apps using gtk3 version 3.12 or higher (but the apps must honor the GTK_THEME env variable)`. This lead me to the conclusion that termite is not influenced by these settings.

**Comment by thestinger** [comment]
Since it's included in the GTK+ documentation, it should already be working for anything not explicitly overriding the theme. Termite doesn't do that, so this doesn't seem like a Termite issue. If the feature doesn't work in GTK+, that's a GTK+ problem.
