### ISSUE TITLE
Fullscreen with F11 is inserting a tilde

### ISSUE THREAD

**Issue by varmanishant** [thestinger/termite#374]
When I press <kbd>F11</kbd> it makes termite fullscreen as expected but it also inserts a tilde `~` in my Arch Machine. Is this a bug?

**Comment by jelly** [comment]
I can't reproduce this issue, which version of termite are you using?

**Comment by polyzen** [comment]
Doesn't happen in zsh, but in python interactive shell, here.. termite v11-4-g2a87f8d

**Comment by ixjlyons** [comment]
This is explicitly implemented behavior (by vte). See http://aperiodic.net/phil/archives/Geekery/term-function-keys.html. I think the solution would be to not propagate the F11 key press event.
