### ISSUE TITLE
how about set $TERM_ITALICS = 'true' by default?

### ISSUE THREAD

**Issue by wsdjeg** [thestinger/termite#378]
as some plugin use this var chect terminal italic support. and terminal support italic well, but the value of $TERM_ITALICS is NULL, should it be set as 'true' by default?
see  https://github.com/morhetz/gruvbox/blob/d7f7f1951d0716957f3e32549a247e92d25b1449/colors/gruvbox.vim#L31-L37

**Comment by thestinger** [comment]
That's what terminfo is for. I can't find any indication that this has widespread usage.

**Comment by wsdjeg** [comment]
I do not know the the value of $TERM_ITALICS is NONE.
here is my output of stty -a, and I have installed termite-terminfo.
```
✔ wsdjeg:DotFiles [ master | ✔  ] ➭ stty -a
speed 38400 baud; rows 34; columns 151; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
✔ wsdjeg:DotFiles [ master | ✔  ] ➭ pacm
pacman             pacman-db-upgrade  pacman-key         pacman-optimize    pacmd              
✔ wsdjeg:DotFiles [ master | ✔  ] ➭ pacman -Ss terminfo
community/ghc 8.0.1-1
    The Glasgow Haskell Compiler
community/rxvt-unicode-terminfo 9.22-2
    Terminfo files for urxvt
community/termite-terminfo 11-3 [installed]
    Terminfo for Termite, a simple VTE-based terminal
community/unibilium 1.2.0-1 [installed]
    A terminfo parsing library
```

**Comment by thestinger** [comment]
I'm saying that there's no need for this ad-hoc environment variable, since there's already terminfo to provide the ability to use italics across terminals in a compatible way. Ask the project using this environment variable to switch to terminfo, rather than asking us to support a redundant feature.

**Comment by wsdjeg** [comment]
ok, I got it , thank you!
