### ISSUE TITLE
Does termite have feature like `$WINDOWID` in Xterm?

### ISSUE THREAD

**Issue by dhad05** [thestinger/termite#379]
Does termite have feature like `$WINDOWID` in Xterm? I don't see it mentioned anywhere.

**Comment by thestinger** [comment]
It does set `$WINDOWID`.

**Comment by dhad05** [comment]
I use a bash script to set window title 

```
#!/usr/bin/bash
xwit -id $WINDOWID -name "$1"
```
It works for Xterm but I don't know why it doesn't work for Termite.

**Comment by jelly** [comment]
Works fine here:

```
[jelle@P9][/tmp/termite]%echo $WINDOWID 
50331651
```
