### ISSUE TITLE
Add `word_chars` option back

### ISSUE THREAD

**Issue by kazuoteramoto** [thestinger/termite#380]
Hi!

Commit 7f03ded7308ad0e26b72b150080e4f3e70401815 move the is_word_char from vte to termite and removed the option to set a custom `word_chars`, can we get this option back?

I have a lot of files with : in the name and selecting is very hard without a option to allow : in the is_word_char.

**Comment by thestinger** [comment]
A patch implementing this based on the new API would be welcome. The Termite-level word matching needs to continue to match the VTE-level word matching, so it requires adding support for setting word_char_exceptions and then using the configured value for Termite's keyboard selection. It won't happen if no one steps up to do it - there's no one working on developing Termite features that only other people are interested in.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
