### ISSUE TITLE
C-M-% for Emacs

### ISSUE THREAD

**Issue by paulie4** [thestinger/termite#381]
I found this commit (https://github.com/thestinger/termite/commit/614eca0f030182dcde45e754eb04928549abd178) by @holomorph, which sounds like it should have added support for C-M-%, but when I try C-M-%, it doesn't seem to work. I've tried using `showkey -a` directly in the terminal and `(read-event)` within terminal Emacs, and it looks like termite sends `^[%` when M-% or when C-M-% are pressed.

BTW, do you know why xterm seems to send `^[[27;8;37~` for C-M-%, but the above commit looks like it tries to send `^[[27;14;37~`? What do the ;8; and ;14; mean?

**Comment by Kaligule** [comment]
I am using termite on Arch Linux with a us-keyboard and C-M-% in (terminal-)emacs triggers the function `query-replace`. 

`
$ showkey -a
Press any keys - Ctrl-D will terminate this program

^[% 	 27 0033 0x1b
 	 37 0045 0x25
`
What was supposed to happen?

**Comment by paulie4** [comment]
C-M-% runs the command `query-replace-regexp`. M-% runs the command `query-replace`, so Emacs is only seeing M-%, not C-M-%. You can run `C-h k` to see what keys Emacs is seeing.

showkey is showing you that only Escape (27) and percent (37) are being sent. Since the commit shows `{ GDK_KEY_percent,    "\033[27;14;37~" }`, I would think that showkey would show 11 lines, one for escape, and one for each of the next characters in the string.

I actually can't figure out how to get showkey to show the keys that xterm is sending, since it just shows ¥ whether I press C-M-% or just press M-%, but that's not what xterm sends Emacs. If you press M-: (meta+colon) in Emacs and run `(read-event)` (although, in xterm, I had to press Escape then colon, since M-: sends a non-ASCII character), and then press C-M-%, `[27;8;37~` gets printed, and if you look at the \*Messages* buffer, you'll see that `(read-event)` picked up the escape key, so the rest of the characters that were sent by xterm are just printed out, unescaped.

BTW, I manually tried typing Escape with the two different escape codes `[27;8;37~` and `[27;14;37~` in terminal Emacs, and Emacs seems to accept either one as a substitute for C-M-%, so I guess the ";8;" versus ";14;" isn't that important.

I'm also using Arch Linux. I had uninstalled termite a while back and can't get it to install now, since pacman says "vte3-ng and vte3 are in conflict". I also tried building it from source, but I get a bunch of errors, like this:
```
$ make
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v12-13-g7738c76\" -pthread -I/usr/include/vte-2.91 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/p11-kit-1  -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lpcre2-8 -lgnutls -o termite
termite.cc: In function ‘void update_selection(VteTerminal*, const select_info*)’:
termite.cc:443:85: error: ‘vte_terminal_set_selection_block_mode’ was not declared in this scope
     vte_terminal_set_selection_block_mode(vte, select->mode == vi_mode::visual_block);
                                                                                     ^
termite.cc:450:60: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      cursor_col, cursor_row);
                                                            ^
termite.cc:453:74: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      select->begin_col, select->begin_row);
                                                                          ^
termite.cc:459:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc:465:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc: In function ‘void enter_command_mode(VteTerminal*, select_info*)’:
termite.cc:472:41: error: ‘vte_terminal_disconnect_pty_read’ was not declared in this scope
     vte_terminal_disconnect_pty_read(vte);
                                         ^
```

**Comment by paulie4** [comment]
@holomorph, yes, I followed the README instructions and did a recursive clone to also get the vte-ng repo. The vte-ng project compiles without a problem, but termite does not.

**Comment by holomorph** [comment]
What does that have to do with using pacman?  A recursive clone of _what_ to get vte[3]-ng? You're not making any sense.

**Comment by paulie4** [comment]
The DEPENDENCIES section of the README says, "The vte-ng project is required", and the BUILDING section says to do a "git clone --recursive https://github.com/thestinger/termite.git". The --recursive option is what automatically gets the vte-ng project, and like I said, I was able to build that project successfully but termite still did not build. That is what I am referring to.

What exactly are you referring to in the README that has to do with using pacman?

**Comment by jelly** [comment]
This is basic Arch Linux maintenance, vte3 conflicts with vte3-ng so you have to say yes to the removal of vte3. Then you can easily compile termite.

**Comment by paulie4** [comment]
Oh duh, sorry, I don't know why I didn't realize that the "vte3-ng" pacman package was the same as the "vte-ng" GitHub project.

I have termite installed now, and sure enough, when I open up terminal Emacs and run the (read-event) command, it shows that only Escape and % get sent when C-M-% are pressed, even though this commit (https://github.com/thestinger/termite/commit/614eca0f030182dcde45e754eb04928549abd178) by @holomorph looks like `^[[27;14;37~` should be sent, or am I not understanding what this code is supposed to do?
```
static const std::map<int, const char *> modify_meta_table = {
...
    { GDK_KEY_percent,    "\033[27;14;37~" },
...
...

gboolean key_press_cb(VteTerminal *vte, GdkEventKey *event, keybind_info *info) {
...
    } else if ((modifiers == (GDK_CONTROL_MASK|GDK_MOD1_MASK)) ||
               (modifiers == (GDK_CONTROL_MASK|GDK_MOD1_MASK|GDK_SHIFT_MASK))) {
        if (modify_key_feed(event, info, modify_meta_table))
            return TRUE;
```

**Comment by craigbarnes** [comment]
> What do the `;8;` and `;14;` mean?

@paulie4 Those numbers both correspond to modifier codes, as shown in the ncurses `user_caps(5)` man page:

```
            Value   Description
            ──────────────────────────────────
            2       Shift
            3       Alt
            4       Shift + Alt
            5       Control
            6       Shift + Control
            7       Alt + Control
            8       Shift + Alt + Control
            9       Meta
            10      Meta + Shift
            11      Meta + Alt
            12      Meta + Alt + Shift
            13      Meta + Ctrl
            14      Meta + Ctrl + Shift
            15      Meta + Ctrl + Alt
            16      Meta + Ctrl + Alt + Shift
```

`xterm` may treat `Meta` and `Alt` as the same thing, depending on the `altIsNotMeta` setting.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
