### ISSUE TITLE
Building for Fedora 23/24

### ISSUE THREAD

**Issue by mamiu** [thestinger/termite#382]
I tried to build termite for Fedora but couldn't make it. Building vte-ng has already failed.

Or is there an flatpack package to install it easily (everywhere)?

**Comment by thestinger** [comment]
> I tried to build termite for Fedora but couldn't make it. Building vte-ng has already failed.

Building vte-ng is the same as building vte. Perhaps you can use Fedora's vte package as a starting point. If you posted the errors you were running into, then there would be something specific to respond to if there's a known solution.

> Or is there an flatpack package to install it easily (everywhere)?

No, and it's not something that I'm interested in providing. It's not a proprietary application and it's not complex so there's little gain from that effort. This project is also very low on the list of stuff that I care about, so development will still be happening very slowly but not significant work that's not strictly necessary.

**Comment by mamiu** [comment]
Thanks! Ok, here's what I did:

`git clone https://github.com/GNOME/vte.git`
`cd vte`
`./autogen.sh`

The output (the same for vte-ng):
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:57: installing './compile'
configure.ac:16: installing './install-sh'
configure.ac:16: installing './missing'
doc/openi18n/Makefile.am: installing './depcomp'
src/Makefile.am:179: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
src/Makefile.am:206: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
src/Makefile.am:28: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:28:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:28:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:28:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:28:   its definition is in aclocal's search path.
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
```

**Comment by thestinger** [comment]
You need to install libtool and perhaps other dependencies for the Vala portions of the build.
