### ISSUE TITLE
I cannot use Top or Htop tools from remote connexion

### ISSUE THREAD

**Issue by WyRe** [thestinger/termite#383]
I get the follow msg when I try to use this tools in a remote server via ssh prompt:

`top
'xterm-termite': unknown terminal type.
`

**Comment by thestinger** [comment]
That's expected. You need to upload the termite.terminfo file from this repository to the server and install it to the terminfo database with `tic -x termite.terminfo`. No need for root access, it will install to the home directory for non-root users.
