### ISSUE TITLE
Is it possible to specify several fonts ?

### ISSUE THREAD

**Issue by teto** [thestinger/termite#389]
hi,

in i3status/urxvt it is possible to specify several fonts; in case a character doesn't exist in the default font, i3status will look into the others. I wonder if something similar is possible in termite ? 
I've tried:
`font = Inconsolata For Powerline 11, FontAwesome 9`
as well as 
`font = Inconsolata For Powerline 11
font = FontAwesome 9`
without success (some characters don't appear either way).

**Comment by jelly** [comment]
This sounds tricky, I'm not sure if VTE has anything for this. This option sounds more like a workaround then a real solution to the character display issue.

This PR implements some fix related to this I guess, but I'm not sure if I'm in favor of it.
https://github.com/thestinger/termite/pull/386

**Comment by teto** [comment]
I opened an issue here even if I think that would rather be a job for the terminal to handle fonts no ? https://bugzilla.gnome.org/show_bug.cgi?id=770274

**Comment by jelly** [comment]
Shouldn't fontconfig handle the fallback? https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/

**Comment by teto** [comment]
Makes sense rather then modifying every application. This link looks very cool. I will try that when I get more time and report back. Thanks

**Comment by teto** [comment]
Thanks to the link, I realized my understanding was wrong, i3 does not allow to set several fonts, the 2 fonts had some glyph in commons, which confused me (as well as the examples giving several fonts one after another). I now know how to properly setup everything thanks
