### ISSUE TITLE
using termite -e results in Vte-WARNING

### ISSUE THREAD

**Issue by jfavega** [thestinger/termite#390]
when attempting to start any program utilizing termite -e I receive the following error:

(termite:12364): Vte-WARNING **: (vtegtk.cc:1718):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

all packages are up to date.

**Comment by jelly** [comment]
Has been fixed in Git be3eec81c01105dc947725e251d1f68844b0d37e but not included in a release yet. And currently I don't want to release anything till the configure keybindings issue is resolved.
