### ISSUE TITLE
Handle filesystem URLs

### ISSUE THREAD

**Issue by ppwwyyxx** [thestinger/termite#391]
It would be nice if termite could recognize filesystem URLs, such as:
`filesystem:http://example.com/temporary/lolcat.png`.
See: https://developer.mozilla.org/en-US/docs/Web/API/Entry#toURL

**Comment by jelly** [comment]
filesystem: sounds like something non-standard. I'd expect it to be file://// which for example GIT can handle.

Not sure what the use-case would be here.

**Comment by jelly** [comment]
Another argument for not implementing it iis that it's not even a standard:
```
This feature is non-standard and is not on a standards track. 
Do not use it on production sites facing the Web: it will not work for every user.
There may also be large incompatibilities between implementations and the behavior 
may change in the future.
```
