### ISSUE TITLE
Don't overwrite existing config files

### ISSUE THREAD

**Issue by skosch** [thestinger/termite#393]
I just had to re-compile and -install termite after a system upgrade, and `make install` just overwrote my beloved `config` with the default. And of course I'd never made a backup :sweat: 

It'd be nice if the `install` target could ask whether or not the existing file should be overwritten. Alternatively, if the old `config` were copied to `config_old_{timestamp}` or similar before installing the default, that would solve the problem too.

**Comment by jelly** [comment]
termite does not the config file in your $HOME which is the recommended place where your config should be.

Marking it as a config however should be packaging job (rpm, deb or pkg.tar.xz). Ideally you should't use make install at all and use a packaged version.

**Comment by skosch** [comment]
Ah, I missed that. We can probably close this then. Lesson learned, I suppose ... but thanks for the quick response!
