### ISSUE TITLE
Weird Colors

### ISSUE THREAD

**Issue by pedrocunial** [thestinger/termite#394]
Hey there, I've been using termite for a while but the colorscheme has always been different then what it is supposed to be. Here is a screenshot of what I'm talking about (in comparison to gnome terminal)

![screenshot from 2016-09-20 08-33-19](https://cloud.githubusercontent.com/assets/11504078/18668685/2741404c-7f0d-11e6-95b4-206c9bfd01e5.png)

**Comment by thestinger** [comment]
There isn't an indication that this is a bug rather than a configuration error you've made.
