### ISSUE TITLE
Can't start certain applications

### ISSUE THREAD

**Issue by rightaway** [thestinger/termite#397]
When I run `termite -e 'tmuxinator start myconfig'`, nothing happens. I'd like termite to start with that tmuxinator config. If I run just `tmuxinator start myconfig` on the command line it works, however.

Or if I run it within urxvt as `urxvt -e bash -c "tmuxinator start myconfig"` (from https://wiki.archlinux.org/index.php/tmux#Start_tmux_in_urxvt), it works too. I tried the equivalent with termite, `termite -e bash -c "tmuxinator start myconfig"`, but that also doesn't work.

**Comment by thestinger** [comment]
The `-e` parameter in Termite takes one argument, like a normal switch.

**Comment by thestinger** [comment]
i.e. you need to quote stuff properly, it's not a magical option eating up all of the remaining output with custom semantics.
