### ISSUE TITLE
Option to run as login shell

### ISSUE THREAD

**Issue by ZeroKnight** [thestinger/termite#399]
Most terminal emulators have an option that toggles whether or not to start the shell as a login shell. Unless I'm missing something, Termite doesn't seem to be able to implicitly launch a login shell. I know you could do: `termite -e '/usr/bin/zsh -l'`, but that's a bit cumbersome.

**Comment by thestinger** [comment]
Why?

**Comment by ZeroKnight** [comment]
>Why?

Why not?

Now an actual response: so that shell startup files that only launch on login shells are actually run, eg. .zprofile, .zlogin, <insert *sh equivalents here>

**Comment by thestinger** [comment]
A login shell is supposed to run when you log in, not when you start an application like Termite. People correctly put things in those like modifications to PATH that are supposed to apply to their whole session, not only terminal emulators.

**Comment by thestinger** [comment]
> Why not?

I'm not willing to implement workarounds for stuff that is meant to be handled elsewhere. Display managers should be able to run a login shell, and most can probably already be configured to do so.

**Comment by ZeroKnight** [comment]
While I agree with you, it is also convenient to be able to apply and use changes to those files without restarting the entire session, like updating $PATH or $FPATH for example.

**Comment by thestinger** [comment]
Login shells are not meant to be run nested inside each other though. Most modifications to PATH will append/prepend to it, so they won't actually update PATH but rather will extend it further which won't necessarily work and is ugly / slow.

**Comment by madalinignisca** [comment]
With this decision you just made termite not being able to use it for RVM or other runtime clones of RVM.

**Comment by thestinger** [comment]
> With this decision you just made termite not being able to use it for RVM or other runtime clones of RVM.
> It forces the user to find workarounds to get RVM working as expected for any Ruby developer.

That's not true. You haven't set it up properly.

> Actually I think you have done same thing like it happened to you, when you have been refused with a nice patch in VTE. Karma.

I don't see any patch, only a misunderstanding of how things are meant to be done.

**Comment by thestinger** [comment]
I suggest reading my comments above where you can find the proper solution: a login shell should be run a single time as part of starting sessions. They aren't support to be nested. When you add something like `export PATH="$PATH:$HOME/.local/bin"` to `.bash_profile` that's only meant to run a single time upon logging in and should not only be available within terminals started with login shells. Running a terminal is not logging in. It is *wrong* and the decision was made to handle things like this properly. The same goes for URL matching and terminfo.

The project doesn't currently have a maintainer/developer so there is no forward progress despite lots of wanted improvements. Things like this are meant to be the way they are. It's expected that the distribution or system administrator sets things up properly. It's unreasonable to add ugly hacks like this to work around broken distributions / environments. A login shell should run as part of logging in, one time, without nesting. That's important.

**Comment by thestinger** [comment]
Aren't you concerned about your changes to the environment not being picked up without the terminal hacking around it?

**Comment by thestinger** [comment]
i.e. none of it applies outside of the terminal applying the hack... which is broken.
