### ISSUE TITLE
Vte-WARNING and Gregex errors

### ISSUE THREAD

**Issue by cjmccormick** [thestinger/termite#404]
get these errors while trying to start termite in i3:

(termite:13954): Vte-WARNING **: (vtegtk.cc:1718):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

first time I got it, im not sure how to fix.

**Comment by polyzen** [comment]
be3eec8

Updated to version 12?

**Comment by cjmccormick** [comment]
Yes I have v11

**Comment by polyzen** [comment]
Update to 12.

**Comment by cjmccormick** [comment]
ahh, that did the job :dancer:

**Comment by polyzen** [comment]
Please close this when you get a chance.
