### ISSUE TITLE
Ctrl + Shit + Space closing termite window

### ISSUE THREAD

**Issue by CrashyBang** [thestinger/termite#406]
Running on Ubuntu 16.04 when I use the `Ctrl` + `Shift` + `Space` combo to enter visual mode the terminal window closes.

Cheers.

**Comment by kyrias** [comment]
That's not very helpful for debugging it.  What's the exit code, does it print anything before exiting?

**Comment by CrashyBang** [comment]
Hey @kyrias,

Point taken, ran termite from `gnome-terminal` so I could get a bit more info, so when enter the `Ctrl` + `Shift` + `Space` sequence I received the following error:

```
termite: symbol lookup error: termite: undefined symbol: vte_terminal_disconnect_pty_read
```

Let me know if I can do anything else.

Cheers.

**Comment by thestinger** [comment]
You need vte-ng.

**Comment by CrashyBang** [comment]
Hey @thestinger I have installed that, after looking at this [issue](https://github.com/thestinger/termite/issues/140) is there something special I need to do to add to my `PATH`?

**Comment by thestinger** [comment]
It doesn't go in your `PATH`. Follow the instructions there.

**Comment by CrashyBang** [comment]
Hey @thestinger sorry I am a little new to this stuff I got it working by adding the directory where the `vte-ng` files were to my `PATH` and running `ldconfig` but I take it from your above comment this is not a good way to do this?

In regards to following the instructions on the other issue I am having trouble with this line: _add the directory to `/etc/ld.so.conf.d/vte.conf`_ by add do you mean something like a symlink? i.e.:

```bash
ln -s /Path/to/vte-ng /etc/ld.so.conf.d/vte.conf
```

Sorry for the newbie question.

**Comment by thestinger** [comment]
`PATH` is for executables, not libraries.

**Comment by CrashyBang** [comment]
@thestinger okay thank you I didn't know that, with that in mind should I be using the above symlink?

**Comment by thestinger** [comment]
ld.so.conf.d is a directory of files containing paths on each line. It defaults to installing to /usr/local/lib which should be in your path already though. You need to remove vte as in non-vte-ng.
