### ISSUE TITLE
Some colors display wrong after vte3-ng update

### ISSUE THREAD

**Issue by Brottweiler** [thestinger/termite#407]
Ran system update on Archlinux today;

```sh
[2016-10-12 12:28] [ALPM] upgraded vte-common (0.44.2-1 -> 0.46.0+5+g398a3f8-1)
[2016-10-12 12:28] [ALPM] upgraded vte3-ng (0.44.2.a-1 -> 0.46.0.a-1)
```

and now it seems that some colors in Termite show wrong. It seems like they show much brighter than what they should be.

Image example:

![](https://i.imgur.com/c7rMUij.png)

I am using base16-google-dark theme, and it seems like the issue might be that half of the colors are ignored. If you look at the pacman and spaceinvador colortest in the above image, the top and bottom rows of the pacmans and aliens should be same color. This is my termite colors:

```cfg
[colors]
cursor = #c5c8c6
#cursor_foreground = #dcdccc
foreground = #c5c8c6
foreground_bold = #c5c8c6
background = #1d1f21

# 20% background transparency (requires a compositor)
background = rgba(29, 31, 33, 0.95)

# if unset, will reverse foreground and background
# highlight = #2f2f2f

# colors from color0 to color254 can be set
color0 = #1d1f21
color1 = #cc342b
color2 = #198844
color3 = #fba922
color4 = #3971ed
color5 = #a36ac7
color6 = #3971ed
color7 = #c5c8c6
color8 = #969896
color9 = #cc342b
color10 = #198844
color11 = #fba922
color12 = #3971ed
color13 = #a36ac7
color14 = #3971ed
color15 = #ffffff
```

This may or may not be termite or vte3-ng bug, but making the issue here because it's related to termite.

**Comment by jelly** [comment]
Report the termite version, it should be v12.

**Comment by Brottweiler** [comment]
@jelly Ah, yes! I was apparently using an older version (git version that I hadn't updated), sorry for the trouble, and thanks for quick reply!
