### ISSUE TITLE
Font is messed up in pulsemixer

### ISSUE THREAD

**Issue by poisonby** [thestinger/termite#408]
I'm not sure where the problem originates from, but I'm starting with Termite (since that's what's running pulsemixer, and other terminals don't have this problem).

**Screenshot of the problem:**
![screenshot](https://ptpb.pw/PZiq.png)

**How it looks in urxvt:**
![screenshot2](https://ptpb.pw/0uqW)

This may have happened after I upgraded my system (I'm not 100% sure). I've tried downgrading `termite`, `termite-terminfo`, `vte-common` and `vte3-ng`. That didn't help.

**Version:**

12-1

**Comment by RunningDroid** [comment]
Are you using the same font in both terminals?

**Comment by poisonby** [comment]
@RunningDroid

Yes, Inconsolata.

**Comment by jelly** [comment]
pulsemixer gave me different funky displays for rxvt and termite with terminus. Also SourceCodePro gives me varied results.

I don't see how this is a termite bug

**Comment by kyrias** [comment]
Inconsolata does not have the `black large square` glyph, so it's falling back to another font with it, and something caused the fallback to change.  Could you pastebin your pacman log?

Anyway, the rendering bug itself is weird...

**Comment by poisonby** [comment]
@jelly
It may very well not be, I just didn't know where else to start since it's worked perfectly with termite thus far. If you insist that this is not a problem with termite, I wouldn't mind closing the issue.

@kyrias
Sure, [here](https://ptpb.pw/lOWo) you go. I realized that I had installed a new font recently (junicode), but removing it and running `fc-cache` doesn't seem to fix it. Maybe whatever change it did was persistent?

Thanks.

**Comment by poisonby** [comment]
Closing this since it's likely not an issue with termite.

**Comment by kyrias** [comment]
For future reference at the very least, it seems the line overflow bug exists in both vte and vte3 terminals. Really fucking weird.

**Comment by kyrias** [comment]
Apparently it's a glib2 bug introduced when updating their Unicode data tables..

**Comment by cwegener** [comment]
Thanks +kyrias for pointing to the upstream bug. I had the same issue in many apps (tmux, vim) in termite when glib2 update came out this month.

**Comment by cwegener** [comment]
Reading GNOME developer comments on their bugtracker makes so angry again.
https://bugzilla.gnome.org/show_bug.cgi?id=772890

**Comment by kyrias** [comment]
That's GNOME for you…
