### ISSUE TITLE
Keybindings for font size not always working

### ISSUE THREAD

**Issue by kohlerm** [thestinger/termite#409]
I use GDM to either login into a Gnome desktop or an i3 desktop. I both cases the keybindings for changing the font size only work if I select an "en" keyboard on the login screen.
E.g if I switch to en later on the desktop it also doesn't work. It never works if I set the keyboard to "de". 

Other keybindings seem to work fine. 
Any suggestions how to debug this?

**Comment by jelly** [comment]
Which termite version do you use? The keybindings changed to crtl+shift+"+" and ctrl+"-" in termite v12.

And this commit was made to fix it for ea0bc59e38301471ad619b252782bdf4c34f6a35 other keyboard layouts.

**Comment by kohlerm** [comment]
I had compiled it from HEAD. Just updated to HEAD again and recompiled it. Works  better. 
As I said it is working  fine with the keybindings you mention with us(en) keyboard setting. 
Ctrl + now increases the font. 
Ctrl shift = works, = requires shift anyway on the de keyboard. 
Ctrl - works 

so I guess this is how it should behave, thanks!
