### ISSUE TITLE
Font rendering issues in termite

### ISSUE THREAD

**Issue by CrashyBang** [thestinger/termite#410]
So I am trying out the new Operator Mono font and using the same font in both gnome terminal and termite I am getting quite different results, termite fonts are thicker.

Gnome above termite below:

![onpaste 20161014-222845](https://cloud.githubusercontent.com/assets/2978850/19382710/e0641b40-925d-11e6-9074-c636c76e4574.png)

Is this vte related (related to #84)?

Cheers.

**Comment by thestinger** [comment]
Looks like a configuration error to me, not a Termite issue. Font rendering is identical to gnome-terminal with the same VTE version.

**Comment by CrashyBang** [comment]
Hey @thestinger made sure both emulators were using the same VTE version and I am still experiencing the same issue (gnome on the left termite on the right):

![onpaste 20161015-153521](https://cloud.githubusercontent.com/assets/2978850/19406920/31779798-92ed-11e6-8fbd-c3d44bac4686.png)

Thoughts?

**Comment by thestinger** [comment]
Configuration issue. You have a different font variant set up in each one.

**Comment by CrashyBang** [comment]
I have like triple checked the fonts but just to make 100% sure here is my [termite config](https://github.com/CrashyBang/dotfiles/blob/master/.config/termite/config).

```
[options]
font = Operator Mono Medium 15
```

And here is a screen shot of my gnome terminal font settings:

![onpaste 20161015-212416](https://cloud.githubusercontent.com/assets/2978850/19408591/c4538c22-931d-11e6-9891-656ea0fa1859.png)

If it is just something I have misunderstood with the termite `font` config option that would be great.

**Comment by terlar** [comment]
Perhaps you need to quote your font? Another option is to configure it in font-config globally as monospace and then just refer to `monospace` in the termite config.

**Comment by CrashyBang** [comment]
Hey @terlar quoting broke completely I tried:

```
[options]
font = 'Operator Mono Medium 15'
```

and

```
[options]
font = 'Operator Mono Medium' 15
```

Setting the system font and then using:

```[options]
font = monospace 
```

Does not seem to work either (have tried `monospace` with a little `m` and `M`), I am setting the system font via `gsettings` and if I run: `gsettings get org.gnome.desktop.interface monospace-font-name` the return value is: `'Operator Mono Medium 15'` so I am pretty sure I am doing this right.

**Comment by CrashyBang** [comment]
Okay I figured it out using a mixture of `unity-tweak-tool` and `gsettings` so it turns out that setting the font to `Operator Mono Medium 15` in `unity-tweak-tool` and then printing the font name using: `gsettings get org.gnome.desktop.interface monospace-font-name` actually returned `'Operator Mono Semi-Light 15'` so the label in the GUI did not actually match the font name.

After that it all came together really easily hopefully anybody with this issue will be able to use a similar technique to debug the issue.

Setting the font to `Operator Mono Semi-Light 15` works perfectly, cheers @thestinger & @terlar for the help.

**Comment by hobarrera** [comment]
Wow, *big thanks* to everyone who contributed to working around this, and to @CrashyBang for the final clear explanation. After hours of banging my head thinking fontconfig was broken, and dozens of dead ends, this finally worked!
