### ISSUE TITLE
Support for RTL langauges

### ISSUE THREAD

**Issue by eyadsibai** [thestinger/termite#411]
I am big fan of termite terminal, but unfortunately it doesn't support rtl languages. Sometimes it is necessary to show some text in these languages.

**Comment by jelly** [comment]
I'm not sure how this is supposed to work, but for gnome-terminal which also uses vte3 the solution seems to be the following: https://gist.github.com/IslamAzab/49428f09cffc4f453be9

**Comment by eyadsibai** [comment]
unfortunately I am not expert when it comes to terminal development... but I saw that many are using this package gnu fribidi

**Comment by thestinger** [comment]
There's no indication of a bug or missing feature right now.

**Comment by eyadsibai** [comment]
Support RTL in the output is a feature

**Comment by thestinger** [comment]
It's not supported by VTE so there's nothing for Termite to expose. Use the solution posted at https://gist.github.com/IslamAzab/49428f09cffc4f453be9.

**Comment by osleg** [comment]
So the solution is to use gnome-terminal?

**Comment by thestinger** [comment]
No, use the approach there with Termite.

**Comment by jelly** [comment]
@osleg I don't think that it supports RTL...
