### ISSUE TITLE
man 5 termite.config does not state default values of options

### ISSUE THREAD

**Issue by cmcaine** [thestinger/termite#412]
`man 1 termite` should probably explicitly state that termite only processes the first config file it finds, too.

**Comment by polyzen** [comment]
Feel free to send a pull request.

**Comment by cmcaine** [comment]
Alright.

My understanding is that this section (around line 1370) is the relevant bit of the source:
````
    auto cfg_bool = [config](const char *key, gboolean value) {
        return get_config<gboolean>(g_key_file_get_boolean,
                                    config, "options", key).get_value_or(value);
    };

    vte_terminal_set_scroll_on_output(vte, cfg_bool("scroll_on_output", FALSE));
    vte_terminal_set_scroll_on_keystroke(vte, cfg_bool("scroll_on_keystroke", TRUE));
    vte_terminal_set_audible_bell(vte, cfg_bool("audible_bell", FALSE));
    vte_terminal_set_mouse_autohide(vte, cfg_bool("mouse_autohide", FALSE));
    vte_terminal_set_allow_bold(vte, cfg_bool("allow_bold", TRUE));
    vte_terminal_search_set_wrap_around(vte, cfg_bool("search_wrap", TRUE));
    info->dynamic_title = cfg_bool("dynamic_title", TRUE);
    info->urgent_on_bell = cfg_bool("urgent_on_bell", TRUE);
    info->clickable_url = cfg_bool("clickable_url", TRUE);
    info->size_hints = cfg_bool("size_hints", FALSE);
    info->filter_unmatched_urls = cfg_bool("filter_unmatched_urls", TRUE);
    info->modify_other_keys = cfg_bool("modify_other_keys", FALSE);
    info->fullscreen = cfg_bool("fullscreen", TRUE);
    info->font_scale = vte_terminal_get_font_scale(vte);
````

And the final all caps values are the defaults for the options.

Can you confirm?

**Comment by polyzen** [comment]
They're all there -- starting at line 1372.

**Comment by polyzen** [comment]
> man 1 termite should probably explicitly state that termite only processes the first config file it finds, too.

It appears to imply this: `termite looks for the configuration file in the following order:`

**Comment by cmcaine** [comment]
Thanks for the confirmation. I'll work up a pull request in some spare time this week.

**Comment by polyzen** [comment]
[This commit](https://github.com/thestinger/termite/pull/426/commits/dc5ec76830161e05b3781c4b8aabbde8a2a72d5a) may help. `font` and `scrollback_lines` and (maybe all of) the remaining color options are sensible (not hard-coded) defaults. Some of the options under [hints] are also not defaults.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
