### ISSUE TITLE
F19 key generate '^[[33~' rather than '^[[18;2~'

### ISSUE THREAD

**Issue by leira** [thestinger/termite#414]
On my mac, I mapped Caps Lock to F19, and used it as a dedicated tmux prefix key with setting

```
set-option -g prefix S-F7
```

I recently setup an arch linux box,  I mapped Caps Lock to F19 using xmodmap, and want to using tmux in termite with the same setting. But when I press F19 key in tmux, it simply print '[33~', rather than take it as prefix. Shift F7 works, though.

On Mac, $TERM is xterm-256color outside of tmux, and screen-256color inside tmux.

On LInux, in termite, $TERM is xterm-termite outside of tmux, and tmux-256color inside tmux.

I ran sed -n l on Mac, F19 and Shift-F7 print the same output ^[[18;2~.

``` fish
mac ~> sed -n l
^[[18;2~
\033[18;2~$
^[[18;2~
\033[18;2~$
^C⏎ 
```

While on Linux inside termite without tmux, F19 and Shift-F7 print differently. F19 prints out ^[[33~. Shift-F7 prints out ^[[18;2~.

``` fish
~> sed -n l
^[[33~
\033[33~$
^[[18;2~
\033[18;2~$
^C⏎
```

I checked output of infocmp, kf19 should be mapped to \E[18;2~, but why termite gave me \E[33~ when I press F19?

``` fish
~> infocmp
#   Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm-termite
xterm-termite|VTE-based terminal,
...
    kf18=\E[17;2~, kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~,
    kf21=\E[20;2~, kf22=\E[21;2~, kf23=\E[23;2~,
...
```

**Comment by egmontkob** [comment]
The escape sequences are hardwired in `vte` (the terminal emulation widget behind termite), technically independently from the terminfo description. Of course ideally they should match :)

I don't know why it works this way, but this also works this way in `xterm`, and `xterm` and `terminfo` are maintained by the same guy. I think you should contact him and ask him why this is the case.

`vte` aims to follow `xterm` as the reference, and at this point it does this correctly. In case you encounter a similar mismatch between `xterm` and `vte` (e.g. `termite`), please file a bug in mainstream `vte`'s bugzilla.

**Comment by leira** [comment]
I opened a bug with vte (https://bugzilla.gnome.org/show_bug.cgi?id=773444) too, and @egmontkob kindly responded on it too. And I do agree with his opinion that:

> Note: the current escape sequences allow an app to differentiate all of F7, F9, F19, Shift+F7, Shift+F9, Shift+F19 and so on from each other. In your proposed one F19 would generate the same as Shift+F7. As such, I believe the current behavior is the better one

I continued the discussion on the tmux issue (https://github.com/tmux/tmux/issues/536), just keep it here as a reference.
