### ISSUE TITLE
Can I launch vim with termite without loose vim ctrl-* shortcut ?

### ISSUE THREAD

**Issue by tyjak** [thestinger/termite#415]
Hello,
Termite is awesome but when I launch vim I can't use vim block selection it seem's termite has priority on Ctrl key and nothing goes to vim. Is this a known issue ? (I found nothing about it, and notify I don't want to use gvim)

Thank you for your support.

**Comment by wsdjeg** [comment]
which key do you type？I do not get this issue.

**Comment by thestinger** [comment]
It works fine here.
