### ISSUE TITLE
[RFE] copy url in url-copy-mode instead of opening it

### ISSUE THREAD

**Issue by shibumi** [thestinger/termite#417]
Hello,
I would like to copy the url only instead of opening it when I am in url selection mode. Is this possible? if not can you implement it?

**Comment by acidrain42** [comment]
You can already do that with a right-click

**Comment by shibumi** [comment]
Is there also a way without mouse? with shortcuts only?

**Comment by jelly** [comment]
It could be implemented as a ctrl+shift+Z key since it can't conflict with other existing key shortcuts. Or it can be made a config option but that would be a weird I'd say.

**Comment by amosbird** [comment]
+1, a nice feature to have.

**Comment by alex3kov** [comment]
+1, would be awesome to have this - e. g. for copying URLs of media files to download with wget. Currently to download media files I have to do `ctrl-shift-x` -> it opens in browser -> `ctrl-l` -> `ctrl-C` -> back to terminal -> wget `ctrl-shift-v`. Tons of key presses.

**Comment by jelly** [comment]
Ok, so btw, ctrl+shift+space and then U allows you to yank an url.

**Comment by alex3kov** [comment]
@jelly That's pretty good, thanks. Doesn't work very well when there are a lot of links on the screen though - need to cycle through them to get to the one you need. Sometimes it's 1 key press, sometimes 20. `ctrl-shift-x` on the other hand is always at most 2 key presses.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
