### ISSUE TITLE
Documentation on setting colours

### ISSUE THREAD

**Issue by silasdavis** [thestinger/termite#418]
It would be nice to include some documentation on how to set terminal colours. In my case I'd like to recreate my urxvt colour theme. I have the following Xresources set:

```
*background:              S_base03
*foreground:              S_base0
*fading:                  40
*fadeColor:               S_base03
*cursorColor:             S_base1
*pointerColorBackground:  S_base01
*pointerColorForeground:  S_base1

*color0:                  S_base02
*color1:                  S_red
*color2:                  S_green
*color3:                  S_yellow
*color4:                  S_blue
*color5:                  S_magenta
*color6:                  S_cyan
*color7:                  S_base2
*color9:                  S_orange
*color8:                  S_base03
*color10:                 S_base01
*color11:                 S_base00
*color12:                 S_base0
*color13:                 S_violet
*color14:                 S_base1
*color15:                 S_base3
```

I've managed to replicate foreground and background colours by setting in `~/.config/termite/config`:

```
[colors]
foreground = #839496
background = #002b36
```

Are there any other colors I can set.

I'd also like to know if it's possible to set my colours in `~/.config/gtk-3.0/gtk.css`, that way I can centralise my colour preferences by defining css variables.

Thanks for the terminal!

**Comment by silasdavis** [comment]
Having read the source code, the following works when added to `~/.config/termite/config`:

```
[colors]
foreground = #839496
background = #002b36
color0 = #073642
color1 = #dc322f
color2 = #859900
color3 = #b58900
color4 = #268bd2
color5 = #d33682
color6 = #2aa198
color7 = #eee8d5
color9 = #cb4b16
color8 = #002b36
color10 = #586e75
color11 = #657b83
color12 = #839496
color13 = #6c71c4
color14 = #93a1a1
color15 = #fdf6e3
```

(Solarized dark colours for any internet wanderers finding this).

Would still be nice to set them via CSS, not sure if this is possible though.

**Comment by jelly** [comment]
Colors are already pretty straightforward and resources such as http://terminal.sexy/ can be used to generate color schemes
