### ISSUE TITLE
Allow shift + selection to automatically copy selection to clipboard

### ISSUE THREAD

**Issue by rightaway** [thestinger/termite#421]
One feature I got very used to while working with some past terminals (`urxvt`, not sure if plain or with some plugins) was when I made a selection, which is done using `shift`, whatever has been selected would automatically be copied to the clipboard and could be pasted elsewhere on the system with `ctrl-v` or in termite with `shift-ctrl-v`.

It's such a common action that this would save a lot of keystrokes, and it's a very pleasant experience that you really miss after having gotten used to it. Even months after switching to termite I still find myself thinking text was copied this way, only to have to switch back to termite, re-select the text, and type `ctrl-shift-c`.

I think it's a great feature to enable by default, but if people are really opposed to it maybe making it possible to disable with a config option?

**Comment by thestinger** [comment]
Termite does automatically set the PRIMARY clipboard to the selected text.

**Comment by rightaway** [comment]
I mean setting it to the system clipboard in addition to the primary selection. The primary selection gets overwritten way too easily by even an accidental text selection in any program to be useful.
