### ISSUE TITLE
Make it possible to map shift-space

### ISSUE THREAD

**Issue by rightaway** [thestinger/termite#422]
In a question about allowing `shift-space` to work as `pageup` in various programs, like `less` (http://unix.stackexchange.com/questions/88579/shift-space-in-less/88592#88592), the answer says

> Since Shift+Space generates the same output as Space, the Unix terminal model treats them identically. To distinguish between the two, you need a programming environment that supports key up / key down events. That is possible in X11 and in terminal emulators that support remapping keys. An example of remapping Shift+Space to PageUp:

```
# For [u]rxvt, in ~/.Xdefaults:
URxvt.keysym.Shift-space: \033[5~
```

The above is an example for `urxvt`. It would be useful if there were an equivalent in termite.

**Comment by egmontkob** [comment]
Termite uses the VTE widget for terminal emulation, and VTE does not allow to remapping the keys at all.

That being said, Terminator might catch Shift+Space as a shortcut key before it arrives at VTE, and feed to VTE PageUp's escape sequence instead, which is effectively the same.

One thing I'm not sure you've thought of: This feature would break typing uppercase text with embedded spaces by holding down Shift. E.g. if you wanted to type "It's A Title", you'd have to release Shift between "A" and "T". Keeping it pressed would move away your cursor and misposition the rest of what you type. I believe it would be way more annoying than what you gain with the scroll up feature.

Having the regular behavior when typing text, and scrolling up whenever Space scrolls down would require a redesign and heavy cooperation from apps (e.g. an app being able to toggle what Shift+Space sends), I'm pretty certain it's not going to happen.

**Comment by thestinger** [comment]
I don't want to do this.
