### ISSUE TITLE
Problems with powerline and similar statusline configurations in tmux

### ISSUE THREAD

**Issue by wbthomason** [thestinger/termite#423]
**Symptoms:** `tmux` statusline flickers in and out, elements are misaligned, and the statusline appears to shift up the screen.

**Steps to reproduce:** Fresh install of `termite`, fresh install of `tmux`, fresh install of `powerline` or [gpakosz/.tmux](https://github.com/gpakosz/.tmux). Enable either `powerline` or @gpakosz's .tmux in `.tmux.conf`. Start `tmux` in `termite`.

**System parameters:** Arch Linux, `termite` v12, `tmux` v2.3. TERM=xterm-termite outside of `tmux` and screen-256color inside of `tmux`.

**Further info:** This thread: https://github.com/gpakosz/.tmux/issues/32

I haven't had a chance to read through `termite`'s source yet, but will try to do so and report any possible causes I find.

**Comment by thestinger** [comment]
This is a VTE issue. Termite isn't responsible for terminal emulation.

**Comment by wbthomason** [comment]
Alright, thanks for the clarification!
