### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by JackHobson** [thestinger/termite#425]
When I run make my prompt spits out this:

`g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v12-4-g7930760\" -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/vte-2.91   -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -o termite
termite.cc: In function ‘void update_selection(VteTerminal*, const select_info*)’:
termite.cc:443:85: error: ‘vte_terminal_set_selection_block_mode’ was not declared in this scope
     vte_terminal_set_selection_block_mode(vte, select->mode == vi_mode::visual_block);
                                                                                     ^
termite.cc:450:60: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      cursor_col, cursor_row);
                                                            ^
termite.cc:453:74: error: ‘vte_terminal_select_text’ was not declared in this scope
                                      select->begin_col, select->begin_row);
                                                                          ^
termite.cc:459:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc:465:73: error: ‘vte_terminal_select_text’ was not declared in this scope
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc: In function ‘void enter_command_mode(VteTerminal*, select_info*)’:
termite.cc:472:41: error: ‘vte_terminal_disconnect_pty_read’ was not declared in this scope
     vte_terminal_disconnect_pty_read(vte);
                                         ^
termite.cc: In function ‘void exit_command_mode(VteTerminal*, select_info*)’:
termite.cc:479:81: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, select->origin_col, select->origin_row);
                                                                                 ^
termite.cc:480:38: error: ‘vte_terminal_connect_pty_read’ was not declared in this scope
     vte_terminal_connect_pty_read(vte);
                                      ^
termite.cc: In function ‘void move(VteTerminal*, select_info*, long int, long int)’:
termite.cc:532:92: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
                                      clamp(cursor_row + row, first_row(vte), last_row(vte)));
                                                                                            ^
termite.cc: In function ‘void move_to_row_start(VteTerminal*, select_info*, long int)’:
termite.cc:540:49: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, 0, row);
                                                 ^
termite.cc: In function ‘void open_selection(char*, VteTerminal*)’:
termite.cc:547:68: error: ‘vte_terminal_get_selection’ was not declared in this scope
         auto selection = make_unique(vte_terminal_get_selection(vte), g_free);
                                                                    ^
termite.cc: In function ‘void move_backward(VteTerminal*, select_info*, F)’:
termite.cc:599:65: error: there are no arguments to ‘vte_terminal_set_cursor_position’ that depend on a template parameter, so a declaration of ‘vte_terminal_set_cursor_position’ must be available [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc:599:65: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
termite.cc: In function ‘void set_cursor_column(VteTerminal*, const select_info*, long int)’:
termite.cc:645:61: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, column, cursor_row);
                                                             ^
termite.cc: In function ‘void move_forward(VteTerminal*, select_info*, F)’:
termite.cc:711:65: error: there are no arguments to ‘vte_terminal_set_cursor_position’ that depend on a template parameter, so a declaration of ‘vte_terminal_set_cursor_position’ must be available [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In function ‘void load_theme(GtkWindow*, VteTerminal*, GKeyFile*, hint_info&)’:
termite.cc:1320:62: error: ‘vte_terminal_set_color_cursor_foreground’ was not declared in this scope
         vte_terminal_set_color_cursor_foreground(vte, &*color);
                                                              ^
termite.cc: In instantiation of ‘void move_backward(VteTerminal*, select_info*, F) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]’:
termite.cc:606:44:   required from here
termite.cc:599:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In instantiation of ‘void move_backward(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:610:70:   required from here
termite.cc:599:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
termite.cc: In instantiation of ‘void move_forward(VteTerminal*, select_info*, F) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]’:
termite.cc:718:43:   required from here
termite.cc:711:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In instantiation of ‘void move_forward(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:722:69:   required from here
termite.cc:711:65: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
termite.cc: In instantiation of ‘void move_first(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]’:
termite.cc:859:86:   required from here
termite.cc:635:76: error: ‘vte_terminal_set_cursor_position’ was not declared in this scope
         vte_terminal_set_cursor_position(vte, iter - codepoints, cursor_row);
                                                                            ^
Makefile:36: recipe for target 'termite' failed
make: *** [termite] Error 1`

I'm running Debian 8.6 Jessie and I'm trying to compile version 12.

**Comment by polyzen** [comment]
I imagine you need to [install vte-ng](https://github.com/thestinger/termite/pull/416)?

**Comment by jelly** [comment]
Not a bug, you are not using vte3-ng
