### ISSUE TITLE
typing errors in ubuntu 16.04

### ISSUE THREAD

**Issue by harsha003** [thestinger/termite#428]
hello. I am new to linux and wanted to install termite. So I did the install with all the dependencies and got this:
![out](https://cloud.githubusercontent.com/assets/18393803/20645539/7485e31c-b487-11e6-8e1a-fb13786647ef.gif)
Is there any way to fix this?

**Comment by egmontkob** [comment]
How do other terminal emulators (e.g. xterm) behave? I suspect it's a problem with your zsh.

**Comment by harsha003** [comment]
no worries a clean install of the OS solved this.By the way, it wasn't a problem with zsh. It was only for termite.
