### ISSUE TITLE
Feature Request: source files in termite.cfg

### ISSUE THREAD

**Issue by adskankster** [thestinger/termite#43]
Changing colour schemes could be a hassle having to change all colours in one go.
Would it be possible to source separate sub files? That way several colourschemes could be defined and changing from one to the other would be a case of (un)commenting the appropriate lines.

Thanks.

**Comment by thestinger** [comment]
Not interested in supporting this. More flexible configuration, sure, but not like this.

**Comment by jck** [comment]
What do you mean by 'more flexible configuration'?

**Comment by thestinger** [comment]
I'm just stating that I'm open to other ideas on how to improve it, but not this. It's too complex.

**Comment by marcospb19** [comment]
I made a [fork](https://github.com/marcospb19/termite) with a solution for this.
