### ISSUE TITLE
Unsetting Bold and Hidden color format doesn't work

### ISSUE THREAD

**Issue by gunar** [thestinger/termite#432]
> Note: As explained by @egmontkob the "unbold" code works properly. I had the code wrong. It's 22 not 21. However, the "unhidden" still does not work.

---

#### How to reproduce it
```
echo -e "Normal \e[1mBold \e[21mNormal"
echo -e "Normal \e[8mHidden \e[28mNormal"
```
#### Expected
![bold](http://misc.flogisoft.com/_media/bash/colors_format/vt100_format_21_reset_bright.png)
![hidden](http://misc.flogisoft.com/_media/bash/colors_format/vt100_format_28_reset_hidden.png)

#### Actual
![image](https://cloud.githubusercontent.com/assets/7684574/21198300/e6239bc6-c225-11e6-9084-9d3b49a7033a.png)

I'm on:
- termite v12
- zsh 5.2 (x86_64-unknown-linux-gnu)

Thanks for this awesome terminal emulator!!

**Comment by egmontkob** [comment]
Newest vte versions definitely get it right, 28 disables the hidden attribute. Not sure about termite versions, I guess v12 uses an older vte.

Type

    echo -ne '\e[>c'

to figure out your vte version (the middle four digits which are injected as if you typed them).

By the way, 21 is not supposed to disable bold as per http://invisible-island.net/xterm/ctlseqs/ctlseqs.html, it's supposed to enable double underline which is not supported by vte. The comment in vteseq.cc says "Error in old versions of linux console", so it's deliberately emulating this error of linux of disabling bold. You should instead use 22 if you expect your code to work in other emulators as well.

**Comment by gunar** [comment]
@egmontkob you are right. 22 disables bold. that works. that is a non-bug. thanks!

However, the hidden attribute is still causing me trouble.

FYI by typing `echo -ne '\e[>c'` I get `84;0;0c`. Also, I'm on `termite -v`: `termite v12`.

**Comment by egmontkob** [comment]
Neither the behavior you describe matches vte's (vte is the widget doing the actual terminal emulation in termite), nor does the response '84;0;0', it should be something like '1;4601;0' (for vte-0.46.01, similarly for other vte version).

I bet you're using tmux, correct? If so, this bugreport belongs to tmux, that's the layer messing with you.

**Comment by gunar** [comment]
@egmontkob you're right. thank you so much!! :heart:
