### ISSUE TITLE
Commands don't take inputs

### ISSUE THREAD

**Issue by preciz** [thestinger/termite#435]
I just installed i3 (manjaro) and installed termite version v12.

I would like to use the `git add --patch` command, but it exits immediately, and doesn't take my inputs therefore. I don't experience the same issue with the default i3 terminal urxvt, that is why I think it might be a related to termite.

How could I debug this issue?

**Comment by jelly** [comment]
It works for me, it sounds more like an shell bug then a termite one

**Comment by thestinger** [comment]
This works fine. The switch for executing commands takes a single argument. You need to use quotes if there are spaces.
