### ISSUE TITLE
Support host specific configuration values - specifically font configurations

### ISSUE THREAD

**Issue by wimstefan** [thestinger/termite#438]
I'm using termite on 5 different computers with 5 different resolutions and I have to edit 4 configuration files by hand every time I sync the config from the main computer (which happens quite often at the moment since I try to implement a system wide colour palette that I created for myself).

Would it be possible to create a construction working with conditionals depending on the host name?

Thanks in advance.

**Comment by jelly** [comment]
This was a related ticket I'd say https://github.com/thestinger/termite/issues/260 which was closed. I don't feel like adding detection on hostname's to termite's config parser. (actually the gnome components parse config files). include's in my opinion would be the only sane alternative.

**Comment by vodik** [comment]
Honestly, I think it probably makes the most sense to just invest in configuration management:

```jinja
color0 = {{ palette.color0 }}
color1 = ...
```

And just template the config as you roll it out on the various machines.

**Comment by wimstefan** [comment]
Thanks for your attention guys :)

It's not so much about the colours. I got that sorted and also use kind of a configuration management to get a unite colorscheme throughout all the applications I use. Remains the fact that I have to manually adjust the font settings manually on 4 computers. That could be handled with an include of course but still there has to be some logic which include to choose depending on the host ... 

And yes you could workaround that problem outside the termite config file but if the includes logic is already about to be  implemented one could address that problem as well could you?

**Comment by thestinger** [comment]
I don't want to add this.
