### ISSUE TITLE
High byte number Unicode characters break backspace display

### ISSUE THREAD

**Issue by samcv** [thestinger/termite#440]
Typing this and then backspacing twice
Typing this: '# 🐧🐧'
and then backspacing twice visually looks like: '#  🐧  ' but there are no actual characters there, if you hit enter it is as if entering no text. There is some bug with backspacing.

**Comment by opeltre** [comment]
Hi, had sort of a same kind of mysterious problem:
When entering ssh in termite, backspace would display as if a space was typed instead, although the command seems to be interpreted with properly deleted characters. 
Exiting ssh in the same termite window, backspace comes back to normal.
I tried the same ssh connection through login shell and suckless terminal in my window manager so figured it was a termite bug, not the wm...  

It seems that setting 
`#TERM=xterm`
fixed it. I wonder how the `TERM` variable can be set in termite configuration though...

**Comment by thestinger** [comment]
That's not the same as this issue and you're not solving it, you're creating a different problem.

**Comment by thestinger** [comment]
You need to use `tic -x termite.terminfo` to install the terminfo file on other hosts (you don't need root, there's a local database). Anyway, it's unrelated to this issue.

**Comment by thestinger** [comment]
The original issue report here is upstream issue with VTE. Please report it there. You can confirm that it occurs with any VTE3-based terminal including their sample app.

**Comment by polyzen** [comment]
Apparently [this is the upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=772890) (thanks to @kyrias for sharing).

**Comment by opeltre** [comment]
Ok I understand this is another problem
Overriding `TERM` variable sure is no good, so thank you the terminfo file did solve mine...

**Comment by samcv** [comment]
@polyzen can this ticket stay open until it is fixed upstream? Hopefully others in the future won't try and open this same issue again. Thanks

**Comment by polyzen** [comment]
@samcv, it's not up to me, but it's normal/expected to search for issues before opening, anyhow. :p

**Comment by thestinger** [comment]
I don't want an issue tracking each upstream bug. It's too much to manage here.

**Comment by samcv** [comment]
Okays thanks @thestinger
