### ISSUE TITLE
Infinite Scrollback

### ISSUE THREAD

**Issue by andrewhanlon** [thestinger/termite#442]
Is it possible to get infinite scrollback like in terminator or must it be set to some finite value?

**Comment by jelly** [comment]
termite uses vte3, which provides a function call to set the [scrollback history](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-scrollback-lines)

Setting it to a negative value makes the scrollback history "infinte"

**Comment by andrewhanlon** [comment]
Thank you!
