### ISSUE TITLE
Unable to use column copy mode in vim

### ISSUE THREAD

**Issue by lrvick** [thestinger/termite#444]
Ctrl+Shift+v is column copy mode in vim and termite seems to clobber it.

Is there no way to remap the leader for termite? I expect conflicts like this to keep happening.

**Comment by polyzen** [comment]
Assuming you're talking about [this](http://vimdoc.sourceforge.net/htmldoc/visual.html#CTRL-V), it works fine. Ctrl+Shift+V is used as paste by termite and [most terminals](https://superuser.com/a/421468).

**Comment by thestinger** [comment]
The vim binding is just ctrl-v, case doesn't matter.

**Comment by lrvick** [comment]
TIL I have been doing it wrong for years. Derp. Thanks.
