### ISSUE TITLE
Font got stacked on terminal

### ISSUE THREAD

**Issue by Gujarats** [thestinger/termite#446]
Hello I got problem when viewing the font on my terminal. I have installed this on my fresh arch Linux and also tried to change the font via config file.

Here is my screenshot of my terminal : 
![1](https://cloud.githubusercontent.com/assets/10476678/22113660/9783a976-de99-11e6-9904-60f5e75a70ba.png)

Notice on the screenshot that the font @ and g got stacked and it is really annoying. Anyone knows how to solve this problem?

**Comment by jelly** [comment]
It would be useful if you would post the actual font configuration option.

**Comment by Ploppz** [comment]
Don't know if the same problem but when I did a system update (Arch linux) just recently, my font also didn't seem to be found (yielded that strange font with off kerning). Used `gohufont 8` - it worked before. Now tried `peep 10` - it works but I want smaller font, which worked before but not anymore. Might also be that the update somehow messed with my font installations? But `xfontsel` finds both `gohufont` and `peep` in differen sizes.

**Comment by Brottweiler** [comment]
Show your termite config. What font do you use? What does it say in the config about font?

Do `fc-list | grep "your font"` and make sure you have the right name. Considering you use arch linux, this surely is related to the harfbuzz update. Read more [here](https://np.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/dc698h0/).

**Comment by Ploppz** [comment]
```
[options]
resize_grip = false
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
visible_bell = false
mouse_autohide = false
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
# font = gohufont 8
font = peep 10
search_wrap = true
cursor_blink = system

cursor_shape = block

browser = chromium

[colors]
foreground = #dddddd
foreground_bold = #cccccc
background = #150a10


#Black
color0 = #0C0500
color8 = #666666
#Red
color1 = #BC2C24
color9 = #CD0E3A
#Green
color2 = #0C8D01
# color10 = #79CA30
color10 = #71AA21
#Brown
color3 = #C36B13
color11 = #D8871D
#Blue (INDIGO)
# color4 = #721B81
color4 = #701D85
color12 = #933EAC
#Magenta
color5 = #802261
color13 = #A62976
#Cyan (BLUE)
color6 = #366694
color14 = #0481B8
#Gray/White
color7 = #CC8888
color15 = #BBBBBB

color16 = #211007


[hints]

```

```
$ fc-list | grep peep
/home/ploppz/.local/share/fonts/zevv-peep-iso8859-1-07x14.bdf: peep:style=Regular
/home/ploppz/.local/share/fonts/zevv-peep-iso8859-1-08x16.bdf: peep:style=Regular
/home/ploppz/.local/share/fonts/zevv-peep-iso8859-1-10x20.bdf: peep:style=Regular
```

```
$ fc-list | grep gohufont
/usr/share/fonts/misc/gohufont-uni-14.pcf.gz: Gohu GohuFont:style=Regular
/usr/share/fonts/misc/gohufont-11.pcf.gz: Gohu GohuFont:style=Regular
/usr/share/fonts/misc/gohufont-uni-11.pcf.gz: Gohu GohuFont:style=Regular
/usr/share/fonts/misc/gohufont-14.pcf.gz: Gohu GohuFont:style=Regular
/usr/share/fonts/misc/gohufont-uni-14b.pcf.gz: Gohu GohuFont:style=Bold
/usr/share/fonts/misc/gohufont-14b.pcf.gz: Gohu GohuFont:style=Bold
/usr/share/fonts/misc/gohufont-uni-11b.pcf.gz: Gohu GohuFont:style=Bold
/usr/share/fonts/misc/gohufont-11b.pcf.gz: Gohu GohuFont:style=Bold
ploppz at ~ $ 
```

**Comment by Brottweiler** [comment]
So neither of those two fonts work properly?

**Comment by Ploppz** [comment]
You were right about the problem - I did as in the link and used this name for the font instead: `font = gohu gohufont Regular 8` and it works now! Thanks.

**Comment by Gujarats** [comment]
I still have the problem here, here is my config termite : 
```
[options]
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
mouse_autohide = false
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
#font = NotoSerif-Regular 9
font = noto notofont Regular 12
scrollback_lines = 10000
search_wrap = true

```

and whe fc-list | grep notofont

/usr/share/fonts/noto/NotoSansUI-Regular.ttf: Noto Sans UI:style=Regular
/usr/share/fonts/noto/NotoSansTelugu-Bold.ttf: Noto Sans Telugu:style=Bold
/usr/share/fonts/noto/NotoSansDevanagari-Regular.ttf: Noto Sans Devanagari:style=Regular
/usr/share/fonts/noto/NotoSansGurmukhiUI-Bold.ttf: Noto Sans Gurmukhi UI:style=Bold
/usr/share/fonts/noto/NotoSansBengaliUI-Regular.ttf: Noto Sans Bengali UI:style=Regular
/usr/share/fonts/noto/NotoSansCham-Regular.ttf: Noto Sans Cham:style=Regular
/usr/share/fonts/noto/NotoSansHebrew-Regular.ttf: Noto Sans Hebrew:style=Regular
/usr/share/fonts/noto/NotoSansGeorgian-Regular.ttf: Noto Sans Georgian:style=Regular
/usr/share/fonts/noto/NotoSansUI-BoldItalic.ttf: Noto Sans UI:style=Bold Italic

any ide how to solve this?

**Comment by Brottweiler** [comment]
Try change `font = noto notofont Regular 12` to `font = Noto Sans UI Regular 12`?

**Comment by Gujarats** [comment]
the font is still overlapping. is this has problem with my arch linux version? `Linux gujarat 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

**Comment by Brottweiler** [comment]
No, your font name is incorrect in the termite config. The problem isn't that the "font is overlapping", you're specifying an invalid font. Try change it to `font = Noto Sans UI`.

**Comment by Gujarats** [comment]
I'm unable to see the link provided by you on reddit since my internet provider block it. so I'm following this guide now https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671. but when I try your solutions the problem on my terminal still exist. the font size was changed but "the font still stack with @ and g and also m and o"

**Comment by Gujarats** [comment]
after trying several ways, I still can't figure it out why the font is not showing like normal. if anybody has a solution please help. thank you

**Comment by Brottweiler** [comment]
I still think somehow the name is wrong, but I don't know what it should say.

**Comment by ixjlyons** [comment]
I think it's because you're using a proportional (i.e. non-monospace) font. Try `font = Noto Mono 10`.

**Comment by Gujarats** [comment]
@ixjlyons Hmm I still don't understand what is the rule to write the font on termite. But thanks to you right now my termite looks normal.

**Comment by Ploppz** [comment]
`monofur` font http://imgur.com/a/tFzaj  - I can't get it right in termite config with `font = misc monofur Regular 14`. It shows default (faulty, which is normal when it can't find the font) font. Shouldn't it be foundry first the family?

**Comment by thestinger** [comment]
This is an issue tracker, not a support system.

**Comment by jelly** [comment]
@Ploppz 
```
font = monofur Regular 12px
```
Seems to work as expected..
