### ISSUE TITLE
Ctrl+Shift+v not working under Wayland

### ISSUE THREAD

**Issue by andmarti1424** [thestinger/termite#447]
Termite is not pasting the content of clipboard..

1. copy a link in firefox
2. open termite and press C-S-v.
3. Content is not pasted.

If instead of termite, I paste clipboard content in.. say for instance.. vim. ("+p) the content is paste correctly.

**Comment by embik** [comment]
Are you by chance running sway or another wlc-based window manager? wlc doesn't synchronise X11 and Wayland clipboards, hence Wayland applications such as Termite cannot access anything copied from X11 applications (such as Firefox). vim is accessing the X11 clipboard and therefore fine. That's not Termite's fault though.

**Comment by andmarti1424** [comment]
Indeed I am using sway. Is there a way to copy to Wayland clipboard manually? Or just insert content to it? Thanks.

**Comment by jelly** [comment]
So far I haven't found anything about it. But this really isn't a termite issue.
