### ISSUE TITLE
Allow "spoiler text" to be viewed on selection

### ISSUE THREAD

**Issue by japanoise** [thestinger/termite#449]
Hi, in many irc channels I'm in, we highlight text black-on-black for potential spoilers. As it is currently, selection colors are chosen by applying reverse video to the selected span (afaict). This works for most text, but not for spoiler text. Could we maybe override the selection color or something like that?

**Comment by guiniol** [comment]
@japanoise if you set `highlight` in the `termite.conf` (section `[colors]`), the specified colour will be used when highlighting text, whatever the foreground and background colour. Does that help?

**Comment by japanoise** [comment]
It's definitely a good start, spoiler text can be viewed after setting it to #ffffff. While it would be nice to be able to set the selection foreground too, this really fixes my issue.
