### ISSUE TITLE
Delayed repeated key press

### ISSUE THREAD

**Issue by andresmrm** [thestinger/termite#450]
These days I started having a very strange behavior with termite: when I scroll up or down in a program (e.g. man or vim), holding J/K or arrow keys for a moment and then releasing, the cursor moves until I release the key (ok), but then after about 1s the cursor moves again one line in the same direction. Like a delayed one line scroll (quite annoying...).

First I thought it was an OS problem. But I can't reproduce the problem with urxvt or Sakura.

Any ideas?

Using:
termite 12-1
Archlinux
(tested with termite-git (termite v12-13-g7738c76) and the problem persists)

**Comment by andresmrm** [comment]
The same issue happens when pressing backspace for a while and then releasing. So it's not just a scroll problem.

**Comment by thestinger** [comment]
I don't think this is a termite issue. I can't reproduce it and it's not responsible for terminal emulation anyway, that's VTE.

**Comment by andresmrm** [comment]
Thanks for the reply, @thestinger !
Any ideas about why this is happening with termite and not with other terminals (I'm using Sakura for now, that is also based on VTE)?
