### ISSUE TITLE
symbols/emoji overlap or insert spaces

### ISSUE THREAD

**Issue by guiniol** [thestinger/termite#451]
When displaying emojis or symbols, termite doesn't seem to know what width to use exactly.
They either overlap with the next character, or insert spaces which can never be deleted.

overlapping characters (font Noto Color Emoji)
![screenshot from 2017-01-25 12-09-09](https://cloud.githubusercontent.com/assets/3483433/22288423/1af78e56-e2f7-11e6-9bd3-c65a85683f32.png)

weird spacing when typing a new character (font Symbola)
1. type `😎`
2. type `a`
3. type `<backspace>`
4. type `<backspace>`
![screenshot from 2017-01-25 12-12-19](https://cloud.githubusercontent.com/assets/3483433/22288545/8df3fc1e-e2f7-11e6-918b-da4b0bf87eb8.png)
Notice how I can't get back to the beginning of the line.

Is there something wrong with my configuration? Anything I could do to fix that?

**Comment by jelly** [comment]
Duplicate of https://github.com/thestinger/termite/issues/440

**Comment by guiniol** [comment]
Sorry, didn't see that one.
