### ISSUE TITLE
Multi-fonts support ?

### ISSUE THREAD

**Issue by kiuKisas** [thestinger/termite#452]
I ask me a question, can Termite manage enough fonts to provide  a multi fonts support (if one glyph miss, go check to other one) or VTE is in total power with that ?

**Comment by thestinger** [comment]
It's already a standard freetype2 / fontconfig feature and the fallback order can be configured. It's not for either Termite or VTE to do.

**Comment by kiuKisas** [comment]
I see.. si How can I set it up in my conf file, something like : 
```
font = font1 10
font = font2 10
```
if a glyph doesn't exist in glyph in `font1`, it gonna search in `font2`.. ?

**Comment by thestinger** [comment]
As I said, it's already a standard freetype2 / fontconfig feature. There is nothing to configure in Termite. It will already search through all fonts for glyphs and you can configure order via fontconfig.
