### ISSUE TITLE
Exiting a process does not go back to terminal

### ISSUE THREAD

**Issue by chrissound** [thestinger/termite#453]
If I run a command ilke `termite --exec="ghci"`, this opens fine, however if I exit from that application it exits the terminal as well. 

Is it starting the `ghci` application directly? (Not 100% familiar with linux processes), is there a way I can have it exit instead 'to' a terminal?

**Comment by thestinger** [comment]
It executes the command you ask it to execute. If you want to execute something else when it exits, you need to ask for that.

**Comment by thestinger** [comment]
termite -e "bash -c 'echo example; bash'"

**Comment by chrissound** [comment]
Thank you!
