### ISSUE TITLE
paste takes long time to print

### ISSUE THREAD

**Issue by eoli3n** [thestinger/termite#454]
I middle clicked directly after launching record.
Then i CTRL+C, the incomplete string appears.
I immediatly redo a middle clic after CTRL+C.
[![asciicast](https://asciinema.org/a/49i6t6x75pq5y434xj9mbarjp.png)](https://asciinema.org/a/49i6t6x75pq5y434xj9mbarjp)

The strange thing is that in vim, it appears without lag
[![asciicast](https://asciinema.org/a/4k3dylsbdx1gmzrevzebvo7w1.png)](https://asciinema.org/a/4k3dylsbdx1gmzrevzebvo7w1)

Not sure if it's a termite issue

**Comment by thestinger** [comment]
I don't think this a termite issue.

**Comment by eoli3n** [comment]
Any idea where could it come from ?
