### ISSUE TITLE
No available termcap for FreeBSD

### ISSUE THREAD

**Issue by lrvick** [thestinger/termite#456]
I am using termite to connect to a remote FreeBSD system.

Attempting to use things like tmux fails as expected:

```
open terminal failed: can't find terminfo database
```

The 'base' version of ncurses that ships with freebsd is compiled without terminfo support, so I installed devel/ncurses which has it however it has no maintainer and while I can add entries to terminfo.db as expected with tic, things like tmux only seem to see/care about the termcap file.

All attempts to automatically convert to termcap via infocmp etc so far have failed to result in anything cap_mkdb could parse. Open to any ideas.

**Comment by thestinger** [comment]
It's not going to be officially supported.
