### ISSUE TITLE
Increase the speed of holding space to continually move the cursor

### ISSUE THREAD

**Issue by mindstormer12** [thestinger/termite#457]
Is there a reason why holding space to continually move the cursor has a noticeable delay compared to the holding space to continually move the cursor on the virtual console? I don't see an option to configure this. Is it possible to decrease this display to match the virtual console's delay? In my opinion, that's more appropriate.

**Comment by thestinger** [comment]
You can already configure the key repeat rate. It's an X11 / Wayland compositor setting.
