### ISSUE TITLE
Error opening terminal: xterm-termite

### ISSUE THREAD

**Issue by pete3215** [thestinger/termite#458]
When using termite to work remotely via ssh, using 'nano' causes the following error:

> Error opening terminal: xterm-termite

This only happens with termite. Why is that? Is this a bug or is something wrong with my installation?

**Comment by thestinger** [comment]
You need terminfo installed there. This has been asked a bunch of times here.

**Comment by pete3215** [comment]
Sorry to have missed the answer in the issues.

Terminfo is installed on my system. I am using arch linux and everything is up to date.

**Comment by thestinger** [comment]
It's not installed *on the system you're logging into* and as I said this is explained a bunch of times here, I'm not answering the same question again and again.
