### ISSUE TITLE
Request: make termite usable on remote machines

### ISSUE THREAD

**Issue by pete3215** [thestinger/termite#459]
As several other issues already reported, termite need terminfo installed on remote systems to work correctly.
However this is not an option when working with a number of remote systems where one can not simply install new software.

Therefore please make termite usable without installing additional software on remote systems.

**Comment by thestinger** [comment]
Putting terminfo on remote systems doesn't require installing any software or root access. Either way, it already works fine without this. This information is already on the tracker. I don't need to keep hearing about it.
