### ISSUE TITLE
Add setb24/setf24 terminfo caps for Emacs' 24-bit colors

### ISSUE THREAD

**Issue by jlombera** [thestinger/termite#460]
Emacs recently added support for 24-bit color terminals (emacs-mirror/emacs@e463e5762bbe628be3d15da066a90f079a8468b3).  The 24-color support is automatically enabled when setb24/setf24 terminfo capabilities are present in the terminal.

Even though these caps are not standard, is there a chance they could be added to xterm-termite terminfo?

**Comment by egmontkob** [comment]
FYI: see https://bugzilla.gnome.org/show_bug.cgi?id=778958.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
