### ISSUE TITLE
number of cells depending on font rendering

### ISSUE THREAD

**Issue by teto** [thestinger/termite#461]
I've been trying to use the character '⚠'  (http://www.fileformat.info/info/unicode/char/26a0/index.htm) in termite.
I use "Inconsolata For Powerline"  (a monospace font http://levien.com/type/myfonts/inconsolata.html) in termite, but it doesn't have '⚠' and so fontconfig falls back on FreeSerif.
While unicode says '⚠' should occupy one cell (If I understand correctly the unicode spec), it appears to have two as can be seen on screenshots. I was wondering if there could be a way to tweak termite so that when the rendering of a character (I believe it's done by pango) is wider than the width of one cells, it's considered as a multicell character ?

Here we see that the warning sign spills over the next character (third prompt):
![2017-02-22-132033_956x507_scrot](https://cloud.githubusercontent.com/assets/886074/23211319/d1cff01c-f901-11e6-8a14-633646f3b17a.png)

Here we can see that the cursor widths are different between the 2 windows
![2017-02-22-134647_251x344_scrot](https://cloud.githubusercontent.com/assets/886074/23212095/679dcb34-f905-11e6-98e4-b3899d6464fb.png)

**Comment by thestinger** [comment]
Terminal emulation issues should be confirmed in gnome-terminal or the vte-2.91 sample app and filed at the VTE tracker. It's not an issue in the scope of Termite's code.
