### ISSUE TITLE
[bug] url parser and single quotes

### ISSUE THREAD

**Issue by shibumi** [thestinger/termite#463]
Hello,
I found a bug in the url parsing. When I have something like:
`'https://github.com/thestinger/termite'` in my terminal and I click on it, my browser will open: `https://github.com/thestinger/termite'`

**Comment by thestinger** [comment]
That's not a bug, single quotes are permitted in URLs. It might make sense to add a heuristic when there's a leading single quote but I won't remove a valid, reserved URL character:

> Thus, only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used for their reserved purposes may be used unencoded within a URL.

**Comment by thestinger** [comment]
I think the paired quote issue can be considered part of https://github.com/thestinger/termite/issues/155.

**Comment by thestinger** [comment]
Also the URL regex is definitely not super accurate but this part is right.
