### ISSUE TITLE
Single quotes on URL messes it up

### ISSUE THREAD

**Issue by rieje** [thestinger/termite#467]
In a text file, I have the line `https://github.com/seebi/dircolors-solarized`. If I click on it as is, it opens the webpage in a browser. However, if I encapsulate it in single quotes like this `'https://github.com/seebi/dircolors-solarized'`, mousing over the link shows an underline beginning at `h` in the link but ends at *and* including `'`, which is the single quote that's not part of the URL. If I click on the link, it does not open the correct page in the browser because it tries to open `https://github.com/seebi/dircolors-solarized'` instead. This is the case on both 
vim and nano (default settings).

 I'm on Arch Linux with the latest package of termite.

**Comment by j-degreef** [comment]
I can reproduce it.
It doesn't happen with double quotes.
And this bug is not present in Terminator, which is a vte terminal too.

I'm on Linux Mint up to date and Termite from git (master).

**Comment by numerical** [comment]
So the problem here is that `'` is valid in URIs. In this case we'd have to add backtracking in order to identify that a URI is embedded in quotes. Also it would probably require some post processing to remove said single quotes.

**Comment by thestinger** [comment]
This has been thoroughly explained in the past. No need for more issues filed about something that's working as intended. A heuristic for wrapping parentheses / quotes might be considered but it isn't necessarily wanted. It's a valid character in a URL, including at the end.
