### ISSUE TITLE
Using nvidia-375 and termite on ubuntu together results in segfaults in termite

### ISSUE THREAD

**Issue by karlmutch** [thestinger/termite#469]
First, thanks for a UTF8 terminal that renders rich fonts correctly.

Compiling termite on Ubuntu 16.04 without nvidia-375 installed and running termite works.

Installing nvidia 375 using 'apt-get install nvidia-375' then running termite with gdb results in the following:

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from termite...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/termite
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37      ../sysdeps/x86_64/rawmemchr.S: No such file or directory.
(gdb) bt
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff549bff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffa800, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0)
    at strops.c:41
#2  0x00007ffff548abb7 in __GI___isoc99_vsscanf (string=0x0, format=0x7ffff34c42f2 "%d.%d", args=args@entry=0x7fffffffa928) at isoc99_vsscanf.c:41
#3  0x00007ffff548ab57 in __isoc99_sscanf (s=<optimized out>, format=<optimized out>) at isoc99_sscanf.c:31
#4  0x00007ffff34a6d22 in epoxy_glx_version () from /usr/lib/x86_64-linux-gnu/libepoxy.so.0
#5  0x00007ffff6fd465b in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007ffff6fd49da in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff6fdd0fe in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff6fda076 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007ffff6fcc355 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#10 0x00007ffff6fa66c6 in gdk_display_manager_open_display () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#11 0x00007ffff7463266 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff62faf38 in g_option_context_parse () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x0000000000405bc2 in ?? ()
#14 0x00007ffff543f830 in __libc_start_main (main=0x4058c0, argc=1, argv=0x7fffffffb3e8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffb3d8) at ../csu/libc-start.c:291
#15 0x0000000000406939 in ?? ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 18103] will be killed.

Quit anyway? (y or n) y

* Uninstallation of nvidia-375 using 'apt-get remove nvidia-375 && apt-get autoremove' returns termite to a working state

**Comment by jelly** [comment]
I can't say anything useful about this issue, I have no idea what the issue could be. Does gnome-terminal work as expected?

**Comment by j-degreef** [comment]
That's rather strange...
I'm running Termite (master compiled by myself) on Linux Mint 18.1 (based on Ubuntu 16.04) without problem with nvidia-375)...

![2017-04-04-123512_1366x768_scrot](https://cloud.githubusercontent.com/assets/6998555/24652967/24626844-1934-11e7-9357-1748c8d78a7c.png)

**Comment by thestinger** [comment]
This isn't a Termite issue. It's a distribution / user configuration issue.
