### ISSUE TITLE
THEMING  -  add option to set alpha channel only // read color from Xresources

### ISSUE THREAD

**Issue by vKnmnn** [thestinger/termite#473]
Hi! 
Are we able to make termite read (colors) in Xresources / bash variables/ shell script and only set a fixed alpha to it?
 e.g.
```
#background=$(script.sh)
background=Xresources
alpha=0.8
```
This would make termite match the applied theming on the fly, if set up correctly, without having to change the values in the config

**Comment by thestinger** [comment]
No, the legacy X resources system isn't going to be supported and neither is turing complete configuration.
