### ISSUE TITLE
Space after some unicode characters

### ISSUE THREAD

**Issue by atomrc** [thestinger/termite#479]
I am not sure if this problem is related to this issue https://github.com/thestinger/termite/issues/440 and I am sorry if it's a duplicate. 

The problem occurs with this character ⚡ (and I think I can find some others). When I print it, I get an extra space just after it. 

Here is a screenshot of what I get (on the right `xterm` and on the left `termite` with the extra space).

![deepinscreenshot20170504195432](https://cloud.githubusercontent.com/assets/1090716/25717970/a2b3ac8e-3104-11e7-8fe8-c8f974428682.png)

This seems to break backspace (sometimes). 

I am running Arch Linux with `i3` (not sure if it is relevant). and the font I use is `DejaVu`.

Thanks for you help and sorry if I just misunderstood the comments in the issue https://github.com/thestinger/termite/issues/440

**Comment by egmontkob** [comment]
See e.g. https://bugzilla.gnome.org/show_bug.cgi?id=772812.
