### ISSUE TITLE
Fira Code Font

### ISSUE THREAD

**Issue by Jab2870** [thestinger/termite#480]
Hi,
Thanks for making this awesome terminal.

I am coming from Konsole and love to use the Fira Code font: [https://github.com/tonsky/FiraCode](https://github.com/tonsky/FiraCode).

Unfortunately the litgures don't seem to work in termite.  Is there any plan to add support for these?

**Comment by thestinger** [comment]
That's not in scope for Termite, it's a VTE thing.
