### ISSUE TITLE
Arch update to gtk3-3.22.13-1 breaks copy paste

### ISSUE THREAD

**Issue by jpoppe** [thestinger/termite#481]
After updating gtk3-3.22.12+6+g42aa4c138c-1 to gtk3-3.22.13-1 copying from any other applications then Termite and pasting it to Termite got broken.

Copying and pasting between other applications seems to work fine.

**Comment by vimeitor** [comment]
Can confirm.

**Comment by frebib** [comment]
Came looking for this issue, so can definitely confirm

**Comment by thestinger** [comment]
https://www.reddit.com/r/archlinux/comments/6adzmi/latest_upgrade_to_gtk3_breaks_paste/

It's not a Termite issue. Some people have the problem on Wayland (some with XWayland) and others just on only X11.
