### ISSUE TITLE
Cursor shape becoming "block" when running neovim

### ISSUE THREAD

**Issue by tgy** [thestinger/termite#483]
### Reproduce issue

1. Get last git version of termite and last version of neovim (`neovim-0.2.0-2`)
2. Set `cursor_shape = "ibeam"` in `~/.config/termite/config`
3. Open a new termite terminal
4. Observe the cursor shape is correct
5. Run `nvim`
6. Observe that the cursor shape is now `"block"`
7. Exit neovim
8. Observe that the cursor shape is still `"block"`

**Comment by tgy** [comment]
Setting `NVIM_TUI_ENABLE_CURSOR_SHAPE` to `1` solves the problem.

**Comment by tgy** [comment]
My bad, it didn't solve the problem.

**Comment by egmontkob** [comment]
See https://github.com/neovim/neovim/issues/4396 and perhaps also https://github.com/neovim/neovim/issues/2583.

**Comment by teto** [comment]
This is a neovim problem which is impossible to solve correctly I believe because terminals won't share the cursor status. In VTE it's possible to reset the cursor and I hope to make the feature usable in a future neovim PR.
This can be closed.
