### ISSUE TITLE
Open editor for command

### ISSUE THREAD

**Issue by Jab2870** [thestinger/termite#484]
Hi, Thanks for making such a great tool.

I have recently moved over to Termite and the only thing I really miss is the ability to write a command in vim (or whichever my default editor is). I most other terminals I have used, I've been able to type `CTRL+x e` and the current line is opened in vim.  I can then use vim to edit the command.

When I try to do this in Termite, I just end up inputing `^Xe`. Is there a way around this?

**Comment by thestinger** [comment]
That's a shell feature, not a Termite feature. It sounds like your shell just isn't configured to do that.
