### ISSUE TITLE
Allow a path like string to be opened like a url

### ISSUE THREAD

**Issue by warmwaffles** [thestinger/termite#485]
Often when I am developing and greping around for things, I have strings with output that look like this

```
rg Foo
src/foo.c
20:  struct Foo {
30:  malloc(sizeof(struct Foo))
```

It would be nice to be able to click on the `src/foo.c` path and have it hook to a program of our chose like `xdg-open` or a shell script of sorts.

**Comment by egmontkob** [comment]
In case of autodetection:

- A really nontrivial technical issue would be that termite would need to know the working directory at the time the given relative filename was printed. (Plus ideally it would also need to know if you're ssh'ed somewhere, not to open the local counterpart of a remote file then.)

- A usability issue would probably be having tons of false positive matches, and/or not recognizing filenames that aren't under a subdirectory.

Another approach could be explicit hyperlinks (see #476) which is supported by newest development VTE releaes, but requires termite to hook up (alas the keyboard-centric approach that termite wishes to have doesn't exist) as well as explicit support from the application (e.g. `grep`).

**Comment by warmwaffles** [comment]
> A usability issue would probably be having tons of false positive matches, and/or not recognizing filenames that aren't under a subdirectory.

@egmontkob I don't think that is really an issue though. iterm2 on a mac doesn't really have this issue. It can definitely be solved. I am just unsure of how it could be.

**Comment by egmontkob** [comment]
I have no clue what iterm2 does here, but it definitely _is_ an issue to think about. Let's say you'd like to recognize files that aren't under a subdirectory, e.g. `foo.c`. But why require an extension, let's recognize and automatically linkify `foo` as well. Now I happen to have a file named `the` and I open an English text file in a text editor -- should all the words `the` be linkified??? Where to draw the line?

**Comment by warmwaffles** [comment]
> But why require an extension, let's recognize and automatically linkify foo as well ... should all the words the be linkified??? Where to draw the line?

That is not what this feature request is for. It is to link if the entire string is a valid path. No linking on sub directories. IE the only thing that would be linked is if it is `src/foo.c` or hell the directory itself, provided the statement ended with a whitespace like so `/tmp`.

One way to check to see if the string is indeed a path is to see if there is at least 1 slash in the path.

The problem is when you have a directory that looks like this:

```
./this is/a/valid/path
```

You'd have to either require backslashes or do a regex to parse the rest of the string. I have no clue how the terminal detects http links, but I assume it could use the same logic around that.

**Comment by egmontkob** [comment]
> It is to link if the entire string is a valid path. [...] there is at least 1 slash

What makes `src/foo.c` a valid path in your eyes, but after cd'ing to `src`, `foo.c` not a valid one??

Why is it okay in the output of `rg` (which I think is your custom recursive grep, right?) to allow to quickly and conveniently open `src/foo.c`, but not a matching file that's in the toplevel directory where you run `rg` from (e.g. `README`)?

Okay, as long as it's about heuristics, you might want to say that this is where you draw the line, this is where you start saying it's "likely" a filename. But I think it's of quite limited usability.

Please _do_ take a close look at the explicit hyperlink feature I've linked to you, I believe that is what really suits you rather than some autodetection magic.

**Comment by egmontkob** [comment]
(By the way, let's clarify: I'm not a Termite owner/developer/maintainer. I'm a VTE developer lurking around.)

**Comment by warmwaffles** [comment]
`rg == ripgrep` http://blog.burntsushi.net/ripgrep/

**Comment by egmontkob** [comment]
It's on my todo list to send feature requests for explicit hyperlinks to relevant standard tools including `GNU grep`. Non mainstream tools such as `ripgrep` are outside of my radar, but you may want to file a feature request to them.

**Comment by dkasak** [comment]
@egmontkob 

> [...] (alas the keyboard-centric approach that termite wishes to have doesn't exist)

Why doesn't it? Is there any chance of it being supported?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Comment by warmwaffles** [comment]
@thestinger loved termite. Thanks for all the work. I moved to Alacritty about a year ago.
