### ISSUE TITLE
Home directory config file not applying

### ISSUE THREAD

**Issue by devonryder** [thestinger/termite#486]
I've created a termite config file located at `~/.config/termite/config`, but this file is not applying when I launch termite. I've even tried launching termite using `termite -c ~/.config/termite/config` to no avail. 

I am using the latest `version 12-2` from `pacman` on Arch/Antergos.

**Comment by cassava** [comment]
I am seeing this issue as well.

**Comment by jelly** [comment]
This works fine for me. Did you try strace'ing termite and verifying it really loads the file or copying the sample config file? Also what is in your config file?

**Comment by cassava** [comment]
From `strace` I can see that it loads my file in `~/.config/termite/config` then `/etc/xdg/termite/config`.

**Comment by cassava** [comment]
A few further notes:
 - I removed `/etc/xdg/termite/config` and a change is visible (default settings).
 - I copied that config file to `~/.config/termite/config` and the settings are loaded again.
 - If I modify the file in a minor way (change a few colors), these settings are loaded
 - If there are any errors in the config, no error message is given, and it would appear that the entire config is discarded

In my case, I had a syntax error in the config which caused it to be discarded.

**Comment by jelly** [comment]
It seems that glib has some error handling options for [https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#g-key-file-load-from-file g_key_file_load_from_file], but that won't really help since that only detects key value issues. Which will show:

```
/home/jelle/.config/termite/config parsing failed: Key file contains line “wjeif” which is not a key-value pair, group, or comment
```

However failing of parsing the following is not reported:
```
foo = falsee
```

Which needs to be handled separate.

**Comment by devonryder** [comment]
Turns out I had an accidental mistyped character that I hadn't noticed. The config now loads fine. As for `strace`, is the correct usage in the case of termite you were suggesting `strace termite`? It's seems to be what you were suggesting, because I see a ton of rapid output with fonts loading and such, but I wasn't sure if you'd suggest certain flags?

**Comment by cassava** [comment]
What you can always do is run it and pipe the output through grep: `strace termite 2>&1 | grep "open("`

**Comment by jelly** [comment]
One PR has been merged, which now shows error messages when the ini format is 100% correct.
