### ISSUE TITLE
bring back pseudo transparency

### ISSUE THREAD

**Issue by raspbeguy** [thestinger/termite#489]
Hello,
This can sound like a nonsense considering the work you put into making true transparency available, but it would be great is you could bring pseudo transparency back. I don't want to use real transparency as I don't want to lauch a composer (it messes up with some other programs like i3lock).
That's the only thing that stops me to use termite, which I would really like to use, as it's nice to configure and handles well special characters.
Why not proposing both transparency methods like urxvt for instance ?
Thanks.

**Comment by Narrat** [comment]
Termite is a vte based terminal. Vte upstream (GNOME) decided to remove it.
So this is the wrong place to ask

**Comment by jelly** [comment]
Please check the old bug reports #169 and  #237. VTE removed this feature so it will not be added back.
