### ISSUE TITLE
Termite doesn't respect BROWSER

### ISSUE THREAD

**Issue by IQubic** [thestinger/termite#490]
If I add to my .zprofile `export BROWSER=qutebrowser` then I can't open any links at all.
However removing that line from my .zprofile allows me to open links as normal, and they will be opened in qutebrowser, as that is my default browser. I don't understand why being explicit about my browser would confuse Termite.

Running `env` shows the right value for BROWSER. AKA the value exported in .zprofile

Thanks in advance,
IQubic

**Comment by jelly** [comment]
After some testing, it works for me. The config file browser has a preference over the BROWSER env. Did you check your termite config.

**Comment by IQubic** [comment]
Nothing related to browsers is being set in my config file.
Only colors, fonts, and cursor shape.

**Comment by IQubic** [comment]
I just noticed this from the readme: 

`If no browser is configured and $BROWSER is unset, xdg-open from xdg-utils is used as a fallback.`

But I do have a $BROWSER set. Why is link opening failing?

**Comment by IQubic** [comment]
Well I feel stupid. Capitalization matters.
Closing this as it has been resolved.
