### ISSUE TITLE
Binding Shift to F30 or F13+ keys when pressed alone causes strange behavior

### ISSUE THREAD

**Issue by rieje** [thestinger/termite#491]
I want to bind SHIFT to an unused key when pressed alone (or a key that doesn't trigger anything in most if not all applications), for example maybe an F key like F30 or something. If it's used as a modifier, don't change its bindings (e.g. continue using SHIFT as you would typically use it as a modifier). xcape can accomplish this. The reason I want to do this is so I can use SHIFT as a leader key for both vim and emacs without any caveats.

So I execute the following:

    xmodmap -e 'keycode 255=F30'
    xcape -t 250 -e 'Shift_L=F30'

xev shows that tapping shift shows up as F30, as expected. 

However, when I'm on termite, if I press SHIFT alone on a string of command I typed out, it turns all the characters at and to the right of the cursor to uppercase if they were lowercase and vice versa. I tried binding it to other F keys and also using a different dummy keycode other than 255 but the same behavior occurs on the terminal.

I don't think this is a termite-specific behavior. Someone said they were able to achieve something [similar](https://www.reddit.com/r/emacs/comments/6hp3wl/attempting_to_rebind_shift_key_when_pressed_alone/dj074re/) to what I want with urxvt where F30 doesn't do anything on the terminal, but he's using urxvt. I've tried urxvt but the same behavior exists--hoping someone can at least understand what's the problem.

**Comment by aereaux** [comment]
I can confirm I also experience strange behavior (like this?).  I bind some of my extra keyboard keys to F13+, and in termite (and no other program I can find), when pressing any of these keys I get a `~`.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
