### ISSUE TITLE
Delay when hitting escape key?

### ISSUE THREAD

**Issue by antoyo** [thestinger/termite#493]
Hello.
It seems there's a delay when hitting the escape key.

I can see a difference in vim between `termite` and `urxvt`.

I do **not** use a terminal multiplexer, like tmux.

Is there a delay in termite when hitting the escape key (or other keys as I think this also happens with other keys)?

**Comment by schoettl** [comment]
I cannot reproduce this. I don't see a difference in Vim's response when using Vim in termite or xterm.

Which magnitude of delay are you talking about? Less than 50ms? More than 200ms?

Are you sure you didn't map something like <Esc>x in Vim?

**Comment by antoyo** [comment]
The delay can range from around 500ms to a few seconds.
It can happen in my shell (`fish`) also,  so it's not related to `vim`.
For instance, sometimes when a press a key in the shell, it can take a second to be shown in the terminal.
What can I do to debug this?

**Comment by schoettl** [comment]
Maybe it's a `fish` problem? You could try to reproduce in a different shell.

**Comment by jelly** [comment]
I have the delay with zsh and vim as well, not sure if it's 500 ms, but it looks long.
https://asciinema.org/a/9cEF9fjBZCydEcL5XwFP7YpQi

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
