### ISSUE TITLE
Cursor stops blinking

### ISSUE THREAD

**Issue by S3NTYN3L** [thestinger/termite#494]
I'm running a shiny new install of arch, i3 and termite. The cursor stops blinking after ten seconds.

Setting `cursor_blink =` to either `system` or `on` seems to have no effect other than to let the cursor blink for ten seconds.
`off` does indeed work as intended.

Any suggestions?

**Comment by egmontkob** [comment]
The VTE widget uses the GNOME-wide dconf/gsettings setting /org/gnome/desktop/interface/cursor-blink-time.

**Comment by S3NTYN3L** [comment]
/org doesn't exist on my system. I don't use GNOME.
I'll edit my initial post, but I forgot to mention that the off setting does work.
It's just the other two that insist on blinking for only ten seconds.

**Comment by egmontkob** [comment]
Correction: cursor-blink-time is the frequency, cursor-blink-timeout is the duration.
This is not a path in the filesystem, this is the key within gsetting/dconf. Check e.g. with dconf-editor.

**Comment by S3NTYN3L** [comment]
Hmm, so I've installed dconf-editor and that path you allude to still doesn't exist.
There is an /org directory and a /ca directory.

Care to throw me a bone here...

**Comment by egmontkob** [comment]
I don't know if it's possible to create a new key with dconf-editor. Probably not. The command line dconf tool should probably be able to do it. I'm not familiar with the details and don't have time right now to dig into it, but I'm sure you'll figure it out easily.

**Comment by S3NTYN3L** [comment]
Meh, it's alright. I'll just go back to using URxvt.

**Comment by egmontkob** [comment]
Your call. Sorry if I wasn't clear, I'm not Termite's developer, I'm one of the developers of VTE (the terminal emulation widget underneath) lurking around here as well as on other VTE-based emulators' bugtrackers in the hope that I can help. My knowledge and my time is finite, I contributed with whatever was relevant and I was aware of, but I really don't have time to look things up for you that I'm not familiar with either. Looks like you'd be a happier Termite user if I didn't join this conversation and didn't provide those pieces of information. Sorry to see it.

**Comment by S3NTYN3L** [comment]
You were clear enough.
My knowledge and time is also finite and I'm simply unwilling and unable to dig into this further.
Thanks just the same for trying to assist.
