### ISSUE TITLE
Home/End

### ISSUE THREAD

**Issue by Diapente** [thestinger/termite#496]
On my system (Arch 12-2) the home and end keys don't function as expected. "Home" seems to move the cursor one to the left and "end" jumps back 4/5 characters.

**Comment by jelly** [comment]
In which mode?

**Comment by Diapente** [comment]
Just regular - I spawn it in i3 with $mod-return.

**Comment by varac** [comment]
For me, HOME / END don't have any function in insert mode :o

**Comment by Diapente** [comment]
I think mine was a zsh issue. I added the following to ~/.zshrc:
'bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "\e[3~" delete-char
bindkey "${terminfo[kich1]}" quoted-insert
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line'

**Comment by varac** [comment]
@Diapente Thx, works !
