### ISSUE TITLE
'o' does not open the current selection as a url

### ISSUE THREAD

**Issue by D12EA177E12** [thestinger/termite#499]
The README claims:
> o | open the current selection **as** a url

, but it doesn't.
Suppose "www.google.com" is the current selection, I expect that by hitting the 'o' (or [Return]) key termite would invoke the browser and have it open www.google.com.

Currently, nothing happens.  OTOH, if the current selection **is** a fully-qualified URL (e.g. https://www.google.com) then it would open it.

This issue is related to [#485](https://github.com/thestinger/termite/issues/485).

**Comment by jelly** [comment]
Indeed, we don't treat www.google.com as an url.

**Comment by fedemengo** [comment]
Well for me it doesn't open http://lorempixel.com/640/480/transport

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
