### ISSUE TITLE
Bundle vte-ng with the termite

### ISSUE THREAD

**Issue by Vintodrimmer** [thestinger/termite#500]
Good day,

Will it be possible to bundle the current version of the patched VTE library with the `termite`?

Some distributions are reluctant to include patched libraries in their repositories, which means that `termite` is out of their reach.

See [this issue](https://github.com/voidlinux/void-packages/issues/5760) in `Void Linux` for example.

**Comment by jelly** [comment]
I'm not really a fan of building, that said I'm not fan of vte3-ng at all it's a pain to update and vte3 keeps deprecating features. Honestly effort has to be put in upstreaming the few patches which defined vte3-ng.

**Comment by thestinger** [comment]
The solution to this is upstreaming the patches.
