### ISSUE TITLE
Enabling/disabling bindings

### ISSUE THREAD

**Issue by ArsenArsen** [thestinger/termite#507]
Pretty self explanatory, but some keybinds (eg C-Tab) conflict with the stuff I want in my tmux/vim config and I am wondering is it possible to disable them? Thanks in advance.

**Comment by jelly** [comment]
There is no such functionality yet, neither do we have a way to configure the keybinding. I think this feature should be implemented with the configurable keybindings.

**Comment by ArsenArsen** [comment]
Even a prefix option would be very well-suited. Also, loving the terminal.

**Comment by jelly** [comment]
Prefix option, what should that be?

**Comment by ArsenArsen** [comment]
Similar to Ctrl+B in tmux

**Comment by grawlinson** [comment]
I would love this functionality to be added! My fat fingers keep hitting specific keybindings.

**Comment by wpcarro** [comment]
Is this supported? I'm looking for a way to either disable or remap a keybinding. Frankly I wouldn't mind disabling all of them since I'm just using Tmux.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
