### ISSUE TITLE
howto set font weight?

### ISSUE THREAD

**Issue by gregf** [thestinger/termite#508]
How can I set the fontweight in my config file?

**Comment by hkmix** [comment]
Assuming your font expresses weights with a suffix, e.g. "Iosevka Term" -> "Iosevka Term Light", you can specify the modified name instead. Otherwise, I'm not too sure.

**Comment by gregf** [comment]
It doesn't appear to. I know in i3 and polybar I can do font:weight=medium:size=12 for example. It would be nice if this worked in termite.

**Comment by hkmix** [comment]
Hmm, at least with Iosevka, I'm able to append any of the modifiers and it seems to work. What's your font and how are you configuring it in the config file?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
