### ISSUE TITLE
Sixel Support

### ISSUE THREAD

**Issue by Astrognome** [thestinger/termite#511]
I was recently informed that a system exists called Sixel for displaying bitmaps in terminal (https://github.com/saitoha/libsixel , https://en.wikipedia.org/wiki/Sixel) but was disappointed to find out that Termite does not seem to support this feature.

Is anyone considering adding this feature to Termite? It doesn't seem like it would be terribly difficult to do, and it could be made an optional compile-time flag. If nobody is already planning on doing this, I'd be more than happy to take a crack at it.

**Comment by xzfc** [comment]
It's out of Termite scope; it should be handled by VTE.
See [saitoha/vte-sixel] and [related VTE bug report].

[saitoha/vte-sixel]: https://github.com/saitoha/vte-sixel
[related VTE bug report]: https://bugzilla.gnome.org/show_bug.cgi?id=729204

**Comment by jelly** [comment]
As noted by @xzfc it should be handled by VTE, I really hope the will implement it one day.

**Comment by dtzWill** [comment]
For what it's worth, you can play with experimental sixel support, see comment I left on related issue:
https://github.com/thestinger/termite/issues/539#issuecomment-362679869
