### ISSUE TITLE
Cursor moving bug with keys b and B

### ISSUE THREAD

**Issue by schoettl** [thestinger/termite#513]
There is a bug with the `b` and `B` keys in selection mode:

If the cursor is *n* characters **after** the last word of a line and there is no trailing whitespace after the word, then `b` and `B` go to the begin of the last word + *n* characters.

Reproduce:

- open termite
- type a word
- switch to selection mode (ctrl-shift-space)
- optionally press `l` or the right arrow key
- press `b` or `B`

Then the cursor is not at the beginning of the last word but one character left.

I'm glad to see that termite is still enhanced! I just switched to AUR/termite-git. Thank you!

**Comment by jelly** [comment]
I believe this bug has been fixed in e3a68149029c8bfb2eac1329bf7f59dedb7e6850 which is fixed in master, but has not been released yet.

**Comment by schoettl** [comment]
Oh, I forgot... is there a plan for the next release?

**Comment by jelly** [comment]
Not sure yet, there are still open PR's I want to make time for and include.
