### ISSUE TITLE
Font Awesome not working with Termite

### ISSUE THREAD

**Issue by Hacksaurus** [thestinger/termite#515]
Hello there!
So far I have created issues with Font Awesome, Powerlevel9k, and they all point to termite so here we go!

So the issue that I am having with termite is that a specific glyph from font awesome is not working as expected

You can see that there is an unevenness in the icon as shown here:
![screenshot_2017-08-31_19-10-30](https://user-images.githubusercontent.com/24832107/30045980-55346caa-91bc-11e7-80fb-fb2b4378f0e9.png)

This is what is expected:
![10px shell](https://user-images.githubusercontent.com/24832107/30045897-d74b62f8-91bb-11e7-8cda-61e76f080053.png)

That there is an even distributed space on each side of the icon.
As explained here: https://github.com/bhilburn/powerlevel9k/issues/612#issuecomment-327047317
The problem seems to lie in the way termite handles spacing. But for some sort of reason it only occurs in that section of powerelevel9k, because as you can see on the other section the home icon works perfectly fine...

Thanks for any help!

**Comment by jelly** [comment]
Is it the same issue in gnome-terminal?

**Comment by Hacksaurus** [comment]
![screenshot_2017-09-05_17-36-12](https://user-images.githubusercontent.com/24832107/30089282-c30460a6-9260-11e7-97b6-1d023473a8c6.png)
Looking at it... this doesn't seem to be...

**Comment by jelly** [comment]
So it's a similiar issue in gnome-terminal, then it's easy and it's an VTE upstream bug.

**Comment by Hacksaurus** [comment]
So where do I exactly go to show this issue? I would like to think here: https://github.com/GNOME/vte
But not 100% sure...

Thank you for you help so far!

**Comment by jelly** [comment]
That would be https://bugzilla.gnome.org/ I can't find anything regarding font awesome.

**Comment by Hacksaurus** [comment]
Alright thank you!
I will certainly try to notify them once possible!

Closing this issue because this is apparently a VTE bug
