### ISSUE TITLE
Termite won't run w3m with -e options

### ISSUE THREAD

**Issue by TeenCorn** [thestinger/termite#517]
![pic1](https://raw.githubusercontent.com/TeenCorn/UbuntuMini_i3wm/master/w3m_Issue.png)

I'm trying to run w3m via key binding in i3wm but it doesn't work with the -e option. If I run it normally, meaning user@host:~$ w3m google.com, it works fine.

**Comment by packer-** [comment]
I am experiencing the same (or at least similar issue). I am running irssi (inside tmux session on my raspberry pi)... and want to attach to that session via keybind (also i3wm):

`termite -e 'ssh -t pi tmux att'`

results in:

(termite:9977): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.

**Comment by dtzWill** [comment]
Not sure if this is the same problem you're experiencing, but I ran into a
similar problem
when using a too-new version of vte-ng (0.48.2) and only when building
against musl.

Dropping vte-ng to 0.46.1 resolved the spawn-related issues for me,
since that version is before vte reworked its exec/spawn bits.

Hope this helps,

~Will

**Comment by jelly** [comment]
You need to quote the argument you want to run:
```
termite -e "w3m google.com"
```

**Comment by TeenCorn** [comment]
Thanks! I tried quotes around google.com, but never considered to do the command and the link.

**Comment by Brottweiler** [comment]
```sh
% termite -e "cal"

(termite:23425): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.
```

**Comment by jelly** [comment]
That actually works, but since there is nothing left to do the window is closed, same if you press 'q' when you execute ```termite -e "htop"```.

**Comment by Brottweiler** [comment]
Oh right, that makes sense.
