### ISSUE TITLE
Option to change cursor color based on underlying character

### ISSUE THREAD

**Issue by alexozer** [thestinger/termite#518]
Gnome Terminal does a nice thing where it indicates the cursor position by swapping the foreground and background colors of the current character. This looks especially nice when passing over syntax-highlighted code in Vim for example. It seems termite only has an option for a constant cursor color, would be it nice to have an option to vary the cursor color like this?

**Comment by Hund** [comment]
This would be an appreciated feature by me as well. :)

**Comment by teto** [comment]
seems to be the default behavior, just unset the cursor configuration. gnome-terminal is vte based too so that makes sense.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
