### ISSUE TITLE
Make doesnt work

### ISSUE THREAD

**Issue by Dimbel1** [thestinger/termite#519]
Hey guys, i tried to compile termite but i get those errors, any ideas?

`g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v12-37-g68b92d3\" -pthread -I/usr/include/vte-2.91 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng15 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/p11-kit-1 -g2 -O3 -pipe -fPIC -fno-omit-frame-pointer -fexceptions -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -Wno-missing-field-initializers -s -Wl,--as-needed -Wl,-z,relro -Wl,-z,now termite.cc -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lz -lpcre2-8 -lgnutls -o termite
termite.cc: In Funktion »void update_selection(VteTerminal*, const select_info*)«:
termite.cc:447:85: Fehler: »vte_terminal_set_selection_block_mode« wurde in diesem Gültigkeitsbereich nicht definiert
 _terminal_set_selection_block_mode(vte, select->mode == vi_mode::visual_block);
                                                                              ^
termite.cc:454:60: Fehler: »vte_terminal_select_text« wurde in diesem Gültigkeitsbereich nicht definiert
                                      cursor_col, cursor_row);
                                                            ^
termite.cc:457:74: Fehler: »vte_terminal_select_text« wurde in diesem Gültigkeitsbereich nicht definiert
                                      select->begin_col, select->begin_row);
                                                                          ^
termite.cc:463:73: Fehler: »vte_terminal_select_text« wurde in diesem Gültigkeitsbereich nicht definiert
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc:469:73: Fehler: »vte_terminal_select_text« wurde in diesem Gültigkeitsbereich nicht definiert
                                  std::max(select->begin_row, cursor_row));
                                                                         ^
termite.cc: In Funktion »void enter_command_mode(VteTerminal*, select_info*)«:
termite.cc:476:41: Fehler: »vte_terminal_disconnect_pty_read« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_disconnect_pty_read(vte);
                                         ^
termite.cc: In Funktion »void exit_command_mode(VteTerminal*, select_info*)«:
termite.cc:483:81: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
  vte_terminal_set_cursor_position(vte, select->origin_col, select->origin_row);
                                                                              ^
termite.cc:484:38: Fehler: »vte_terminal_connect_pty_read« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_connect_pty_read(vte);
                                      ^
termite.cc: In Funktion »void move(VteTerminal*, select_info*, long int, long int)«:
termite.cc:553:92: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
                        clamp(cursor_row + row, first_row(vte), last_row(vte)));
                                                                              ^
termite.cc: In Funktion »void move_to_row_start(VteTerminal*, select_info*, long int)«:
termite.cc:561:49: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_set_cursor_position(vte, 0, row);
                                                 ^
termite.cc: In Funktion »void open_selection(char*, VteTerminal*)«:
termite.cc:568:68: Fehler: »vte_terminal_get_selection« wurde in diesem Gültigkeitsbereich nicht definiert
         auto selection = make_unique(vte_terminal_get_selection(vte), g_free);
                                                                    ^
termite.cc: In Funktion »void move_backward(VteTerminal*, select_info*, F)«:
termite.cc:620:65: Fehler: es gibt keine Argumente für »vte_terminal_set_cursor_position«, die von einem Templateparameter abhängen, weshalb eine Deklaration von »vte_terminal_set_cursor_position« verfügbar sein muss [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc:620:65: Anmerkung: (mit »-fpermissive« wird G++ den Code akzeptieren, aber die Verwendung eines nicht deklarierten Namens ist veraltet)
termite.cc: In Funktion »void set_cursor_column(VteTerminal*, const select_info*, long int)«:
termite.cc:666:61: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_set_cursor_position(vte, column, cursor_row);
                                                             ^
termite.cc: In Funktion »void move_forward(VteTerminal*, select_info*, F, bool)«:
termite.cc:741:65: Fehler: es gibt keine Argumente für »vte_terminal_set_cursor_position«, die von einem Templateparameter abhängen, weshalb eine Deklaration von »vte_terminal_set_cursor_position« verfügbar sein muss [-fpermissive]
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
                                                                 ^
termite.cc: In Funktion »int main(int, char**)«:
termite.cc:1759:14: Warnung: »gboolean gtk_window_parse_geometry(GtkWindow*, const gchar*)« ist veraltet [-Wdeprecated-declarations]
         if (!gtk_window_parse_geometry(GTK_WINDOW(window), geometry)) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtkdialog.h:32:0,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from termite.cc:32:
/usr/include/gtk-3.0/gtk/gtkwindow.h:443:10: Anmerkung: hier deklariert
 gboolean gtk_window_parse_geometry   (GtkWindow   *window,
          ^~~~~~~~~~~~~~~~~~~~~~~~~
termite.cc:1759:68: Warnung: »gboolean gtk_window_parse_geometry(GtkWindow*, const gchar*)« ist veraltet [-Wdeprecated-declarations]
         if (!gtk_window_parse_geometry(GTK_WINDOW(window), geometry)) {
                                                                    ^
In file included from /usr/include/gtk-3.0/gtk/gtkdialog.h:32:0,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from termite.cc:32:
/usr/include/gtk-3.0/gtk/gtkwindow.h:443:10: Anmerkung: hier deklariert
 gboolean gtk_window_parse_geometry   (GtkWindow   *window,
          ^~~~~~~~~~~~~~~~~~~~~~~~~
termite.cc:1796:9: Warnung: »gboolean vte_terminal_spawn_sync(VteTerminal*, VtePtyFlags, const char*, char**, char**, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GPid*, GCancellable*, GError**)« ist veraltet [-Wdeprecated-declarations]
     if (vte_terminal_spawn_sync(vte, VTE_PTY_DEFAULT, nullptr, command_argv, env,
         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/vte-2.91/vte/vte.h:35:0,
                 from termite.cc:33:
/usr/include/vte-2.91/vte/vtedeprecated.h:76:10: Anmerkung: hier deklariert
 gboolean vte_terminal_spawn_sync(VteTerminal *terminal,
          ^~~~~~~~~~~~~~~~~~~~~~~
termite.cc:1798:39: Warnung: »gboolean vte_terminal_spawn_sync(VteTerminal*, VtePtyFlags, const char*, char**, char**, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GPid*, GCancellable*, GError**)« ist veraltet [-Wdeprecated-declarations]
                                 &error)) {
                                       ^
In file included from /usr/include/vte-2.91/vte/vte.h:35:0,
                 from termite.cc:33:
/usr/include/vte-2.91/vte/vtedeprecated.h:76:10: Anmerkung: hier deklariert
 gboolean vte_terminal_spawn_sync(VteTerminal *terminal,
          ^~~~~~~~~~~~~~~~~~~~~~~
termite.cc: In Instanziierung von »void move_backward(VteTerminal*, select_info*, F) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]«:
termite.cc:627:44:   required from here
termite.cc:620:37: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
termite.cc: In Instanziierung von »void move_backward(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]«:
termite.cc:631:70:   required from here
termite.cc:620:37: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
termite.cc: In Instanziierung von »void move_forward(VteTerminal*, select_info*, F, bool) [with F = bool (*)(unsigned int); VteTerminal = _VteTerminal]«:
termite.cc:748:49:   required from here
termite.cc:741:37: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
     vte_terminal_set_cursor_position(vte, cursor_col, cursor_row);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
termite.cc: In Instanziierung von »void move_forward(VteTerminal*, select_info*, F, bool) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]«:
termite.cc:752:75:   required from here
termite.cc:741:37: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
termite.cc: In Instanziierung von »void move_first(VteTerminal*, select_info*, F) [with F = std::unary_negate<std::reference_wrapper<int(unsigned int)> >; VteTerminal = _VteTerminal]«:
termite.cc:903:86:   required from here
termite.cc:656:41: Fehler: »vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert
         vte_terminal_set_cursor_position(vte, iter - codepoints, cursor_row);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:36: termite] Fehler 1
`

**Comment by jelly** [comment]
Yeah I can't really read this badly formatted output, but I suspect you don't have vte3-ng installed.

**Comment by Dimbel1** [comment]
I installed this [this](https://github.com/thestinger/vte-ng)

**Comment by jelly** [comment]
From which branch? You don't seem to compile against it seeing that: ```vte_terminal_set_cursor_position« wurde in diesem Gültigkeitsbereich nicht definiert ``` vte_terminal_set_cursor_position is not defined.

**Comment by gothistanic** [comment]
Hello,
Sorry if commenting in a closed question. I have the same issue and I wanna know how to compile vte3-ng. I have gtk 2 and gtk3 installed. 

thank you

**Comment by unclechu** [comment]
@gothistanic you need to build this first: https://github.com/thestinger/vte-ng/tree/0.48.2-ng
And _pkg-config_ files must be able to be found. You could set for example `PKG_CONFIG_PATH`, but I personally install it to `/opt/vte-ng-0.48.2` (`./configure --prefix=/opt/vte-ng-0.48.2` in vte-ng project root before `make && make install`) and create symbolic links in `/usr/local/lib64/pkgconfig` of `vte-2.91.pc` file from `/opt/vte-ng-0.48.2/lib/pkgconfig/`, might work for you too, but do not forget to also create symbolic links to `.so` files and do `ldconfig` too, see my `ls -lah` from `/usr/local/lib64`:
```
lrwxrwxrwx.  1 root root   39 Dec 14 17:01 libvte-2.91.a -> /opt/vte-ng-0.48.2-ng/lib/libvte-2.91.a
lrwxrwxrwx.  1 root root   40 Dec 14 17:01 libvte-2.91.la -> /opt/vte-ng-0.48.2-ng/lib/libvte-2.91.la
lrwxrwxrwx.  1 root root   40 Dec 14 17:01 libvte-2.91.so -> /opt/vte-ng-0.48.2-ng/lib/libvte-2.91.so
lrwxrwxrwx.  1 root root   42 Dec 14 17:01 libvte-2.91.so.0 -> /opt/vte-ng-0.48.2-ng/lib/libvte-2.91.so.0
lrwxrwxrwx.  1 root root   49 Dec 14 17:01 libvte-2.91.so.0.4800.2 -> /opt/vte-ng-0.48.2-ng/lib/libvte-2.91.so.0.4800.2
```
