### ISSUE TITLE
visual-select (highlighted) matches

### ISSUE THREAD

**Issue by D12EA177E12** [thestinger/termite#522]
You can perform a forward (/) or backward (?) search in termite, but once it highlights the matches, how can I make the cursor jump to a match where I can begin visual-select the parts I want?

Afaik, the cursor remains on the command line regardless of the mode in you're in at the time, or after, you perform the search.

**Comment by nguymin4** [comment]
@D12EA177E12 Please refer to #287

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
