### ISSUE TITLE
Build issues on fedora

### ISSUE THREAD

**Issue by schvabodka-man** [thestinger/termite#523]
Hi! I'm simply getting

```
Package vte-2.91 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.91.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vte-2.91' found
Package vte-2.91 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.91.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vte-2.91' found
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v12-37-g68b92d3\"   -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc  -o termite
termite.cc:32:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
                     ^
compilation terminated.
make: *** [termite] Error 1
Makefile:36: recipe for target 'termite' failed
```
There IS something wrong with makefile because i've both gtk and vte libs installed(with devel packages too)

**Comment by jelly** [comment]
Do you have vte or gtk installed? Since it seems like you don't have those packages.

**Comment by ctrlcctrlv** [comment]
I have a similar problem in Alpine Linux. How is this makefile intended to work?

`bash` and `sh` both say that this is invalid: `VERSION = $(shell git describe --tags)`:

```
q:~/Workspace$ VERSION=$(shell git describe --tags)
sh: shell: not found
```

Yet it still seems to work when I run `make`, but the other commands, such as `${shell pkg-config --cflags ${GTK} ${VTE}}` fail silently and result in that part of the `CXXFLAGS` argument remaining blank, causing @schvabodka-man and my failed build.

```
fredrick@q termite % export SHELL=/bin/bash
fredrick@q termite % $SHELL
q:~/Workspace/termite$ ${pkg-config --cflags ${GTK}}
bash: config: command not found
q:~/Workspace/termite$ ${shell pkg-config --cflags ${GTK}}
bash: ${shell pkg-config --cflags ${GTK}}: bad substitution
q:~/Workspace/termite$ echo $SHELL
/bin/bash
```

I have no idea under which circumstances this Makefile will work...but clearly there's something wrong with it in terms of cross-system compatibility...

**Comment by schvabodka-man** [comment]
I've gtk and i've vte3-devel installed. Did i miss something?

**Comment by Vintodrimmer** [comment]
That may not be the problem with termite's makefile, but something to do with vte.

I have similar problem on void linux with custom build template. The important part is that a couple of months ago the same exact script I'm using was working perfectly, but now it tells me that package is broken, since there is no `vte-2.91`, even though it is present in the main package tree.

Since I've been using the same termite_v12 package and the same vte3-ng_0.48.3.a I find it unlikely that the problem is with them.

**Comment by stormwatch** [comment]
I could compile successfully in Fedora after running:
$ sudo bash -c "echo -n PKG_CONFIG_PATH=/usr/local/lib/pkgconfig >> /etc/environment"

**Comment by NicTanghe** [comment]
Doing what jelly said did not fix the issue.
