### ISSUE TITLE
Temporarily override clickable urls?

### ISSUE THREAD

**Issue by josswright** [thestinger/termite#525]
I've noticed recently a few situations where I want to select part of a URL that has been output to the terminal. The trouble is that the moment I click, termite opens the full URL in my browser. (Obviously this is with clickable_url = true.)

It would be great if either there were a modifier key that would temporarily disable clicking of URLs or, alternatively, if the URL would be followed only on a click, and not a click-and-drag.

**Comment by jelly** [comment]
I'm not sure if it's easy to detect if it's a "drag", wouldn't be that hard. Temporary disabling it, could be an option or maybe a horrible idea would be holding ctrl + click for selecting and not clicking.

**Comment by layus** [comment]
Or maybe use ctrl+click to follow the link like in many applications ?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
