### ISSUE TITLE
vte_terminal_set_cursor_position not declared

### ISSUE THREAD

**Issue by betaredex** [thestinger/termite#528]
I'm trying to compile termite on Void Linux, but it keeps giving the error "'vte_terminal_set_cursor_position' was not declared in this scope." I tried versions of vte-ng from both jelly and thestinger's forks, but neither worked.
Log: https://p.teknik.io/ICgdZ

Thanks in advance.

**Comment by betaredex** [comment]
My /usr/include/vte-2.91 folder:
vte
|-vte.h
|-vtedeprecated.h
|-vteenums.h
|-vteglobals.h
|-vtemacros.h
|-vtepty.h
|-vteregex.h
|-vteterminal.h
|-vtetypebuiltins.h
|-vteversion.h

**Comment by betaredex** [comment]
Ah, my vte header files were inside another folder inside /usr/include/vte-2.91.
Solved.

**Comment by betaredex** [comment]
Just tried a manual compilation on my Arch Linux machine (with vte3-ng installed from the official repositories) and got the same error.
Log: https://p.teknik.io/HSqkS

**Comment by jelly** [comment]
It's not the same error, on Arch Linux with vte3-ng it installs fine, the warnings are not **errors**. On void however, you do not seem to correctly compile against vte3-ng.

**Comment by betaredex** [comment]
Oh, my bad. I guess I'll  do some more testing and compare the vte3-ng installation on Arch with the one on Void.

**Comment by jelly** [comment]
On Arch vte3-ng replaces vte3, while on voidlinux that might not be the true when it's installed in /usr/local/

**Comment by betaredex** [comment]
vte3 acutally isn't installed on my system, and I set it up to replace vte3 in my template. I ran diff a couple times just to test:
- vte3-ng is version 0.50.0 on my Arch system, but is 0.50.1 on my Void system
- As expected, pretty much all the binaries are different
I'll try compiling it with version 0.50.0

**Comment by betaredex** [comment]
So, 0.50.0 failed as well, and I think I've found the issue: my Void machine uses musl rather than glibc. I've seen some other people have issues with musl, has a solution been found?

**Comment by betaredex** [comment]
So 0.50.0 didn't work, but I found a forum post with an identical error: https://forum.voidlinux.eu/t/termite-terminal-package/1925/14
The strange part is that I'm using glibc, not musl.

**Comment by betaredex** [comment]
Also, I forgot to mention: I changed PREFIX to /usr with both vte3-ng and termite, and I also do not have vte3 installed.

**Comment by betaredex** [comment]
Solved, /usr/include/vte-2.91/vte should have been symlinked to /usr/include/vte

**Comment by jelly** [comment]
Maybe it's time to create a real void package for it then.

**Comment by betaredex** [comment]
From what I heard on the forums, they didn't want vte3-ng as a separate package from vte.
