### ISSUE TITLE
CTRL-SHIFT-L Reset and Clear is not clearing the scrollback buffer

### ISSUE THREAD

**Issue by tariqc80** [thestinger/termite#531]
This keyboard shortcut is not actually performing a proper reset and clear for some reason.  It seems to be correctly performing the same functionality as the `clear` command, but the scroll back history still exists if I  scroll up.  Running `reset` in the command line does a proper reset as expected.  

Is anyone else experiencing this behavior?   I'm on running Arch Linux and Termite v12

**Comment by jelly** [comment]
Correct, it does indeed not "reset" the scroll back history

**Comment by egmontkob** [comment]
Works in gnome-terminal though, so it's really not obvious to me where the bug could be.

**Comment by jelly** [comment]
Hmm it uses exactly the same code indeed, https://github.com/GNOME/gnome-terminal/blob/2f33a3630f7093fc4370f2a48437c3d2cd11a961/src/terminal-window.c#L764 but it does not work in termite. Might be due to vte3-ng, but installing vte3 doesn't make it work.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
