### ISSUE TITLE
Copy-on-select and right-click paste

### ISSUE THREAD

**Issue by Xyene** [thestinger/termite#533]
Hi,

I've been using termite for a while, but one thing that was missing for me was copying on selection and pasting on right click, functionality that I've grown used to in other terminal emulators.

I've been running this patch for this functionality:

```diff
diff --git a/termite.cc b/termite.cc
index ba1fc30..6f4edcb 100644
--- a/termite.cc
+++ b/termite.cc
@@ -470,6 +470,7 @@ static void update_selection(VteTerminal *vte, const select_info *select) {
     }
 
     vte_terminal_copy_primary(vte);
+    vte_terminal_copy_clipboard(vte);
 }
 
 static void enter_command_mode(VteTerminal *vte, select_info *select) {
@@ -1168,6 +1169,9 @@ gboolean position_overlay_cb(GtkBin *overlay, GtkWidget *widget, GdkRectangle *a
 }
 
 gboolean button_press_cb(VteTerminal *vte, GdkEventButton *event, const config_info *info) {
+    if (event->type == GDK_BUTTON_PRESS && event->button == 3) {
+        vte_terminal_paste_clipboard(vte);
+    }
     if (info->clickable_url && event->type == GDK_BUTTON_PRESS) {
 #if VTE_CHECK_VERSION (0, 49, 1)
         auto match = make_unique(vte_terminal_hyperlink_check_event(vte, (GdkEvent*)event), g_free);
```

I was wondering if there is interest in having this be supported by vanilla termite; if so, I would be happy to provide a PR with this functionality exposed by some config entries. If not, that's fine too, just wanted to check nonetheless.

**Comment by michalrus** [comment]
Please note, that this doesn’t work with mouse selections (for which `update_selection` is not called).

As a workaround, autocutsel, Parcellite, ClipIt etc. can be used to sync clipboards.

**Comment by Xyene** [comment]
Huh, interesting -- this works fine for me with mouse selections (my use-case)... perhaps it's just not doing in a "cross-platform" way.

**Comment by michalrus** [comment]
@Xyene if you mouse-select some text in Termite, and then switch to a browser and hit Ctrl+V, does it get pasted?

**Comment by Xyene** [comment]
@michalrus got home and tested with a browser (since I primarily use just the terminal), works fine.

I'm not running any extra software &mdash; the only processes executing are essentially i3, compton and polybar. However, I'm accessing this environment through an X server connection (VcXsrv) running with default settings, so perhaps that might have something to do with it.

**Comment by slackhead** [comment]
Would you please make this an option rather than the default? I've experiemented using parcelite like this for a while and it got a bit annoying to overwrite the normal clipboard. Keeping the two separate means you can have two lots of copied text at the same time, which can be very useful.

**Comment by vladsot** [comment]
`vte_terminal_copy_clipboard` has been deprecated and replaced with `vte_terminal_copy_clipboard_format`

**Comment by sshaikh** [comment]
Although I think that "select to copy" is best dealt globally with with a utility, it would be wonderful to have an option to paste on right click inside a termite window.

**Comment by sshaikh** [comment]
The "right click to paste" patch is great, thanks!

However the "select to copy" patch doesn't seem to work, probably for the reasons @michalrus 
says. In fact commenting out the vte_terminal_copy_primary call keeps the copy to primary behaviour in the terminal, so it's probably being handled by X or something.

**Comment by sshaikh** [comment]
For those of you who are finding the original patch not working because of https://github.com/thestinger/termite/issues/533#issuecomment-343682253, the actual patch should go in vte-ge, by forcing widget_copy in src/vte.cc to always use the clipboard.

I've gone the clipster way myself so that I can select-to-copy across apps.

**Comment by christophgysin** [comment]
Came here to look for a working patch, but ended up using:
```
$ wl-paste -pw wl-copy
```

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
