### ISSUE TITLE
Problem building vte-ng on Debian 9.2

### ISSUE THREAD

**Issue by DorianGeraut** [thestinger/termite#536]
Hello,

I've encountered a problem when building vte-ng as some involved python scripts seems to fail while decoding ascii...
I did install libvte-2.91-dev package

Here is the output of the build:

      Making install in src
      make[1]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng/src'
      make  install-am
      make[2]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng/src'
      make[3]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng/src'
       /bin/mkdir -p '/usr/local/lib'
       /bin/bash ../libtool   --mode=install /usr/bin/install -c   libvte-2.91.la '/usr/local/lib'
      libtool: install: /usr/bin/install -c .libs/libvte-2.91.so.0.4800.2 /usr/local/lib/libvte-2.91.so.0.4800.2
      libtool: install: (cd /usr/local/lib && { ln -s -f libvte-2.91.so.0.4800.2 libvte-2.91.so.0 || { rm -f libvte-2.91.so.0 && ln -s libvte-2.91.so.0.4800.2 libvte-2.91.so.0; }; })
      libtool: install: (cd /usr/local/lib && { ln -s -f libvte-2.91.so.0.4800.2 libvte-2.91.so || { rm -f libvte-2.91.so && ln -s libvte-2.91.so.0.4800.2 libvte-2.91.so; }; })
      libtool: install: /usr/bin/install -c .libs/libvte-2.91.lai /usr/local/lib/libvte-2.91.la
      libtool: install: /usr/bin/install -c .libs/libvte-2.91.a /usr/local/lib/libvte-2.91.a
      libtool: install: chmod 644 /usr/local/lib/libvte-2.91.a
      libtool: install: ranlib /usr/local/lib/libvte-2.91.a
      libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
      ----------------------------------------------------------------------
      Libraries have been installed in:
         /usr/local/lib
      
      If you ever happen to want to link against installed libraries
      in a given directory, LIBDIR, you must either use libtool, and
      specify the full pathname of the library, or use the '-LLIBDIR'
      flag during linking and do at least one of the following:
         - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
           during execution
         - add LIBDIR to the 'LD_RUN_PATH' environment variable
           during linking
         - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
         - have your system administrator add LIBDIR to '/etc/ld.so.conf'
      See any operating system documentation about shared libraries for
      more information, such as the ld(1) and ld.so(8) manual pages.
      ----------------------------------------------------------------------
       /bin/mkdir -p '/usr/local/etc/profile.d'
       /usr/bin/install -c -m 644 vte.sh '/usr/local/etc/profile.d'
       /bin/mkdir -p '/usr/local/include/vte-2.91/vte'
       /usr/bin/install -c -m 644 vte/vte.h vte/vtedeprecated.h vte/vteenums.h vte/vteglobals.h vte/vtemacros.h vte/vtepty.h vte/vteregex.h vte/vteterminal.h '/usr/local/include/vte-2.91/vte'
       /bin/mkdir -p '/usr/local/include/vte-2.91/vte'
       /usr/bin/install -c -m 644 vte/vtetypebuiltins.h vte/vteversion.h '/usr/local/include/vte-2.91/vte'
      make[3]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng/src'
      make[2]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng/src'
      make[1]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng/src'
      Making install in bindings
      make[1]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng/bindings'
      Making install in gir
      make[2]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng/bindings/gir'
        GISCAN   Vte-2.91.gir
      Traceback (most recent call last):
        File "/usr/bin/g-ir-scanner", line 66, in <module>
          sys.exit(scanner_main(sys.argv))
        File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 535, in scanner_main
          ss = create_source_scanner(options, args)
        File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 443, in create_source_scanner
          ss.parse_files(filenames)
        File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/sourcescanner.py", line 252, in parse_files
          self._scanner.append_filename(filename)
      UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 14: surrogates not allowed
      /usr/share/gobject-introspection-1.0/Makefile.introspection:155: recipe for target 'Vte-2.91.gir' failed
      make[2]: *** [Vte-2.91.gir] Error 1
      make[2]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng/bindings/gir'
      Makefile:448: recipe for target 'install-recursive' failed
      make[1]: *** [install-recursive] Error 1
      make[1]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng/bindings'
      Makefile:574: recipe for target 'install-recursive' failed
      make: *** [install-recursive] Error 1

**Comment by jelly** [comment]
which version of vte-ng?

**Comment by DorianGeraut** [comment]
Well I tried with the one available on your repo:

https://github.com/thestinger/vte-ng

**Comment by jelly** [comment]
I would recommend using https://github.com/thestinger/vte-ng/releases/tag/0.50.2.a

**Comment by DorianGeraut** [comment]
Sorry for the delay.
It doesn't work either, here is what "make" prompt:

```

make[1]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/glade'
make[1]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/glade'
make  all-recursive
make[1]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a'
Making all in src
make[2]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/src'
make  all-am
make[3]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/src'
make[2]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/src'
Making all in bindings
make[2]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/bindings'
Making all in gir
make[3]: Entering directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/bindings/gir'
  GISCAN   Vte-2.91.gir
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 535, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 443, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/sourcescanner.py", line 252, in parse_files
    self._scanner.append_filename(filename)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 14: surrogates not allowed
/usr/share/gobject-introspection-1.0/Makefile.introspection:155: recipe for target 'Vte-2.91.gir' failed
make[3]: *** [Vte-2.91.gir] Error 1
make[3]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/bindings/gir'
Makefile:448: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a/bindings'
Makefile:574: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dorian/Téléchargements/termite/vte-ng-0.50.2.a'
Makefile:481: recipe for target 'all' failed
make: *** [all] Error 2
```
Thank you nonetheless

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
