### ISSUE TITLE
Cannot open weechat on startup

### ISSUE THREAD

**Issue by Hritik14** [thestinger/termite#537]
I'm trying to open weechat in termite. I've tried    
` termite -e "weechat" `
` termite -e "bash -c weechat"`
Both output
`(termite:15421): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.)`

I'm running i3wm, if that matters.

**Comment by jelly** [comment]
```termite -e "weechat"``` works fine for me. So I'm not sure what the issue is. Which vte3-ng do you use?

**Comment by Hritik14** [comment]
vte3-ng 0.50.0.a-1

**Comment by Hritik14** [comment]
@Xyene I've terminfo already installed.

**Comment by jelly** [comment]
@Hritik14 silly question, but is weechat installed?

**Comment by Hritik14** [comment]
@jelly Obvious answer, Yes.

**Comment by turing-king** [comment]
termite --hold -e cmatrix
Add --hold It works but still has error

**Comment by ifohancroft** [comment]
Are you sure weechat isn't started already? I get the same error when I try to start a second instance of it and when it's not started, termite -e "weechat" works perfectly for me.

**Comment by jelly** [comment]
Closed, no response.
