### ISSUE TITLE
copied text with "control shift c" inside visual or visual block mode, is truncated

### ISSUE THREAD

**Issue by evanescente-ondine** [thestinger/termite#538]
I want to copy plenty of lines, but strangely enough the yanked text is only.. what ? 26 characters long ? it copies, INSIDE my selection, only the 26 first characters of each row. No warning nor error.
very nice behaviour...

**Comment by jelly** [comment]
In selection mode? Since selection mode works fine for me.

**Comment by evanescente-ondine** [comment]
I don't see problems anymore, I don't get what happened. Though I am certain I press the right hotkeys. Whatever, thanks.
