### ISSUE TITLE
handling of alt+something and Modfiers+Delete

### ISSUE THREAD

**Issue by evanescente-ondine** [thestinger/termite#541]
I transmit this from micro editor's github. Micro can't handle these keybindings: Alt Backspace, Alt Delete. The guys told me it could be that my terminal is handling well thoses combinations. So... Anyone wanna try micro ?
I would like to have info on the way keys event are handled in this terminal, or in any terminal for the matter, and how these are transmitted all the way to console applications.
> Perhaps there is an issue with your terminal not recognizing a meta key.

**Comment by jelly** [comment]
Do you mean this program? https://github.com/zyedidia/micro

**Comment by evanescente-ondine** [comment]
Yeah.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
