### ISSUE TITLE
cursor is not visible when using selection mode in ncurses apps

### ISSUE THREAD

**Issue by craftyguy** [thestinger/termite#545]
When running an app that uses ncurses (like `top` or `mutt`), the cursor is not visible when in termite's selection mode. Interestingly enough if using tmux's copy-mode, the cursor is visible, so this seems to be an issue with termite. I've tried setting `cursor_blink` to `on` and `off`, but neither setting helps.

**Comment by craftyguy** [comment]
Interestingly enough, I've found that if I set TERM like this, then I can see the cursor when running ncurses apps!

`$ TERM=xterm-color top`

**Comment by egmontkob** [comment]
FYI: `top` is not based on `ncurses` (at least on my system, Ubuntu).

**Comment by craftyguy** [comment]
It is on Arch. The point is, ncurses apps cause this. Termite should make the cursor visible again if in selection mode, like tmux does.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
