### ISSUE TITLE
Search with single result loses highlight when using `n/N` 

### ISSUE THREAD

**Issue by goodboy** [thestinger/termite#547]
When conducting a search from selection mode where there is only one result if you subsequently type `n` or `N` the highlighting disappears and is never to return. IMHO the highlight should remain on the single match signalling to the user that this is the lone result.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
