### ISSUE TITLE
Possible outdated information in README file: padding setting not working

### ISSUE THREAD

**Issue by lorenzonodari** [thestinger/termite#548]
I tried to set the padding the way specified in the README but i can't see any difference at all.
I'm not a gtk expert so there might be something i'm doing wrong, but as far as i read from the README file it looked pretty easy to set the padding that way. Is maybe the information outdated?

**Comment by Narrat** [comment]
There were in the past different ways to set the padding (or at least what was written in the CSS file).
So it would be nice if you could tell us what is your termite and gtk 3 versii. Or alternatively look at the history of the Readme.

**Comment by lorenzonodari** [comment]
I ran a full system upgrade and now everything works as expected, don't know what was causing the problem... Sorry for opening a useless issue!
