### ISSUE TITLE
Resizing "eats" lines

### ISSUE THREAD

**Issue by andreyorst** [thestinger/termite#549]
Hello. Weird behaviour i found - when resizing the terminal with long lines of text, on rewrap termite eats  previous line. Check this gif:
![ezgif-2-ee00ccda95](https://user-images.githubusercontent.com/19470159/34073782-dfbe306c-e2b2-11e7-9054-38d8523aeaea.gif)

**Comment by egmontkob** [comment]
It's not termite (VTE) itself eating those lines. As you can see, the problem only occurs right above the prompt, and it won't occur at all if you have a utility such as "cat" running.

Your shell is notified about each resize event, and in turn, it decides redisplay the prompt on every resize step. This is where the shell emits escape sequences that move the cursor a bit further up than necessary.

There's also an inevitable race condition in the game. If you're crazily dragging the window border, by the time your shell repaints its stuff according to the new window width the terminal emulator's size might have changed again. So the shell prints its prompt in a false belief about the size, it wraps at a point unexpected by the shell, so the shell hopelessly loses track of the cursor's position.

The only proper solution I can think of is to add options to popular shells (bash, zsh) not to redisplay the prompt on resize at all, instead assume that the terminal emulator rewraps it correctly for them.

**Comment by andreyorst** [comment]
Hmm, I guess you right, installed a couple of other terminals, like Konsole and xfce4-treminal, they both have same issue. Closing then.
