### ISSUE TITLE
SSH from termite to zsh

### ISSUE THREAD

**Issue by eoli3n** [thestinger/termite#550]
Hi,
When ssh from termite to a host which has in his .zshrc
```
if [[ $TERM == xterm-termite ]]; then
  . /etc/profile.d/vte.sh
  __vte_osc7
fi
```
I get an error
```
❯ vagrant ssh
Last login: Wed Dec 20 04:13:15 2017 from 10.0.2.2
/home/vagrant/.zshrc:69: command not found: __vte_osc7
```
How to fix it please ?

**Comment by jelly** [comment]
Does /etc/profile.d/vte.sh exists on your server?

**Comment by eoli3n** [comment]
```
~ vagrant@archlinux
❯ file /etc/profile.d/vte.sh
/etc/profile.d/vte.sh: UTF-8 Unicode text
```

**Comment by eoli3n** [comment]
I have this problem on many server, since i use termite (maybe 1 year) just created this issue late

**Comment by jelly** [comment]
Hmm it indeed does not work in an ssh session.

**Comment by eoli3n** [comment]
What is that vte.sh script ? why isn't it usefull on ssh session ?

If it's really not usefull through ssh session
Maybe you should update readme with
```
if [[ $TERM == xterm-termite ]] && [[ -z "$SSH_CLIENT" ]] || [[ -z "$SSH_TTY" ]]; then
  . /etc/profile.d/vte.sh
  __vte_osc7
fi
```
It works with it.

**Comment by egmontkob** [comment]
`/etc/profile.d/vte.sh` (or `/etc/profile.d/vte-2.91.sh`) checks for `$VTE_VERSION` and only does stuff if it's present. This variable is set by VTE, but not forwarded by ssh, that is, not present on your remote system.

OSC 7 is pointless over ssh. Its purpose is to be able to open a new terminal in the current directory of the current one. This cannot be done if the current terminal's notion of the working directory is a remote one.

While at it, I don't see the point in executing `__vte_osc7` in the local case either. `vte.sh` hooks up `__vte_osc7` to the prompt, so it's executed always when the prompt is displayed. I see no point in emitting it explicitly, just before the shell displays its initial prompt which will also emit it.

(`vte.sh` sucks by the way, we have like 2 or 3 VTE bugreports to refactor them. We'll probably do it at one point.)

**Comment by eoli3n** [comment]
Ok, thx !
