### ISSUE TITLE
How could I add border raduis.

### ISSUE THREAD

**Issue by bluedrack** [thestinger/termite#551]
I saw the issue with the padding but nothing with the border raduis. Is it possible ?
Thank you.

**Comment by andyperisho** [comment]
Same here. I created the file `$HOME/.config/gtk-3.0/gtk.css` that contains
```
.termite {
  padding: 20px;
  border-radius: 20px;
}
```

The padding works, but not the border-radius!

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
