### ISSUE TITLE
font size control doesn't work. Nothing happens

### ISSUE THREAD

**Issue by evanescente-ondine** [thestinger/termite#552]
These commands don't work anymore, but they used too:              
       ctrl-+ increase font size
       ctrl-- decrease font size
       ctrl-= reset font size to default

No bug, but it simply does nothing. My version is termite v12-43-g1f9ab29

**Comment by jelly** [comment]
Works fine for me. BTW the latest version of temite is v13.

**Comment by evanescente-ondine** [comment]
Though I do have i3 too, works with v13 ! thanks !
