### ISSUE TITLE
border colors are black with 2bwm window manager

### ISSUE THREAD

**Issue by dagnachewa** [thestinger/termite#554]
Hello 
after installing latest termite, my borders went black,
the borders respected the 2bwm color border codes until the latest termite install

**Comment by jelly** [comment]
Screenshot? Vte3-ng version?

**Comment by dagnachewa** [comment]
yes vte3-ng version
![2018-01-09-050427_1920x1080_scrot](https://user-images.githubusercontent.com/2177069/34715451-bdc188d8-f4fa-11e7-9817-8a81dadd4f49.png)

**Comment by jelly** [comment]
But which vte3-ng?

**Comment by dagnachewa** [comment]
vte3-ng-0.50.2.a-1-x86_64.pkg.tar.xz, 
I downgraded to 
vte3-ng-**0.50.0.a-1**-x86_64.pkg.tar.xz 
and recompiled termite, it had the same black borders

**Comment by jelly** [comment]
So it was always reproducible?

**Comment by dagnachewa** [comment]
termite was working very well until update, now am with st terminal. Thanks for your time,
I dont's want to waste your time, I just don't understand why termite stoped using 2bwm colors when it used too until yesterday.

**Comment by jelly** [comment]
Can't reproduce.

**Comment by dagnachewa** [comment]
I have still the problem

On Sat, Feb 10, 2018 at 8:10 PM, jelle van der Waa <notifications@github.com
