### ISSUE TITLE
Colorscheme changes on regex

### ISSUE THREAD

**Issue by shibumi** [thestinger/termite#555]
Hello,
I would like to propose a feature from iTerm2. In iTerm2 it's possible to change the colorscheme when a specific regex occurs. This is useful when somebody ssh's into a server with root or triggers sudo/su.

Example:
```
user@client $ #blue background 
user@client $ sudo -i #blue background
root@client #  #red background
root@client # ssh root@server #red background
root@server # #red background
root@server # ^D #red background
root@client # ^D #red background
user@client # #blue background
```

Even more advanced could be something like this: https://kpumuk.info/mac-os-x/how-to-show-ssh-host-name-on-the-iterms-background/

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
