### ISSUE TITLE
URL detection too aggressive leading to invalid results

### ISSUE THREAD

**Issue by anthraxx** [thestinger/termite#556]
The detection of URLs is too aggressive including invalid characters into the URL.
This is a common case f.e. when using parentheses to speak about a URL:

example:
```
Hey, there are awesome stats at the tracker (https://security.archlinux.org/stats).
```
This leads to a clickable URL: `https://security.archlinux.org/stats)` which is obviously wrong. Only valid characters should be considered as part of the URL. The suggested way is f.e. also used by Urxvt.

**Comment by egmontkob** [comment]
URLs can contain parentheses, e.g. https://en.wikipedia.org/wiki/The_Offspring_(album).

Is it possible to detect both kinds of URLs correctly using regular expressions? It is, but it's truly complicated. See how gnome-terminal did it: [source](https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-regex.h), [unittests](https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-regex.c), [this particular issue](https://bugzilla.gnome.org/show_bug.cgi?id=763980).

**Comment by anthraxx** [comment]
I got distracted, it indeed seems to be valid without being encoded.

So IMO how we can get the best possible result for all variants by:
check if the URL itself contains both, opening and closing parentheses. This should make all links that contain such enclosed parentheses work while still not break links even like `(for this link https://security.archlinux.org/stats)`. This is actually how Urxvt behaves and i believe is best for UX. If thats desired, i can see to get a PR.

**Comment by nemanjan00** [comment]
Urls indeed can contain parentheses, but, those should be encoded... 

I think unencoded parentheses is much rarer problem than url in parentheses...

**Comment by shibumi** [comment]
Just for reference: https://github.com/thestinger/termite/issues/463

**Comment by MaskRay** [comment]
This may be mitigated by https://github.com/thestinger/termite/pull/596
