### ISSUE TITLE
Gtk Scrollbar at wrong position when using padding

### ISSUE THREAD

**Issue by anthraxx** [thestinger/termite#558]
The padding should be defined to the inner group. Right now, it affects the whole Pane, including the scrollbar. This means that adding a padding of lets say 20px will lead to the scrollbar not being displayed at the very right and adding the padding left to it, but it will float around 20px left to the edge and the text will be exactly up to the scrollbar.
Suggested way would be to have a way to define such padding without influencing the scrollbar, leaving the scrollbar where it is and adding the padding left to it.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
