### ISSUE TITLE
Can't use some fonts I installed

### ISSUE THREAD

**Issue by Ploppz** [thestinger/termite#560]
Two fonts I installed (after which I did a reboot):
```
$ fc-list | grep scientifica
/home/ploppz/.local/share/fonts/scientifica-11.bdf: scientifica:style=Regular
$ fc-scan --format "%{foundry} : %{family}\n" /home/ploppz/.local/share/fonts/scientifica-11.bdf
nerdypepper : scientifica
$ fc-list | grep Envy
/usr/share/fonts/TTF/EnvyCodeR.ttf: Envy Code R:style=Regular
$ get-foundry /usr/share/fonts/TTF/EnvyCodeR.ttf                           
ENVY : Envy Code R
```

As you now have to write fonts in `.config/termite/config` in the format `<foundry> <name> <style> <size>`, I tried font = `ENVY 'Envy Code R Regular' 9` and `font = nerdypepper scientifica Regular 11`.

None worked. That is, termite just fell back on a default font with really bad kerning. What am I doing wrong here? `xfontsel` can find these fonts.

**Comment by thestinger** [comment]
Not able to provide support here, unfortunately.
