### ISSUE TITLE
Copying to clipboard using Ctrl+Shift+c not working?

### ISSUE THREAD

**Issue by STiiiXx** [thestinger/termite#561]
Hello,
first of all, Termite is great and I never had any issues with it.
However, when I installed it from source (termite v13-1-g01bfd9f) on my freshly set up Ubuntu 17.10 Virtual Machine today, I realized that copying selected text to clipboard using ctrl+shift+c in insert mode does not seem to work.
When I use y to yank the text in command mode, it works.
Also pasting to termite's insert mode using ctrl+shift+v works.
Also it works as usual in gnome-terminal.
I have another machine running an older build of termite and it has always worked so far (termite v13).

So what happens is that when I am in insert mode, select some text and press ctrl+shift+c, I just get a ^C sequence printed out and a new line.

I am not sure if I am overlooking something or missing some package in my setup, but I love Termite and really want to know what the issue with this is.
So sorry for maybe asking something stupid :)

**Comment by STiiiXx** [comment]
Update: So I managed to install v13 on the same machine using _git clone --branch v13 --recursive https://github.com/thestinger/termite_ and it works perfectly. So this may indeed be a bug in the newest build.
I did not want to annoy you, sorry. :)

**Comment by vighneshiyer** [comment]
I noticed the same issue when compiling Termite from the latest source. I am using Ubuntu 16.04.3. gnome-terminal and xfce4-terminal can copy to the clipboard just fine. Termite v13 works fine.

**Comment by wimstefan** [comment]
Hmm - the same happens here as well with `termite v13-1-g01bfd9f` and vte-ng 0.48.2.9999 installed on a Gentoo system. Is there any workaround already?

**Comment by nashe** [comment]
This issue was introduced by https://github.com/thestinger/termite/commit/01bfd9f9ea8d0d05b063bc43a5121860ccc8d8a2, since it works as expected when building  https://github.com/thestinger/termite/commit/e9e72d089384ef785a9050ef409ecc45a6664834.

**Comment by jelly** [comment]
Fixed in master 01bfd9f9ea8d0d05b063bc43a5121860ccc8d8a2

**Comment by Narrat** [comment]
You point to the commit, where the breakage occured.
So just want to note https://github.com/thestinger/termite/commit/051e2fbf6692dbd5a08858dd6fdebeae2656680e is the applied fix
