### ISSUE TITLE
No mouse support on manually compiled termite, Ubuntu 16.04

### ISSUE THREAD

**Issue by PiQuer** [thestinger/termite#570]
I manually compiled vte-ng (0.48.2-5-g37d02b6, ./autogen.sh && make && sudo checkinstall) and termite (v13-7-ga4af9e7, make && sudo checkinstall) on Ubuntu 16.04. libgtk-3 is version 3.18.9.

I cannot select text with the mouse or interact with terminal applications such as tmux (tried in input and selection mode). Both works with the vte-2.91 terminal. Termite config only defines colors and font. Any hints what I might be missing?

**Comment by PiQuer** [comment]
Just noticed there are more recent tags on the vte-ng repo than the default branch, but I get the same behaviour with vte-ng 0.50.2.a.

**Comment by dotdash** [comment]
Fixed by #568

**Comment by PiQuer** [comment]
Thanks for the quick fix! New to termite and already :heart:ing it.
