### ISSUE TITLE
What does ctrl+shift+e do, and why does it make the cursor invisible?

### ISSUE THREAD

**Issue by iirelu** [thestinger/termite#572]
I keep pressing it by accident whilst swapping between a terminal and something that needs me to press ctrl+shift+e a lot. I couldn't find it in the list of keybinds, and I have no idea how to fix the terminal after i enter it.

**Comment by Narrat** [comment]
It comes from vte (as I could reproduce this with the vte test terminal).
And it seems to be the input method for emojis

**Comment by egmontkob** [comment]
For me, all GTK+ apps suffer from this same problem. After a Ctrl+Shift+E, the next 9 keypresses (or up to the first Space or Enter) are swallowed.

**Comment by Narrat** [comment]
Yeah, it waits for a valid emoji name (grin worked for me)

**Comment by egmontkob** [comment]
There should really be some visual feedback, like with Ctrl+Shift+U, I guess.

Since there's none in other GTK+ apps either, I'm not sure if Termite or VTE could/should do anything here.

**Comment by egmontkob** [comment]
According to https://developer.gnome.org/gtk3/3.22/GtkIMContextSimple.html, a mere thirty-some emojis are supported, which is IMO hardly useful.

This one looks much more usable: https://fedoramagazine.org/using-favorite-emoji-fedora-25/, although that's not how it works for me in GTK+ apps (mind you, I'm on Ubuntu Artful and Unity 7).

**Comment by Narrat** [comment]
What kind of visual feedback? At least in termite, the visual indication is the same for me for both modes. One with the underlined u and the other with the underlined e.
Although without knowing what those mean I would be irritiated. Like the first time I accidently opened the vi editor :D

**Comment by egmontkob** [comment]
I don't have absolutely anything, not even an underlined e. Glad to hear it's better for you :)

**Comment by avdv** [comment]
FYI, according to https://blog.gtk.org/2018/06/23/a-gtk-3-update/ highlights of Gtk+ 3.23.0 are more emoji features:

* Support a completion popup for Emoji
* Drop Ctrl-Shift-e shortcut
