### ISSUE TITLE
Add zoom option similar to gnome-terminal

### ISSUE THREAD

**Issue by anoopar112** [thestinger/termite#577]
i used to launch gnome-terminal with a --zoom flag , is there a similar feature in termite? i can zoom out using the keyboard combination CTRL - but can't seem to see an option to launch it with a default zoom . Anyone know of anything similar in termite?

**Comment by gitgeeray** [comment]
would like to know as well

**Comment by paddyoneill** [comment]
Increase the font size in you config

**Comment by yymirr** [comment]
I'm mostly using Bitmap fonts, those would render badly if the font get too big.

**Comment by jelly** [comment]
There is no zoom option nor configuration option (I just closed that ticket). So this needs to be written.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
