### ISSUE TITLE
GChildWatchSource error

### ISSUE THREAD

**Issue by rieje** [thestinger/termite#578]
I'm getting the following error when I execute the script containing the command `xsel -b > "${file}" && termite -e "nvim ${file}" && cat "${file}"  | xsel -b -i`:

> (termite:18928): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.

Is this intended?

**Comment by jelly** [comment]
Standard error from Glib, not harmful.
