### ISSUE TITLE
can not open file in file manager

### ISSUE THREAD

**Issue by kenardes** [thestinger/termite#579]
previously when i'm still using xfce4-terminal as default terminal, i can directly open file in file manager using neovim by double click or right click menu, but now when i set termite as default terminal it just produce blank page in neovim window ( i can open the same file with neovim in terminal emulator)

**Comment by rhssk** [comment]
Try one of those:

In Thunar as a custom action:
`termite --exec="nvim %f"`

or in neovim.desktop:
`Exec=termite --exec="nvim %f"`

**Comment by Limero** [comment]
It does not work for me neither in thunar, error message "Failed to execute child process "xterm" (No such file or directory).".

Right clicking and doing "Open Terminal Here" opens termite as usual, so thunar is aware about termite.

**Comment by jelly** [comment]
@Limero @kenardes have you tried @rhssk's suggestion?
