### ISSUE TITLE
"no directory uri set" even with vte.sh

### ISSUE THREAD

**Issue by Expeto** [thestinger/termite#580]
Hello,
Been using the termite for a while and I have been loving it so far.

But I couldn't get ctrl-shift-t functionality to work. I have added vte.sh to my bash rc as in readme. 

> if [[ $TERM == xterm-termite ]]; then
>  . /etc/profile.d/vte.sh
>  __vte_prompt_command
> fi

I'm using arch with 4.9.77-1-lts. 
> [a@host tmp]$ echo $PROMPT_COMMAND
> __vte_prompt_command

Am I missing somthing?

**Comment by Expeto** [comment]
Workaround ;
termite -d `pwd`
Add as alias, call whenever you need. Easier on wrists than ctrl-shift-t.

**Comment by jelly** [comment]
This feature still works for me, which version does not work?

**Comment by Expeto** [comment]
termite v13
vte 2.91
