### ISSUE TITLE
[Feature req] Add support for drag and drop path

### ISSUE THREAD

**Issue by Limero** [thestinger/termite#581]
In xfce4-terminal and gnome-terminal, if you drag a file from a GUI based file browser (such as thunar or nautilus) to a terminal window, the path of the file/directory will be entered in the terminal.

This is a very useful feature and something I really miss in termite.

**Comment by jelly** [comment]
Is that supported in gnome-terminal, if not it might not be easy to add. I also don't see much benefit in adding this feature, since termite is mostly used in tiling wm's.

**Comment by Limero** [comment]
Yes, it's supported in gnome-terminal. It's still an useful feature in tiling wm's, if you use a regular file browser.

**Comment by hnicke** [comment]
I'd also love to see this feature. Sometimes it makes integration between GUI and terminal apps much easier.

**Comment by teto** [comment]
I am using an application without filename completion right now and such a feature would be very helpful though I've no idea of the technical complexity.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
