### ISSUE TITLE
Weird spacing on right side

### ISSUE THREAD

**Issue by thatnerdjosh** [thestinger/termite#583]
I am noticing in any full screen application, like vim or emacs I see a column on the far right side which isn't filled... I have set in my gtk conf to zero padding and it is still there

![2018-03-14-154328_1920x1080_scrot](https://user-images.githubusercontent.com/5251847/37434997-bec04518-279e-11e8-9a17-46fbce6e3c79.png)

**Comment by rawatashwin** [comment]
I can comfirm this problem, to reproduce install any theme in vim which makes background opaque, or different colour than your terminal background, try gruvbox.
![nvim-screenshot](https://user-images.githubusercontent.com/13271336/41143192-0c2e5672-6b16-11e8-961f-cea66370b247.png)
I'm using arch with i3-gaps. I have created a css class in gtk.css as well, making padding 0.
Look at extreme right side of the image, you'll see gap between nvim and window border.

**Comment by yw662** [comment]
confirmed also.
looks like a border or padding that cannot be removed.

**Comment by oxodao** [comment]
Any update on this ? I am also experiencing it unfortunately..

![Image](https://u.oxodao.fr/i/1547805761.png)

**Comment by eknowlton** [comment]
I am also experiencing this. It's a real eye sore.  I have nothing other than that to contribute though.

**Comment by Recidiviste** [comment]
Same for me, when using a colorschemes in neovim, there is a strange space between the window border and the background of neovim. It also happen down of the terminal
![sp](https://user-images.githubusercontent.com/46760804/56947173-9986eb80-6b2c-11e9-90cf-2e1e0ae99b61.png)

**Comment by man9ourah** [comment]
I was able to make this go away by setting `size_hints = true` in the config file.

I guess this occurs if the terminal width is not a multiple of the cell size.

**Comment by AndreSouzaAbreu** [comment]
I had the same issue and fix it by setting padding to 0 as follows in `~.config/gtk-3.0/gtk.css`

```
.termite {
    padding: 0;
}
```

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
