### ISSUE TITLE
Alt modifier not responding as expected

### ISSUE THREAD

**Issue by severoraz** [thestinger/termite#585]
I have some key bindings with the Alt modifier (aka Meta), but they don't work in termite. I'm unsure as to whether this is a bug for termite or some underlying library, or whether it is isolated to my experience entirely. Can somebody confirm this?

**Comment by paddyoneill** [comment]
Can you provide some more information on the key binding? Where they are set, what they do,etc...?

**Comment by jelly** [comment]
Closed, no response.
