### ISSUE TITLE
[Question] zoom option

### ISSUE THREAD

**Issue by flatusv** [thestinger/termite#586]
Can we have a zoom option like in gnome-terminal?

**Comment by anbenson** [comment]
From the README:
 ctrl-+              increase font size
 ctrl--               decrease font size
 ctrl-=              reset font size to default

I think this is equivalent.

**Comment by gitgeeray** [comment]
Sorry i think i wasn' t precise enough. I meant can we set this in the config so when invoking the terminal, it appears zoomed.

**Comment by paddyoneill** [comment]
Just increase the font size in the config

font = Monospace 13

**Comment by jelly** [comment]
It makes no sense to to set the default zoom level in my opinion.

**Comment by MahrezBH** [comment]
Try to use Ctrl + '-' (not '-' in Numpad) to zoom out 
and Ctrl + '+' (which front of Backspace)
