### ISSUE TITLE
Is it possible to have termite alert when a command finishes?

### ISSUE THREAD

**Issue by stevenroose** [thestinger/termite#589]
It would be nice to have an option to make termite "ask attention" (so that the window manager can make it red or blinking or whatever) when a longer-running command finishes. Or basically when a command finishes and the window is not focused.

**Comment by jelly** [comment]
This works for me, for example weechat does this when it's not focused. I assume this just the terminal beep:
```sleep 5; echo -e "\a```

**Comment by jelly** [comment]
Is the following option set to false? ```urgent_on_bell = false```  or does awesomewm not suppor the terminal beep?

**Comment by stevenroose** [comment]
It does support it for f.e. WeeChat. I just set `urgent_on_bell = true`
explicitly and it didn't change. Strange. Are there different "urgency
levels" in terminal beeps?

On Fri, Apr 20, 2018 at 6:26 PM, jelle van der Waa <notifications@github.com

**Comment by jelly** [comment]
I don't think there are different levels and not sure why it wouldn't work in AwesomeWM.
