### ISSUE TITLE
[Feature improvement request] Update title with sub-process name

### ISSUE THREAD

**Issue by TLogiviere** [thestinger/termite#593]
Hello thestinger & associates,
Using the quick termite (V.13-3 with dynamic_title) in i3wm may turn out to be a bit frustrating if one needs to land on the right instance when many of it exist.
An example: there is 5 termite windows running in different containers or workspaces.
One want to get the termite running process X that is living in another i3 container or workspace alongside with 2 others. Then, successful switching becomes a chance action or a trial & error + correction process.
So here is a proposition: dynamic_title could also take into account the information exhibited by the running sub-processes to enrich termite window title (WM_NAME(STRING) and _NET_WM_NAME(UTF8_STRING) in i3wm).
e.g. the name of the first one or the active one when in a Screen window ? Or something I didn't though of ?
What do you think ?
Thank you for your time.

**Comment by jelly** [comment]
I'm not sure what the issue is or requested feature is. Show the running process in the running termite shell?

This should work fine if your bash or zsh is set up correctly.

**Comment by TLogiviere** [comment]
Yup, its definitely not showing the process info, only changes of $PS1.
I will look into config files then. Thank you.
