### ISSUE TITLE
Don't match unpaired `)` in url_regex.hh URLPATH

### ISSUE THREAD

**Issue by MaskRay** [thestinger/termite#594]
For common Markdown link notation `[xxx](https://xx/xx)`, `https://xx/xx)` will be recognized as an URL. It will be better to reject unpaired closing parenthesis `)`. I understand that `()` are legal in URL but the Markdown notation is so common that probably requires a differential treatment.

```diff
--- a/url_regex.hh                                                                                                                      
+++ b/url_regex.hh                                                                                                                      
@@ -9,8 +9,10 @@
 #define PORT            "(?:\\:[[:digit:]]{1,5})?"
 #define SCHEME          "(?:[[:alpha:]][+-.[:alnum:]]*:)"
 #define USERPASS        USERCHARS_CLASS "+(?:\\:" PASSCHARS_CLASS "+)?"
-#define URLPATH         "(?:/[[:alnum:]\\Q-_.!~*'();/?:@&=+$,#%\\E]*)?"
+#define URLPATH         "(?:/[[:alnum:]\\Q-_.!~*';/?:@&=+$,#%\\E]*)?"

-const char * const url_regex = SCHEME "//(?:" USERPASS "\\@)?" HOST PORT URLPATH;
+const char * const url_regex = SCHEME "//(?:" USERPASS "\\@)?" HOST PORT URLPATH
```

**Comment by MaskRay** [comment]
Other improvement could be skipping trailing `.` or `,` which is also common but not generally intended as part of the URL.

**Comment by egmontkob** [comment]
> Markdown notation is so common

So is Wikipedia's use of `blah_(disambiguating_stuff)` in URLs, so it's a truly tricky issue.

See also #556 and further links from that.

**Comment by MaskRay** [comment]
@egmontkob How about #596

**Comment by egmontkob** [comment]
I'm not a termite developer, so I'm just making random comments but won't make decisions or do code reviews. Let's wait for termite's developer to chime in.

**Comment by jelly** [comment]
Seems a duplicate of #556
