### ISSUE TITLE
--class argument not working?

### ISSUE THREAD

**Issue by tardypad** [thestinger/termite#595]
I've been trying to use the `--class` argument but without success within Sway WM on Arch Linux.
Whatever I pass to it, when I analyze the windows tree the class is set to `"termite"`

I've noticed the same problem on Gnome Terminal (which I understood share the same VTE component)
However I tried some other GTK applications (GIMP, inkscape, firefox) and there it was working correctly

I'm trying to figure out where the problem lies, whether in termite, VTE, Sway or something else

Can someone with other WM / distro /... try it and report if it works?

**Comment by emersion** [comment]
The window class is an X11 thing, it won't work with native Wayland apps.

**Comment by tardypad** [comment]
OK thanks for the explanation
I was not aware of this
