### ISSUE TITLE
[Question] Is it possible to add secondary font (for icons)?

### ISSUE THREAD

**Issue by MrEvilCookie** [thestinger/termite#597]
I use curie (upscaled scientifica) as my main termite font, but it doesen't have icons, that lemon font has so it uses default font for icons. Is it possible to do something like
```
   font-0 = curie 10
   font-1 = lemon 10
```
like in polybar config?
![mess](https://user-images.githubusercontent.com/20132158/39756492-8b571c92-52d2-11e8-9c10-143b11f2b150.png)

**Comment by MrEvilCookie** [comment]
Thanks, it kind of works now, icons work but now text is super small, changing size in config doesen't help.

**Comment by paddyoneill** [comment]
Just looked more into this and it should only be necessary to specify the text font. Fontconfig should handle fallback if a glyph is not found in that font. 
See #262 and #389
