### ISSUE TITLE
Nerd Font Hack Not Rendering Correctly

### ISSUE THREAD

**Issue by sirplatypos** [thestinger/termite#598]
This messed with my head for a while, but I believe I have it right this time.  I compared the Hack font to its nerd font counterpart in termite.  The regular font is fine, but the nerd font is having issues.  I compared this against what the fonts look like in my titlebar in i3wm.

This photo is when both the titlebar and the terminal use the nerd font at size 11: 
![image](https://user-images.githubusercontent.com/32854229/39847403-6c8f948a-53cf-11e8-82b8-49d79aabb0a2.png)

This photo is when the regular font is used in the terminal, and is identical to the nerd font in the titlebar: 
![image](https://user-images.githubusercontent.com/32854229/39847429-8e803b6c-53cf-11e8-971d-28b43f332a0e.png)
This has made it apparent that the terminal is having issues rendering the nerd font, but not the regular font.  Other things such as i3 do not seem to have the same issue.

**Comment by jelly** [comment]
Sadly, no configuration was provided?? So how did you specify it..

```
font = Hack Nerd Font 12
```
That seems to work fine for me

**Comment by sirplatypos** [comment]
Is there a setting or plugin that may be necessary?

**Comment by jelly** [comment]
There is no plugin framework so I don't understand that suggestion. But the font should be configured by for example:

```fc-list | grep -i termi```

```font = xos4 Terminus 12px```

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
