### ISSUE TITLE
Unicode Block Elements - Shades not rendering correctly

### ISSUE THREAD

**Issue by dlrn** [thestinger/termite#602]
Light, medium and dark shades (░ -  ▒ - ▓) are not working as they supposed to be.

[Block Elements (wikipedia)](https://en.wikipedia.org/wiki/Block_Elements)

![bep](https://user-images.githubusercontent.com/39781299/40779003-a0bbb634-64d3-11e8-86d2-b8196cad880b.jpg)

![om](https://user-images.githubusercontent.com/39781299/40779053-cbf7d36e-64d3-11e8-868b-4d708e991908.jpg)

**Comment by egmontkob** [comment]
Upstream: [VTE 778122](https://bugzilla.gnome.org/show_bug.cgi?id=778122)
