### ISSUE TITLE
Sequence and ZWJ Emoji Support

### ISSUE THREAD

**Issue by defektive** [thestinger/termite#603]
Not sure how hard this would be, but it'd be awesome to be able have emoji sequences and ZWJ support. 

- 🇺🇸 https://emojipedia.org/flag-for-united-states/
- 👨🏽‍⚕️  https://emojipedia.org/male-health-worker-type-4/
- 👩🏿‍💻 https://emojipedia.org/female-technologist-type-6/

https://emojipedia.org/emoji-zwj-sequences/
https://emojipedia.org/zero-width-joiner/

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
