### ISSUE TITLE
How can I enable middle-click pasting?

### ISSUE THREAD

**Issue by ifschleife** [thestinger/termite#604]
I guess this is more like a question:
Mouse selection and middle-click pasting works inside termite. But if text is selected in a different application, like a browser, it can't be pasted into termite by middle clicking. The opposite is true as well, text that is selected in termite can't be middle-click pasted into the browser.
ctrl+shift+v works fine.
So is there a setting that I didn't see? Or does it have to be configured somewhere else?
Or is it intentional?

I'm running termite on archlinux/wayland/sway. If I try the same in Terminology it works fine, so I assume I'm not missing a package or something(?)

**Comment by jelly** [comment]
It's probably due to the lack of synchronisation of the two clipboards, although I don't know how that works in wayland.

**Comment by ifschleife** [comment]
Oh right, thank you. That seems like the problem. I also didn't realize terminology was using xwayland, that's why it works there.
So case closed, this has nothing to do with termite.
