### ISSUE TITLE
Shift+F7 not working

### ISSUE THREAD

**Issue by gdalex** [thestinger/termite#606]
Hello,

I use mc to browse and edit files.
When editing, F7 allows to me to search for a text. Shift+F7 goes to the next match.

I've noticed that in Termite, Shift+F7 does not work.
Using gnome-terminal, Shift+F7 works fine.

Is Termite intercepting the Shift+F keys? If so, how can I change that?

Thanks
George

**Comment by gdalex** [comment]
I just realized that the functions are shifted to the left by 2.
Ex: in gnome-terminal  in termite
      shift+f7       =           shift+f5
      shift+f4       =           shift+f2
etc

**Comment by egmontkob** [comment]
(Disclaimer: I'm not a Termite developer.)

> Is Termite intercepting the Shift+F keys?

I really don't think so.

However, it sets `$TERM` to a different value, and ships its own corresponding terminfo entry `xterm-termite`. I guess that's the culprit.

**Comment by gdalex** [comment]
Hi egmontkob,  you're right. Changing TERM to xterm-256color fixed the problem.
Do you know if there's a way to instruct termite to use xterm-256color for TERM?

**Comment by manzerbredes** [comment]
Hello,
I have a quite similar problem on termite when using midnight commander.
Actually, pressing Shift+F6 do the wrong key combination. Even after using TERM with "xterm-termite".

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
