### ISSUE TITLE
Font being rendered incorrectly

### ISSUE THREAD

**Issue by pltrz** [thestinger/termite#609]
I am having an issue rendering the SourceCodePro font (I tried the `.ttf` as well as the `.otf` versions. Not any 'patched' version, just vanilla straight from [the official repository](https://github.com/adobe-fonts/source-code-pro/releases)). Specifically, any bolded text seems to be squished slightly upwards. I am not sure if this may be somehow related to #598.

Here are two images to showcase the problem:

![2018-06-08-230353_749x608_scrot](https://user-images.githubusercontent.com/20757930/41187150-98cfe432-6b71-11e8-928b-812355279f79.png)
![2018-06-08-230537_749x508_scrot](https://user-images.githubusercontent.com/20757930/41187151-98e2bc74-6b71-11e8-8e8a-b9b7668fb83b.png)

In the first screenshot, I selected some text just to show the height of the line in comparison to the bolded area of the font.

This does not happen with `rxvt-unicode`.

**Comment by egmontkob** [comment]
See [VTE 794672](https://bugzilla.gnome.org/show_bug.cgi?id=794672), maybe removing and reinstalling the font helps you too.

**Comment by platerza** [comment]
Just tried that, with no success

**Comment by platerza** [comment]
^ don't mind that. was an accident

**Comment by DrDonkey** [comment]
System appearance rendering setting? Anti-aliasing and stuff?
