### ISSUE TITLE
URL is not accepting Firefox profile specified in config

### ISSUE THREAD

**Issue by M4NH3X** [thestinger/termite#611]
Termite v13-3
Firefox v60.0.2

I have two profiles in Firefox, one is the default and another one named joshy. In the termite config
`browser = firefox -p joshy`

Above doesn't seems to work, and if I recall correctly it used to work earlier. I have rechecked the profile name in Firefox and in config, it's the same. Don't know if the issue is with Firefox/Termite or in my config.

If I comment out 'browser' in the config, it seems to open my default Firefox profile, while if I specify it then it doesn't seems to open URL's at all.

**Comment by jelly** [comment]
if you comment out browser, it will use the $BROWSER env variable.

**Comment by jelly** [comment]
This is expected since the $BROWSER or browser config option has to be a binary and doesn't take arguments. See the error in the console
```error launching 'firefox -p none': Failed to execute child process “firefox -p none” (No such file or directory)```

If you want to specify a specific profile, you'll have to use a wrapper script.

**Comment by M4NH3X** [comment]
Got curious since it used work to on older versions, hence thought there might be an issue. I will use a wrapper script as suggested. Thanks!
