### ISSUE TITLE
Rows too tall after an update

### ISSUE THREAD

**Issue by fread2281** [thestinger/termite#612]
Font is `font = DejaVu Sans Mono 10`

Before:
![2018-06-22-115524_1308x724_scrot](https://user-images.githubusercontent.com/985195/41791538-369707d0-7613-11e8-83f4-ef5a8dd6af47.png)
After:
![2018-06-22-115530_1308x772_scrot](https://user-images.githubusercontent.com/985195/41791548-3bad4496-7613-11e8-9432-6612b37ad199.png)

This was after an update of lots of stuff, so it's probably due to a change in fontconfig or something.

**Comment by jelly** [comment]
I must be drunk, but I hardly spot the difference.

**Comment by Narrat** [comment]
Some fontconfig update ago, with DejaVu the space between lines (or the total row, dunno) increased marginally. Was really noticeable if using floating wm and opening a terminal, which was taller than before.
But has nothing to do with termite.
