### ISSUE TITLE
Termite will not display ttf-symbola

### ISSUE THREAD

**Issue by rgarch** [thestinger/termite#615]
I've actually deleted Noto Color Emoji from my system and I did several changes to my fontconfig file just to test the issue and for some reason I can't get termite to display ttf-symbola.

Desired results: https://ptpb.pw/PHAd.png

Actual results: https://ptpb.pw/yszV.png

Every terminal I have installed displays symbola without an issue except termite.

**Comment by jelly** [comment]
How did you configure the font in termite? And did you update your font cache with `fc-cache`.

**Comment by rgarch** [comment]
In the termite configuration I have "font = Source Code Pro 15px" and I've actually used just "Source Code Pro" and variations of that with the same results every time. Also, yes I did a fc-cache after removing the noto emoji color font. I even experimented to see if symbola would show up even if I put it as the font and it still displayed the noto fonts regardless.

**Comment by rgarch** [comment]
Apparently even though I removed the Noto fonts and updated the cache I found duplicate files somewhere and removed them. Finally I can confirm ttf-symbola is displayed in termite.
