### ISSUE TITLE
bold colors inside tmux are not consistent with behavior outside tmux

### ISSUE THREAD

**Issue by jshap70** [thestinger/termite#616]
See below for an example comparing w/ gnome-terminal inside and outside tmux.

![hello](https://imgur.com/gDUsKO0.jpg)

The point of interest is the top left terminal's 6th row down: "Bold system colors". The colors don't match the output from all of the other terminals. It's acting like the behavior of "bold text uses bright colors" from gnome-terminal inside tmux but outside it is using the 0-7 colors normally. All terminals and tmux are using xterm-256color.

`bold-colors.pl` can be seen here: https://github.com/jshap70/dotfiles/blob/master/bin/bold-colors.pl

**Comment by jshap70** [comment]
possibly a duplicate of https://github.com/thestinger/termite/issues/245, but because the behavior is inconsistent I figured I'd report it.

**Comment by egmontkob** [comment]
"Show bold text in bright colors" is new in gnome-terminal 3.28 and vte 0.52.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
