### ISSUE TITLE
w3m-img (ranger image previews) don't work under wayland

### ISSUE THREAD

**Issue by includereserved** [thestinger/termite#619]
I suspect this is a problem with termite/wayland, I've tried on GNOME and swaywm with the same results, however they do work on urxvt wayland/X but only on termite under an X window manager.

**Comment by jelly** [comment]
Duplicateof https://github.com/thestinger/termite/issues/501

**Comment by includereserved** [comment]
I don't think this is a duplicate of #501. I can use urxvt under sway and the previews will work fine, but it doesn't work on termite. If I open i3 on the same machine the previews work on termite, just not on sway and GNOME.
