### ISSUE TITLE
custom keyboard binds

### ISSUE THREAD

**Issue by zeltak** [thestinger/termite#62]
First of all holly crap termite is amazing..how the hell did i not hear about this before is mind bending..but i digress :)

would it be possible to have the option to get custom keybinds? some of the defaults conflict with other cool apps i use (dunst etc)

thx alot

Z

**Comment by rpdelaney** [comment]
+1. LCTRL is stuck on my laptop, which forces me to use terminator so that I can copy-paste.

**Comment by DaveDavenport** [comment]
I started working on this:
https://github.com/DaveDavenport/termite

(I also added autotools todo building, so I can easily build it.)

Once finished I will try to pull out the keybinding stuff and make a PR.

**Comment by DaveDavenport** [comment]
First version up.  Got a problem with gtk_accelerator_parse, it seems to lowercase everything. Failing capital bindings.. will continue.

**Comment by DaveDavenport** [comment]
In my git fork you can now specify per key what mode it apply on:
```
copy-clipboard=y:!insert,<Control><Shift>c:all
```

**Comment by yacoob** [comment]
Any chance of merging @DaveDavenport's changes any time soon? `termite` looks like a very good terminal emulator, except for the fact that I use `C--` as `tmux` prefix... :)

**Comment by DaveDavenport** [comment]
I do not think so. I am not updating this patch anymore. (Using it daily though together with my mode overlay and autotools patch on an old version of termite. If this is acceptable you could try running this..).

**Comment by MrOutis** [comment]
any PR or fork working on this issue?

**Comment by DaveDavenport** [comment]
@MrOutis  [this](https://github.com/DaveDavenport/termite) still works.

**Comment by MrOutis** [comment]
thank you, @DaveDavenport 👍

**Comment by aecepoglu** [comment]
Is @DaveDavenport 's solution to read config at runtime or compile time?

I'd be down with the ability to edit it at compile time, so I can just have my `config.h.patch` to apply on top of the source before compiling termite. It'd also be a low maintainance on my end.

**Comment by stobenski** [comment]
My (fresh) [fork](https://github.com/stobenski/termite) with Ctrl-Ins/Shift-Ins hotkeys for copy/paste and disabled Ctrl-Tab hotkey.

**Comment by jelly** [comment]
@aecepoglu I wouldn't want a compile time one, that doesn't really make it userf riendly.

**Comment by aecepoglu** [comment]
@jelly It still beats not being able to change the keybindings *at all* for me.

**Comment by boxxxie** [comment]
the forks i see people making for the configs don't look like they are supported emacs keybindings.
is there a fork with such keybindings coded? and would there be much difficulty in someone adding emacs keybindings to the project?

**Comment by omgold** [comment]
@jelly would you like to have customizable keybindings (from config file)? I have implemented it on this fork and could donate it, if you wish:

https://github.com/omgold/termite

Didn't open a pull request, as the patch is a little bit intrusive, of course (having to touch the large switch/case constructs). Would like to ask your opinion first, about getting this code merged in some way.

**Comment by dotKuro** [comment]
Is there any way omgolds patch will be merged some day?

**Comment by thestinger** [comment]
Termite doesn't have a developer / maintainer right now.

**Comment by thestinger** [comment]
Step one is updating the VTE patches to update VTE, etc.

**Comment by omgold** [comment]
For info, as I didn't want to wait, meanwhile I created this: https://github.com/omgold/mantid-term

It is mostly a reimplementation of Termite in Python with the features added I wished for (custom keybinds, multiple tabs).

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
