### ISSUE TITLE
copying text or blocks from vim using termite / sway / clipboard ?

### ISSUE THREAD

**Issue by colin-williams** [thestinger/termite#620]
I tried searching around because I'm sure the answer is out there but I didn't pick it up. Anyhow I use vim from terminals extensivly and can't seem to access the text from the editor from other applications. Then right now I cat the file I'm editing in another terminal so that I can paste it. But ideally I could access the items I'm copying in vim either from the mouse copy or a vim selection. What's the best way to go about this when using termite and sway as wm with vim from a termite console?

**Comment by colin-williams** [comment]
Any ideas?

**Comment by sum01** [comment]
I'd also like to know how to do this. Ctrl-C seems to do nothing when I select text in Vim's visual mode.

**Comment by zacheryph** [comment]
I am hitting this same issue. I cannot make a rhyme/reason out of it though.
* terminator->termite: works
* termite->terminator: works
* termite->termite: works
* chromium->terminator: works
* chromium->termite: works
* terminator->chromium: works
* termite->chromium: does _**not**_ work.
* termite->slack: does _**not**_ work.

**Comment by cpadilla** [comment]
I'm having this issue as well. I also can't seem to access the clipboard in vim using `"*y` or `"+y` when I'm in termite.

**Comment by adabru** [comment]
As a workaround you can use bugaevc's [wl-clipboard](https://github.com/bugaevc/wl-clipboard) copy/paste utilities.

Add following to your ~/.vimrc <sup>1</sup>:

```
" xnoremap         only in visual mode
" <c-c>            bind cTRL-c
" y                yank selection to "
" :!wl-copy        send following argument to wayland clipboard
" <C-r>"<cr>       magically paste " into vim's command line
" <cr>             execute wl-copy command
" gv               re-highlight selection

xnoremap <c-c> y:!wl-copy <C-r>"<cr><cr>gv
```

If your vim is compiled with the +x11 option, you can alternatively use <sup>2</sup>:

```
" xnoremap                    only in visual mode
" <c-c>                       bind cTRL-c
" :                           start command
" <c-u>                       remove '<,'>
" exe system('wl-copy', @*)   send selected characters @* to wayland clipboard
" <cr>                        execute vim command
" gv                          re-highlight selection

xnoremap <c-c> :<c-u>exe system('wl-copy', @*)<cr>gv
```


<hr>

[1]: https://vi.stackexchange.com/a/10265 by DJMcMayhem

[2]: https://stackoverflow.com/a/18031078/6040478 by glts

**Comment by edrex** [comment]
termite isn't involved in how vim handles the clipboard. Neovim, if wl-clipboard is installed, will sync the `*` and `+` registers using wl-copy and wl-paste. 

To sync the default registers put in your config:

```
set clipboard=unnamedplus
```

-----

https://github.com/neovim/neovim/issues/9365
https://github.com/neovim/neovim/blob/3f10c5b5338fc7efec53a23427e1c0e2dea56be4/runtime/autoload/provider/clipboard.vim#L75

**Comment by edrex** [comment]
The vim selection is different than the terminal selection. If you have mouse enabled in vim, you can still terminal select and copy like this:

1. Hold `Shift` while dragging to select text to avoid passing the mouse events to the application, resulting in a terminal selection.
2. `Ctrl-Shift+C` to copy the terminal selection.
3. Paste with `wl-paste`

Works for me with termite.

This is all different from the title of the issue, which indicates it is about visual/block selection and yanking in vim.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
