### ISSUE TITLE
how to partially select text from a url with the mouse?

### ISSUE THREAD

**Issue by gdalex** [thestinger/termite#622]
Hi,

in termite I can't select part of a url with the mouse. 
When a url is detected, hovering with the mouse over it, the mouse cursor changes into a hand, and if I try to start a selection, it will just open the url.

In gnome-terminal, I can select a part of that url with the mouse.

Is there an option in termite to allow me to do the same?

Thanks

**Comment by JordanL2** [comment]
This might be too late to be useful to you, but I solved this by adding these lines to the termite config in the [options] section:

clickable_url = false
hyperlinks = false

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
