### ISSUE TITLE
Ctrl-+ and Ctrl-- do not work with the numpad

### ISSUE THREAD

**Issue by pvutov** [thestinger/termite#625]
The hotkeys for increasing and decreasing font size only work with the plus and minus keycodes, not their numpad equivalents (KP_Add and KP_Subtract).

To make sure that it is not caused by something else, I verified the events with xev and also installed another terminal with the same scheme (sakura).

**Comment by BarbUk** [comment]
There is a PR to fix this issue: https://github.com/thestinger/termite/pull/652

**Comment by jelly** [comment]
470631b0b7832c89d131a0c0ce03e3e246efe2ea
