### ISSUE TITLE
URL with IPv6 address is not recognized

### ISSUE THREAD

**Issue by MisterDA** [thestinger/termite#626]
Hello,

I noticed that an url such as `http://[::1]/` which is a valid url pointing to the host itself in IPv6 is not underlined by termite. Not sure if it's an issue in termite or vte-ng.
To reproduce: `echo 'http://[::1] http://192.168.1'`. The first on is not underlined, the second is.

Thanks.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
