### ISSUE TITLE
Title restoration on alternate screen change

### ISSUE THREAD

**Issue by teto** [thestinger/termite#627]
As per the comment https://github.com/neovim/neovim/issues/4063#issuecomment-410478507, a simple change in smcup/rmcup with a recent VTE can provide: `switching to and back from the alternate screen automatically saves and restores the title` which is cool. As I don't rewrite my title in the prompt, I usually end up with a bad title (due to neovim mostly) so this could be great.

https://github.com/thestinger/termite/blob/master/termite.terminfo#L174

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
