### ISSUE TITLE
certain unicode characters crash termite instantly

### ISSUE THREAD

**Issue by Soundtoxin** [thestinger/termite#628]
I heard from a bud on Rizon that there was a little /exec -o python3 one-liner you could run to crash people on hexchat. It also crashed termite for me, though. Whether its output was shown in my irssi window, or in less while reading my log, it made my terminal instantly crash. I was working in tmux, so I was able to see that 'tmux attach' made the whole window disappear. The bug didn't affect urxvt, so I was able to attach to tmux that way and get the offending thing off my screen.
Below is the command to make the thing that crashes termite. It comes out as a message that looks like "hey" with a heart emoji after it on things that don't crash.
`/exec -o python3 -c "print(u'hey \u2665\ufe0e\ufe0f')"`

**Comment by thestinger** [comment]
It's a bug in the Pango library. You should keep your system updated:

https://github.com/GNOME/pango/commit/a6a89818246b0b14c0fe3d00d6120929fc0a11d9

It doesn't seem there's anything to do about it here.

**Comment by Soundtoxin** [comment]
Don't worry, I do keep my system updated. I guess not all distros updated Pango at the same time. GuixSD pushed the fix a few hours after I created this issue. I think I heard OpenBSD fixed it a week ago.
