### ISSUE TITLE
24bit color support in tmux isn't quite correct

### ISSUE THREAD

**Issue by kevinclevenger** [thestinger/termite#629]
When running tmux in a termite terminal the 24bit color support isn't complete, and 'tmux info' reports "202: Tc: [missing]".

I've attached screenshots for clarity.

Plain termite
![termite_tc](https://user-images.githubusercontent.com/484148/44925751-c46f3480-ad3e-11e8-8e43-9ba95473102b.png)

Termite and tmux
![termite_tmux_tc](https://user-images.githubusercontent.com/484148/44925752-c507cb00-ad3e-11e8-90b5-400c67955157.png)

Sakura and tmux
![sakura_tmux_tc](https://user-images.githubusercontent.com/484148/44925748-c46f3480-ad3e-11e8-8889-8d871ffdd96a.png)

Terminator and tmux
![terminator_tmux_tc](https://user-images.githubusercontent.com/484148/44925750-c46f3480-ad3e-11e8-95ab-7dc2ea7cfd46.png)

**Comment by DzKaki** [comment]
Try adding this 2 lines in your ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-termite:Tc"

source: https://wiki.archlinux.org/index.php/Tmux

**Comment by kevinclevenger** [comment]
I din't think to add an additional terminal-overrides for xterm-termite, that works perfectly. Thank you!
