### ISSUE TITLE
Error opening terminal: xterm-termite.

### ISSUE THREAD

**Issue by ycf83** [thestinger/termite#630]
hi, 
i build termite for debian, if i want open open file with sudo in system like:

sudo nano /etc/hosts
Error opening terminal: xterm-termite.

in home with sudo no problem, only in root file i get this problem

**Comment by ycf83** [comment]
problem fixed 
add this

if [ "$TERM" = xterm ]; then TERM=xterm-256color; fi
export TERM=xterm-256colo

**Comment by jelly** [comment]
The fix is wrong, please read the README.

**Comment by Machine-Hum** [comment]
> problem fixed
> add this
> 
> if [ "$TERM" = xterm ]; then TERM=xterm-256color; fi
> export TERM=xterm-256colo

```
if [ "$TERM" = xterm ]; then 
    TERM=xterm-256color;
fi
export TERM=xterm-256color
```

Clean your shit up boi
