### ISSUE TITLE
Open scrollback buffer in pager program

### ISSUE THREAD

**Issue by Ape** [thestinger/termite#633]
[kitty](https://sw.kovidgoyal.net/kitty/) has this features where you can open the scrollback buffer in a pager program:

> Sometimes you need to explore the scrollback buffer in more detail, maybe search for some text or refer to it side-by-side while typing in a follow-up command. kitty allows you to do this by pressing the ctrl+shift+h key-combination, which will open the scrollback buffer in your favorite pager program (which is less by default). Colors and text formatting are preserved. You can explore the scrollback buffer comfortably within the pager.

Would it be possible to have this feature also in termite?

#297 might be related.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
