### ISSUE TITLE
Single Termite instance registers with two id's according to xdo

### ISSUE THREAD

**Issue by Hessesian** [thestinger/termite#634]
Context: I create named instance of termite in bspwm to use as scratchpad/dropdown terminal "termite --name=scratchy"
Then use script 'xdo id -n scratchy' to find instance and switch visibility
Expected result: one ID in the output
Current result: two ID's in the output

`$: xdo id -n scratchy                                                                                                                                  :(
0x01200003
0x01200001
`
urxvt for example registers only under one ID
ID's are in random order, and only one of them referrences the termite window

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
