### ISSUE TITLE
Bold text on light themes

### ISSUE THREAD

**Issue by aleprovencio** [thestinger/termite#638]
Hello,
I'm having issues with displaying bold text on light themes, which has already been described here https://github.com/dylanaraps/pywal/issues/175

The conclusion of that thread was a needed update on ``vte``, which I confirmed to work for  ``gnome-terminal`` but not for ``termite``.  I've also tried changing ``allow_bold`` without success.

**Comment by dylanaraps** [comment]
bug report - https://bugzilla.gnome.org/show_bug.cgi?id=793152

commit with fix - https://github.com/GNOME/vte/commit/e9989360bb3b020c4507562af9385ca7584f0d97

**Comment by egmontkob** [comment]
Do you have `foreground_bold` defined in your termite config? If so, that color is used for bold text, this isn't overridden by pywal.

**Comment by aleprovencio** [comment]
Sorry for not testing this option, and it works good enough, thank you.  However, as my main concern was pywal's use, I'll be waiting for this https://github.com/dylanaraps/pywal/issues/316
