### ISSUE TITLE
Can't set border

### ISSUE THREAD

**Issue by cstrahan** [thestinger/termite#639]
I know very little about GTK theming, but I have found that this works on just about all applications, with the exception of `termite` (in `~/.config/gtk-3.0/gtk.css`):

```css
decoration {
  border: 1px solid gray;
  background: gray;
}
```

It would be nice to have some documented way to apply a border to `termite`, otherwise the bottom left/right corners are invisible when termite is on top of a black background (in my case, likely another termite instance):

![Image of overlapping terminals](http://files.programster.org/tutorials/themes/enable-border/before.png)

([image source](https://blog.programster.org/ubuntu-16-04-add-borders-to-windows))

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
