### ISSUE TITLE
Ctrl-Shift-Space to switch to Selection mode makes Termite crash

### ISSUE THREAD

**Issue by Zer0t3ch** [thestinger/termite#640]
```
Gtk-Message: 07:24:14.206: Failed to load module "appmenu-gtk-module"
termite: symbol lookup error: termite: undefined symbol: vte_terminal_disconnect_pty_read
```

That's the output from a terminal running Termite when try to use that keybind.

This is related to #565, but @javiertury's `LD_LIBRARY_PATH` fix didn't work for me, so I thought a new issue might be in order.

**Comment by jordanrinke** [comment]
Don't know the solution/specific cause for this but wanted to say, I had this issue when I did the docker build/binary copy from https://github.com/Corwind/termite-install however when I did the straight termite-install.sh everything works fine.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
