### ISSUE TITLE
Switch back to Selection Mode from Visual Mode

### ISSUE THREAD

**Issue by cpadilla** [thestinger/termite#641]
I'd like to have the option to switch back to selection mode after entering visual mode. Hitting `Escape` returns back to insert mode. It would be nice if there was an option to change this behavior to go back to selection mode first.

**Comment by cpadilla** [comment]
Oh, I see. Yeah, I guess that works too. I'd still like to be able to edit the config to have `Escape` return to selection mode when in visual mode, just because I press `Escape` so often out of habit.

Is this possible with the existing config options in termite, or would this need to be implemented?
Thanks.

**Comment by amayer5125** [comment]
According to `man termite.config` there is no option to configure this functionality. You would need to add it yourself.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
