### ISSUE TITLE
Can we add an option to change the default TERM env variable?

### ISSUE THREAD

**Issue by czert** [thestinger/termite#647]
There are several ways to deal with the "`Error opening terminal: xterm-termite`" problem, but for me (and, I suspect, others as well) having the TERM variable configurable would be by far the most painless way. It's by no means an ideal solution, but worth its drawbacks when installing terminfo on remote machines is not an option.

I now compile my own build of termite with the value changed, but I'd appreciate not having to do that.

**Comment by jelly** [comment]
Won't do, read the README. Changing the TERM does not fix your problem you need to install the correct terminfo file.

**Comment by czert** [comment]
That's my whole point: I don't need the correct terminfo, changing the TERM is good enough for me. On the other hand, installing the terminfo on all the machines I routinely connect to is a no go.

If I submit a PR for this, will you consider it, or should I not bother?

**Comment by jelly** [comment]
I won't support it, since it will end up causing bugs and scenario's I don't want to support.

**Comment by czert** [comment]
OK, that I can understand.

Thanks.

**Comment by bergentroll** [comment]
vte3 xfce4-terminal perfectly uses $TERM == 'xterm-256color'. Termite solution looks like right one, but is really inconvenient when you need to ssh to many hosts, also when some of the hosts are temporary boxes. It is better to have some client-side solution. One ugly solution can be alias ssh='env TERM=xterm-256color ssh'.
