### ISSUE TITLE
Character ─ in zsh PS1 repeats characters when tab completing

### ISSUE THREAD

**Issue by lohfu** [thestinger/termite#649]
With the following .zshrc

```
PS1='─'
```

I get bunch of incorrect characters when tab completing in zsh and termite. The more `─` (or similar, `└` causes the same behaviour) i add the more incorrect characters are added.

It only seems to happen when the tab completion has multiple suggestions. Ie if i type `chr<TAB>` and it suggests chromedriver, chromium etc.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
