### ISSUE TITLE
Uneeded space around termite  ref #174

### ISSUE THREAD

**Issue by Afro-Coder** [thestinger/termite#651]
Hey,
I found this same bug referenced here issue #174 
I have the same issue also I have set the padding of termite to 0 in .config/gtk-3.0/gtk.css
The geometry option wasn't there.
I have double checked i3-gaps config for any extra borders it creates.

I even built the package github.

> Termite Version : termite 14-2
> Distro Arch
> WM i3-gaps

>  i3 config https://pastebin.com/a6Z1DKZV

> .config/gtk-3.0.0/gtk.css
   ```
VteTerminal, vte-terminal {
   padding: 0px;
  }
  .termite {
     padding: 0px;
   }

```
> Termite Config https://pastebin.com/bfZhDeSP

Screenshots:

![2018-12-31-181014_935x159_scrot](https://user-images.githubusercontent.com/8469842/50560717-966c2200-0d29-11e9-9a96-a3554824b349.png)

![2018-12-31-175501_955x73_scrot](https://user-images.githubusercontent.com/8469842/50560724-a97ef200-0d29-11e9-9034-efbf514a14f5.png)

![2018-12-31-180014_971x100_scrot](https://user-images.githubusercontent.com/8469842/50560719-9a983f80-0d29-11e9-83b6-841c5ee184cb.png)

I cannot figure out what to check next, can someone please guide me, I just got started with tiling managers. I also couldn't replicate the issue in a fresh VM install of Manjaro i3.

Edit : Even tried with compton disabled
Thanks

**Comment by elhenro** [comment]
what fixed it  for you?
