### ISSUE TITLE
Don't spawn new window for program started with termite

### ISSUE THREAD

**Issue by mb720** [thestinger/termite#653]
Hi and thanks a lot for termite!

I was wondering if it's possible to start a program like [imv](https://github.com/eXeC64/imv) or [zathura](https://wiki.archlinux.org/index.php/Zathura) from termite without spawning a new window for the program.

Ranger, Vim, and htop already exhibit the desired behavior: When started, they replace the termite window and once I exit the program (Ranger, Vim, or htop respectively), termite appears in the same window again.

Is this possible for programs that are not textual applications?

---

I use termite v14 on Arch Linux 4.19.9 with i3 version 4.16.

**Comment by jelly** [comment]
Not really possible, one option is to "zathura &" to background the zathura
