### ISSUE TITLE
'xterm-termite': unknown terminal type

### ISSUE THREAD

**Issue by 0003c9fe** [thestinger/termite#654]
I'm aware that this has been asked before, however you've responded that it's "expected" and that all you need to do is "upload the termite.terminfo".

But why is that expected? And why do I need to upload that? None of the other terminal emulators that I've tried have this issue, so why is it necessary to do here?

**Comment by jelly** [comment]
Because other terminal emulators have their terminfo in ncurses while termite has not been added since 6.1

https://github.com/thestinger/termite/pull/591
