### ISSUE TITLE
Optional half-page paging through scrollback buffer

### ISSUE THREAD

**Issue by sriedel** [thestinger/termite#659]
Maybe this is already possible, and I just didn't find the appropriate options.

It would be nice to be able to have a bit of overlap between the individual pages when going through the scrollback buffer with shift pgup/pgdn.

I frequently finding myself paging back and forth rapidly to establish context of a stack trace that goes across the paging boundary.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
