### ISSUE TITLE
Open HTTP link using just the keyboard

### ISSUE THREAD

**Issue by adtac** [thestinger/termite#662]
Termite's amazing, thank you for making this.

HTTP links are underlined and opened in my web browser when I hover and click on them, so Termite/VTE can detect URLs. I'd like to do this without using my mouse i.e. open a link displayed on screen using just the keyboard. Something like Tridactyl's (or any other vim-bindings extension for Firefox) `F` shortcut.

**Comment by adtac** [comment]
Here's what pressing `F` looks like on Tridactyl: https://screenshotscdn.firefoxusercontent.com/images/a512c1fa-fac7-42bd-a8fe-43cde613c55c.png, just to give an idea. I don't know if this issue belongs on termite or VTE, sorry.

**Comment by lhanson** [comment]
This would be an amazing feature, I'm also very interested.

**Comment by jelly** [comment]
This can already be done with Ctrl+shift+x or ctrl+shift+u.

**Comment by adtac** [comment]
Excellent!

**Comment by lhanson** [comment]
Yep, there it is, right in the Readme. Time to read it again just to see what else I'm missing out on.

**Comment by mb720** [comment]
This is great! Is there a way to open the link in the background?
Currently, after selecting a URL with ctrl+shift+x, the browser gets focus.

If it's possible, I'd like to have termite keep the focus.
