### ISSUE TITLE
Pass keybind directly to app?

### ISSUE THREAD

**Issue by FFY00** [thestinger/termite#664]
Is there any way to pass a keybind directly to the app running inside termite? For example, I have `Ctrl+s` bind to a function that adds/removes `sudo` on my shell. This doesn't work right now.

**Comment by jelly** [comment]
Ctrl+s is not used as a key binding so I don't see why it wouldn't work.

**Comment by FFY00** [comment]
Nevermind, I wasn't able to reproduce it again.
