### ISSUE TITLE
Termite + Tmux + Mutt = Redraw problems

### ISSUE THREAD

**Issue by Eluminae** [thestinger/termite#665]
Hello there !

I got problems with mutt inside tmux inside termite. The lists doesn't redraw correctly !
This problem doesn't occur on xterm with the exact similar condition.

The $TERM variable is 'screen-256color' tmux.

The layout is:

newsboat | mutt
ikhal         |

My environment:

```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

$ uname -r
5.0.2-arch1-1-ARCH

$ sway -v
sway version 1.0

$ termite -v
termite v14

$ tmux -V
tmux 2.8

$ mutt -v
Mutt 1.11.4 (2019-03-13)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Linux 5.0.2-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libidn2: 2.1.1 (compiled with 2.1.1)
hcache backend: GDBM version 1.18.1. 27/10/2018 (built Jan 10 2019 15:18:10)
```

**Comment by Eluminae** [comment]
tmux: https://raw.githubusercontent.com/Eluminae/dotfiles/master/tmux.conf
termite : https://raw.githubusercontent.com/Eluminae/dotfiles/master/config/termite/config
mutt: https://raw.githubusercontent.com/Eluminae/dotfiles/master/mutt/muttrc

**Comment by Eluminae** [comment]
The problem seems to not occur in all conditions.
I run the tmux layout with https://raw.githubusercontent.com/Eluminae/dotfiles/master/bin/tmux_work_session.sh

**Comment by Eluminae** [comment]
I dunno what parameters create the redraw bug. I can't find a specific scenario that produce it.

**Comment by jelly** [comment]
Why is TERM not set to xterm-termite ?

**Comment by Eluminae** [comment]
Cause I'm running mutt inside a tmux session.

**Comment by bisby** [comment]
I'm having a weird redraw issue as well (although different? I could make a new issue, but TERM + redraw seems related)

Anytime TERM is `screen-256color` and I reload my i3wm config, there is a redraw delay that causes ghosting. If I hold down backspace to clear a line, I see a fainter "ghost" of the text I deleted, and then a few seconds later it disappears. Similarly when I type, I see the new letters show up instantly, but I can also see a ghost of the cursor a few characters back.

Setting TERM back to xterm-termite doesn't solve this. If I reload i3wm config with a tmux/screen session open, I can only get it to stop doing this by closing termite and reopening.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
