### ISSUE TITLE
Search matches depend on termite's window geometry

### ISSUE THREAD

**Issue by camoz** [thestinger/termite#667]
When doing a search in selection mode and cycling through the matches with `n`/`N`, only one match per line is considered.

Quick example:
* run `for i in $(seq 50); do echo -n hello\ world; done`
* Enter selection mode: `Ctrl-Shift-Space`
* search e.g. for `world`
* cycle through matches via `n`/`N`
* resize window to something small/large and repeat -> different matches

This way, one could easily miss matches.

It would make slightly more sense, if the search matched one entry per actual line, not per line as displayed by termite, i.e. if the window geometry wouldn't matter. But even then, it's not really practical.

So expected behavior would be to cycle through ALL matches.

**Comment by egmontkob** [comment]
Might be a VTE bug: https://gitlab.gnome.org/GNOME/vte/issues/104.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
