### ISSUE TITLE
May I ask you about the random MAC you mentioned on github before, which can realize this function in the kernel? My device is millet 5-msm8996

### ISSUE THREAD

**Issue by 760644586** [thestinger/termite#669]
May I ask you about the random MAC you mentioned on github before, which can realize this function in the kernel? My device is millet 5-msm8996

**Comment by jelly** [comment]
This has nothing to do with termite, but sounds more about android. A simple google reveals https://source.android.com/devices/tech/connect/wifi-mac-randomization
