### ISSUE TITLE
Display issue with ssh?

### ISSUE THREAD

**Issue by rieje** [thestinger/termite#673]
A picture is worth [a thousand words](https://imgur.com/a/VxH4ktx)--what may be causing it? As you can see, it's only a display issue--after issuing the command I typed (which is "`exit`", but shows as e.g. "eeexxxiiitttt"), the command is executed. So both the client and the server are receiving the correct keystrokes, but it shows up in the terminal like that.

When I'm in the virtual console, I don't have this issue.

**Comment by jelly** [comment]
Where do you ssh too, did you install the terminfo on the remote server?

**Comment by NextHendrix** [comment]
@rieje do you get the same issue if you disable your shell config

**Comment by rieje** [comment]
It is solved by installing terminfo on the remote server as @jelly suggested, thanks.
