### ISSUE TITLE
Feature Request: Serial Console Client

### ISSUE THREAD

**Issue by ifohancroft** [thestinger/termite#676]
I'd like it if Termite had the ability to act as a serial console client. For example, being able to connect to the Arduino's Serial console so I can use Termite instead of the Arduino's software serial monitor. For example termite -o /dev/ttyACM0 115200 (specifying the device and the baud rate).

**Comment by jelly** [comment]
Won't be implemented, there are plenty of alternatives for serial console clients such as screen. ```screen /dev/ttyACM0 115200```

**Comment by ifohancroft** [comment]
Thanks! I didn't know screen can do that.
