### ISSUE TITLE
Can't change font 

### ISSUE THREAD

**Issue by Seanmusse** [thestinger/termite#678]
Hey! I've been trying to change my font but it doesn't leave Monospace. The fonts I'm trying to change to are in `fc-list` and were installed in `/usr/share/fonts` . Not really sure of what I can do form now... 

I haven't modified my config file at all, besides from the font line, which is `font = tamzen 12` (for example) 

Any suggestions are welcome!

**Comment by BarbUk** [comment]
You maybe forgot to put the group in your config.
Test your config with `--config=`

```
$ cat test.conf 
[options]
font = Source Code Pro 12
```

and 

```
termite --config=test.conf
```
