### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by vikasgola** [thestinger/termite#683]
add screenshots.

**Comment by jelly** [comment]
What do you mean?

**Comment by vikasgola** [comment]
How does terminal look like? Add screenshot of the terminal look or a short video.

**Comment by BarbUk** [comment]
It really depends on your wm and your config (termite config and dotfiles).

If you want to see termite with a light theme without window decoration (awesomewm), here is a screenshot:

![image](https://user-images.githubusercontent.com/64371/60069001-3a0b1d80-9722-11e9-9d5f-cebbf43eb26e.png)

If you want to see it in action, the best way is to install it and try it on your system.
