### ISSUE TITLE
Loose resize event on start

### ISSUE THREAD

**Issue by backdround** [thestinger/termite#686]
I have the same issue like #88

If terminal opened with "-e nvim", then neovim doesn't receive first resize event.
`termite --class qute_editor -e nvim`:
![termite_resize_event](https://user-images.githubusercontent.com/17349169/60301513-47025980-993a-11e9-8c31-591ef6e14224.gif)

Bug works:
* on weak pc
* complex nvim [configuration](https://github.com/fasterbru/configuration/blob/f5bea73d280e20d5c65a23cc1e45e9846840be9c/nvim/init.vim)

For local needs i fix it by inserting 0.05 delay before nvim.
`termite --class qute_editor -e "bash -c \"sleep 0.05 && nvim\""`:
![termite_resize_event_with_delay](https://user-images.githubusercontent.com/17349169/60301625-8630aa80-993a-11e9-8e78-cf653813d36c.gif)

I test this behavior on xterm and couldn't reproduce.
`xterm -class qute_editor -e nvim`:
![xterm_resize_event](https://user-images.githubusercontent.com/17349169/60301679-b1b39500-993a-11e9-841b-8f9f5e94988a.gif)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
