### ISSUE TITLE
Spacing on the bottom and the right (i3wm)

### ISSUE THREAD

**Issue by oxodao** [thestinger/termite#687]
Hi,

I'm facing more or less the same problem as #174 
I'm having a weird space at the bottom but also on the right
With the `size_hits = true` and css doesn't fully fixes it

When the window is in floating mode, it does works as intended
When the window is in full screen (Like the standard i3) the bottom is correct but there is still a weird space on the right
When the window is in full screen BUT with some gaps (from the i3-gaps fork), I'm having the original issue with both weird spaces.

Here are some pictures to explain better:
https://u.oxodao.fr/termite_bug/floating.png
https://u.oxodao.fr/termite_bug/wgaps.png
https://u.oxodao.fr/termite_bug/wogaps.png

**Comment by elhenro** [comment]
same problem here, with i3-gaps

**Comment by littlecoce** [comment]
According to my understanding this gap is the result of a window size with a left over space which does not cover a complete line height (bottom) or character width (right).

When resizing floating windows the same problem should arise.

**Comment by romariolopezc** [comment]
https://github.com/thestinger/termite/issues/174#issuecomment-575178742

**Comment by syphoxy** [comment]
this is a common issue in a lot of terminal emulators when faced with geometries that are not perfect multiples of the character cell size.

I just came from konsole and one useful feature konsole implements is to center the cell grid to the containing window. the benefit of this is that if it's uneven, at least the left over space would be distributed across the entire border as opposed to along the bottom and right.

I'll start poking at the code to see if this is possible.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
