### ISSUE TITLE
`dynamic_title = true` results in blank window titles

### ISSUE THREAD

**Issue by rieje** [thestinger/termite#688]
`dynamic_title = true` results in blank window titles, at least on i3-wm. Latest version of both on Arch linux. Setting to `false` fixes this issue.

**Comment by jolange** [comment]
I guess you shell does not properly set the dynamic title.
See for example https://github.com/thestinger/termite/issues/474#issuecomment-416053063

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
