### ISSUE TITLE
DISPLAY environment variable is ignored.

### ISSUE THREAD

**Issue by kindaro** [thestinger/termite#690]
### Description of the problem:

If I have, say, two X servers running in two different virtual terminals, `termite` will always spawn in the same X windows instance, even if I run the command from another instance of X windows.

### How to see for yourself:

1. Run two X servers in two different virtual terminals. For instance:

    <pre>
    <em>(Press Ctrl+Alt+F1 and log in.)</em>
    % xinit /bin/i3 -- /bin/X :1 vt1

    <em>(Press Ctrl+Alt+F2 and log in.)</em>
    % xinit /bin/i3 -- /bin/X :2 vt2
    </pre>

2. Run some `termite` in the first X server, see its windows spawn there.

3. Run some `termite` in the second X server, see its windows spawn... to the first server instance.

### My program and system version:

    % termite --version
    termite v15
    % uname -r
    5.1.16-arch1-1-ARCH

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
