### ISSUE TITLE
ibeam cursor change to block cursor after opening vim

### ISSUE THREAD

**Issue by shibumi** [thestinger/termite#691]
Hi, I have some weird behavior. I have set the following option in my `.config/termite/config` file:
```
cursor_shape = ibeam
```

This works as expected, but when I open vim for editing a file and close it afterwards the cursor is changed to a block cursor. Any idea?

**Comment by shibumi** [comment]
Here is a screen record https://paste.xinu.at/t96/

**Comment by BarbUk** [comment]
Do you have a cursor definition in your vim config ?
Check for:

```
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
```

or 

```
autocmd VimEnter * silent !echo -ne "\e[2 q"
```

**Comment by BarbUk** [comment]
You can change your vim config if you want a block cursor only in vim:

```vim
" optional reset cursor on start and leave:
augroup myCmds
au!
autocmd VimEnter * silent !echo -ne "\e[1 q"
autocmd VimLeave * silent !echo -ne "\e[5 q"
augroup END
```

To test the cursor change:
`echo -ne "\e[N q"`

with N = 
```
N = 0  -> blinking block.
N = 1  -> blinking block (default).
N = 2  -> steady block.
N = 3  -> blinking underline.
N = 4  -> steady underline.
N = 5  -> blinking bar (xterm).
N = 6  -> steady bar (xterm).
```

**Comment by shibumi** [comment]
@BarbUk I have cursor definition in my vim. But it's not about the cursor inside of vim, the cursor changes when I exit vim. This is not what I expect. I expect that the terminal always has the same cursor. But I will try out this reset block you have posted.

**Comment by BarbUk** [comment]
> I expect that the terminal always has the same cursor. 

Vim use the terminal cursor in cli mode.
Your config in vim is telling termite: `change the cursor to block please.`

**Comment by elenapan** [comment]
Use this in your vim config to restore the cursor on exit:
```vim
" Restore cursor shape to beam on exit
augroup restore_cursor_shape
  autocmd!
  au VimLeave * set guicursor=a:ver10-blinkoff0
augroup END

```

**Comment by harsathAI** [comment]
This works, but I make vim as BG task, it makes the cursor to Block instead of the I beam. This works only on exit, is there any way I can do it when I make vim as BG task and return to the shell?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
