### ISSUE TITLE
Add support for two-wide characters

### ISSUE THREAD

**Issue by martmists-gh** [thestinger/termite#694]
Two-wide characters do not render correctly. This issue is similar to #461 as it has the same issues, but these issues do not appear on other VTEs such as gnome-terminal.

OS: Arch Linux x64
Termite version: Latest
Font: NotoSansMono Nerd Font 9

**Comment by syphoxy** [comment]
not a maintainer or contributor but I just started using termite and I can't seem to replicate this issue with two wide characters.

for example, 四六時中 and 不言実行 both render fine for me.

**Comment by martmists** [comment]
Are you using the same font and size?

**Comment by ultratensai** [comment]
It looks like the issue is due to _Nerd Fonts_ using double width glyphs.
I am using CaskaydiaCove Nerd Font and it's not rendering = < > properly.

[screenshot - top one is kitty, bottom one is termite](https://nicewarm.coffee/uploads/nerd_font_termite.png)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
