### ISSUE TITLE
Blinking text

### ISSUE THREAD

**Issue by szatanjl** [thestinger/termite#695]
It would be great if there would be an option to turn off blinking text.  I personally find it very irritating.

You can see what I am talking about by typing: `printf '\033[5m asdf \033[0\n'` in terminal.

Thanks.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
