### ISSUE TITLE
extra config file

### ISSUE THREAD

**Issue by zakariaGatter** [thestinger/termite#699]
is there is way to source other files to termite config ???

**Comment by jelly** [comment]
No, there isn't.

**Comment by zakariaGatter** [comment]
ok thank you

**Comment by appelgriebsch** [comment]
Any plans for such a feature? Would be great to differentiate color options from the rest to make theming easier. Eventually introducing another command line parameter for a style file, or allowing to use the --config parameter multiple times would be an alternative approach (assuming that those additional config files are parsed during startup)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
