### ISSUE TITLE
Specify mouse cursor style / disable graphical text selection

### ISSUE THREAD

**Issue by scrouthtv** [thestinger/termite#700]
My default cursor is a high visibility, red one:
![image](https://user-images.githubusercontent.com/23227405/66754350-10732f00-ee96-11e9-9a7e-5438e667509e.png)

However, as soon as I move my cursor onto the termite window, it turns into the text selection tool:
![image](https://user-images.githubusercontent.com/23227405/66754473-5203da00-ee96-11e9-8f5a-5ba49238faf2.png)

Which - after all - makes sense. However, is it possible to deactivate the graphical text selection all together, as I don't use it at all? Or is there some way to at least specify the mouse cursor style to use (because it after all is kind of hard to spot the tiny text selection cursor)?

Thanks in advance.

**Comment by scrouthtv** [comment]
This isn't any special cursor theme.. I just replaced the cursor file with the red one and left the other ones as-is. 

I suppose that termite isn't even explicitly setting the cursor theme, but it's rather some lower level interface that prints the text which is also setting the cursor theme.

The text selection cursor style is indeed as well displayed in any other terminal emulator & text editors (which is how it is supposed to be - I guess), but in this specific case I don't need it.

**Comment by egmontkob** [comment]
> This isn't any special cursor theme.. I just replaced the cursor file with the red one and left the other ones as-is.

You can just replace the other cursor files as well – "xterm" in particular –, problem solved :)

> I suppose that termite isn't even explicitly setting the cursor theme, but it's rather some lower level interface that prints the text which is also setting the cursor theme.

It's called VTE that prints the text and does all the terminal emulation, and it's this one choosing the particular cursor shape (e.g. arrow vs. i-bar) from the cursor theme. How to choose a cursor theme belongs to your desktop (I'm unaware of technical details here).

**Comment by scrouthtv** [comment]
Oh nice, to be perfectly honest, I wasn't aware that there was an actual ```xterm``` cursor... 

I wanted to keep the text selection tool in any other application that has text, so I didn' want to replace the ```text``` cursor, but linking ```xterm``` to ```default``` did the trick.

Thanks for the help. :)
