### ISSUE TITLE
ctrl+shift+v problem with russian layout

### ISSUE THREAD

**Issue by ghost** [thestinger/termite#701]
when i press ctrl+shift+v with rus layout, i'm getting ^V. (on eng layout no problems)
ver: termite 15-1 from arch repo.

**Comment by bladefox1337** [comment]
gnome-terminal 3.34.2-1 not have this issue.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
