### ISSUE TITLE
Missing KEY_FORWARDS KEY_BACKWARDS input

### ISSUE THREAD

**Issue by SairesArt** [thestinger/termite#703]
I use the KEY_FORWARDS and KEY_BACKWARDS (the two keys next to the arrow keys on older thinkpads, on newer models replaced with PGUP and PGDN) in emacs all the time to jump between buffers. In terminal-emacs this does not work, since those keys are not carried over to the terminal application.
Can termite be somehow configured to pass these keys through?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
