### ISSUE TITLE
URL selection doesn't work for this text

### ISSUE THREAD

**Issue by alex3kov** [thestinger/termite#708]
I'm using URL selection a lot via Ctrl-Shift-Space and then hitting `u` until I get to desired URL so I can copy it. But for some reason it doesn't work with a particular text (it's an RSS summary).  
Reproduction:  
1. Copy this text to a file: 
```
Feed: Dmitry Puchkov
Title: Олег Соколов о Второй Итальянской кампании Наполеона, ч. 1: На Сен-Бернар!
Author: Dmitry Puchkov
Date: Tue, 29 Oct 2019 16:09:52 +0300
Link: https://invidio.us/watch?v=uzrHgVxiSII

[image 2][2]

Ждёшь новых лекций Клима Жукова? Поддержи проект! https://oper.ru/donate/history Аудиоверсия: https://oper.ru/video/audio/interview_napoleon16.mp3 Сайт Тупичок
Гоблина: https://oper.ru Канал в Telegram: https://t.me/oper_goblin Гоблин в Twitter: https://twitter.com/goblin_oper Гоблин Вконтакте: https://vk.com/goblin
Гоблин в Instagram: https://www.instagram.com/goblin_oper/ Гоблин в Facebook: https://goo.gl/GK13pD Группа Вконтакте: https://vk.com/goblin_oper_ru

Links:
[1]: https://invidio.us/watch?v=uzrHgVxiSII (link)
[2]: https://invidio.us/vi/uzrHgVxiSII/mqdefault.jpg (image)
```
2. In `termite`, `cat` that file.
3. Press Ctrl-Shift-Space and hit `u` several times - termite skips "https://oper.ru/video/audio/interview_napoleon16.mp3" URL. Works fine with similar URLs in other UTF-8 texts with Cyrillic characters, but not with this one.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
