### ISSUE TITLE
Termite returns size of 0x0 on Sway

### ISSUE THREAD

**Issue by Siborgium** [thestinger/termite#710]
I played with [this](https://github.com/Difrex/gosway/tree/master/swaymgr) project and noticed that its spiral layout doesn't work with termite. The source of this issue is termite itself: sway thinks termite's window has size of 0x0. Other VTE-based terminals' size is determined correctly.

**Comment by Warepire** [comment]
Maybe related? https://gitlab.gnome.org/GNOME/vte/issues/188

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
