### ISSUE TITLE
Blinking text doesn't seem to work

### ISSUE THREAD

**Issue by daphniz** [thestinger/termite#711]
In xterm/irssi, if you type `^fword^f`, 'word' will blink, but not in
termite.

**Comment by egmontkob** [comment]
VTE supports blinking text since version 0.52 (see also #695), but it's missing from termite's terminfo entry.

**Comment by egmontkob** [comment]
`export TERM=xterm-256color` should be a workaround for you.

**Comment by daphniz** [comment]
all right, it seems that blinking works but not inside tmux

**Comment by daphniz** [comment]
however, in xterm/tmux blinking works.

**Comment by daphniz** [comment]
setting TERM as you say before opening tmux works
