### ISSUE TITLE
Cannot use xterm font

### ISSUE THREAD

**Issue by daphniz** [thestinger/termite#712]
I liked the look of xterm, and wanted to try to make termite look like
that, so I wrote

	font = Fixed 9
	
But the result looks nothing like xterm.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
