### ISSUE TITLE
URL paranthesis

### ISSUE THREAD

**Issue by andsanmar** [thestinger/termite#714]
If in an url ends in parenthesis+dot, it uses it for opening the link (e.g. `(https://github.com/thestinger/termite).` will open `https://github.com/thestinger/termite/).`

**Comment by cap4096** [comment]
This is probably the same as #718

**Comment by mvdan** [comment]
I solved this for my old X11 terminal emulator by using https://github.com/mvdan/xurls - it's regex-based, but smart enough to deal with surrounding characters.

I wish there was a way to use it with Termite, but there doesn't seem to be a way right now.

Another option would be to simply copy xurls' regular expression for http/https URLs, which isn't all that large. That should only need to be updated once a year or so.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
