### ISSUE TITLE
urgent_on_bell does not work in wayland

### ISSUE THREAD

**Issue by andremarcais** [thestinger/termite#715]
I have `urgent_on_bell` set. When using swaywm (Wayland), the window does not get urgent state. It works under i3wm (Xorg).

**Comment by FreeFull** [comment]
This is because wayland doesn't yet have a protocol for urgency. Sway itself does support urgency, but only for programs running under Xwayland.

**Comment by WhyNotHugo** [comment]
I'm running swaywm, and Telegram _does_ show urgency bells.
I'm sure it's not running under xwayland, because apps under xwayland don't scale and look super blurry, it's immediately evitend.

Maybe some new spec has come out adding support for that?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
