### ISSUE TITLE
Is it possible to remap the copy and paste shortcut keys?

### ISSUE THREAD

**Issue by krzkrzkrz** [thestinger/termite#716]
Is it possible to configure termite to have `ctrl+c` and `ctrl+v` for copy and paste?

**Comment by Narrat** [comment]
In general: As there are no customizable keybinds, no. You would need to change the source (but dunno if in termite or vte-ng)
But your reworked `ctrl-c` would clash with the ability to send SIGINT via the same keybind to a process.

**Comment by krzkrzkrz** [comment]
Thank you for this feedback
