### ISSUE TITLE
URL selection selects one character too much.

### ISSUE THREAD

**Issue by cap4096** [thestinger/termite#718]
If a URL is quoted the URL passed to the browser contains the end quote character:
Example:

'http://www.freedesktop.org/' , if hovering over the URL the following text is underlined and sent to the broweser if clicked:  http://www.freedesktop.org/'
Note the ending single-quote character.

**Comment by cap4096** [comment]
This is probably the same as #714

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
