### ISSUE TITLE
Terminal window shows artifacts while opening termite

### ISSUE THREAD

**Issue by melihcoban** [thestinger/termite#719]
Hi, while I am opening a new terminal in i3 (arch linux) most of the time horizontal white lines appears in the window. I don't have any issues with other terminal emulators (tried with urxvt, alacritty and kitty),

[youtube video showing it](https://youtu.be/ds-Opjl1N6c)

termite -v says I am using the version v15. also my computer only have intel graphics card and as far as I know correct drivers are installed. 

also, I compared startup times with other terminals and termite is a little bit slower (I don't know if it feels like that because I am seeing this glitches)

```
urxvt -e "sh -c exit"  0.05s user 0.00s system 98% cpu 0.058 total
alacritty -e "sh -c exit"  0.07s user 0.02s system 92% cpu 0.096 total
termite -e "sh -c exit"  0.13s user 0.02s system 100% cpu 0.147 total
```

I really would like to switch to termite but this couldn't find any way to fix this glitches (sorry if this is a old issue, unfortunately I couldn't find anything while searching for it)

**Comment by Narrat** [comment]
As termite uses vte(-ng) you could maybe test if those glitches happens with other vte-based terminals. Could be possible the culprit isn't termite :)

**Comment by magnetophon** [comment]
I tried with lxterminal, which is also VTE based, and it has the same issue, unfortunately.

**Comment by magnetophon** [comment]
I noticed that emacs has these artifacts too, but only when I enlarge the window.
There is no vte in emacs, and the only dependency that all 3 have in common is gtk3.
I tried another gtk3 app: baobab, but could not get it to produce artifacts.

I figured the culprit might be some text-displaying part of gtk3, so I tried geany.
Sure enough, it has the same artifacts when resizing and closing.

A quick search on https://gitlab.gnome.org/GNOME/gtk/-/issues didn't turn anything up yet, but maybe swihtomeone more familiar whit the termite codebase will have more success with a more targeted search.

**Comment by karlyeurl** [comment]
Hello,

I have a similar issue (I use AwesomeWM and switching tags causes the issue). I tried with `lxterminal` as well, and the same happened.

Is this a vte(-ng) bug? What's the best way to figure out what is wrong and help fix it? Would perhaps trying to merge upstream vte (which is under development) into vte-ng (which hasn't received commits for quite some time) be a good start?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
