### ISSUE TITLE
support multline url

### ISSUE THREAD

**Issue by parisni** [thestinger/termite#721]
hi

often large url get split over multiline in the terminal. eg: 
```
http://example/very/very/very/very/very/very/very/very/very/
very/very/very/very/very/very/very/large-url.com
```
that would be great if the termite url regex support those splited url

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
