### ISSUE TITLE
Execute / reload command on window size change

### ISSUE THREAD

**Issue by scrouthtv** [thestinger/termite#722]
How would one perform an action / reload a task on change of the window size? My example is the man command, if I run it at first and then open a second window next to it the entire output is messed up:
![image](https://user-images.githubusercontent.com/23227405/73163659-b1f25980-40f0-11ea-8e4a-fa6d23fb4403.png)
My guess would be to have an xorg event when the window size changes and the send termite a signal but how would I do that?

**Comment by scrouthtv** [comment]
It should instead look like so:
![image](https://user-images.githubusercontent.com/23227405/73165113-7907b400-40f3-11ea-818e-a634c22fb229.png)

**Comment by egmontkob** [comment]
It's technically hopeless to fix it from the terminal's side. It should be fixed in the `man` command (along with changes to `less` so that they can cooperate nicely, or by `man` switching to an internal pager implementation).
