### ISSUE TITLE
termite scrollback/selection-mode inside tmux covers only "visible area"

### ISSUE THREAD

**Issue by fmirus** [thestinger/termite#723]
I'm using termite (termite v15-5-g9565563) on ubuntu 18.04. When I use tmux (version 2.6) inside termite, selection mode only allows me to scrollback the visible area of the terminal. Further scrolling back in termite works perfectly fine without tmux. However, if I want to further scroll back with tmux inside termite, I have to use tmux scrolling, which is ok as a workaround but I'd much rather use termite's selection mode. Is it possible to solve this problem through configuration or is it a (probably known) incompatibility between tmux and termite or even a bug?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
