### ISSUE TITLE
config option to set env variables

### ISSUE THREAD

**Issue by mschwartz** [thestinger/termite#724]
I may have missed it, but I could not find a way in termite.conf to SET env variables.  Seems like a very useful feature to me.

For example, set env variable TERMINAL='termite'

then in sh scripts, you can do special logic based upon $TERMINAL

Thanks for the program, it's awesome.

**Comment by Narrat** [comment]
Maybe I miss something. But why should it be possible with the terminal emulator config?
Those are normally set in one of the possible config files for the shell you use with said terminal emulator.

**Comment by mschwartz** [comment]
In my .zshrc or .bashrc, I want to be able to do specific logic depending on if running in termite.

So the env variable has to be set before the shell is run...

**Comment by mschwartz** [comment]
Kitty terminal program:

https://sw.kovidgoyal.net/kitty/conf.html

env
Specify environment variables to set in all child processes. Note that environment variables are expanded recursively, so if you use:

env MYVAR1=a
env MYVAR2=${MYVAR1}/${HOME}/b
The value of MYVAR2 will be a/<path to home directory>/b.

**Comment by mschwartz** [comment]
Also, env is more general purpose than setting some well-known env var automagically within termite.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
