### ISSUE TITLE
scrollback_lines not honored?

### ISSUE THREAD

**Issue by Dieterbe** [thestinger/termite#726]
the config says.
```
# Length of the scrollback buffer, 0 disabled the scrollback buffer
# and setting it to a negative value means "infinite scrollback"
scrollback_lines = 10000
```

I've tried both 0 and -1, but they seem to behave the same. i can't scroll back as far as i want.
when I test using `for i in {1..1000}; do echo $i; done`, i can scroll back to line 490, not further (higher) than that. am i missing something? thanks!
I'm using v15.

**Comment by BarbUk** [comment]
`scrollback_lines = -1` is working correctly on termite v15 with my config.
Did you test in a new term to reload the config file ?

**Comment by Dieterbe** [comment]
oh. I missed that have to create a section `[options]`.
once i did that. it works well. i can run `for i in {1..100000}; do echo $i; done` now and scroll all the way back :) fantastic.

this also makes the difference between 0 and -1 very clear. with 0 there is no scrolling possible at all.

thanks for your help @BarbUk , have a nice day!

**Comment by adrian5** [comment]
I assumed the config was showing compiled-in default values (common convention).  In some cases—where termite cannot assume authority in the terminal pipeline—omission may be a sensible default, but I certainly was confused by this choice; the `10000` is an arbitrary example in this case, not the default value.
