### ISSUE TITLE
don't resolve symbolic links in path

### ISSUE THREAD

**Issue by erzoe** [thestinger/termite#727]
When opening a new window with `termite -d /some/path` symbolic links in `/some/path` are resolved.

I would prefer it if `termite -d /some/path` would open a new window with the current working directory `/some/path` and not some other path.

**Comment by egmontkob** [comment]
This requires termite to set `$PWD`, or ([beginning with VTE 0.52](https://bugzilla.gnome.org/show_bug.cgi?id=758452)) to pass the directory to `vte_terminal_spawn_sync()` (which takes care of setting `$PWD` then).

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
