### ISSUE TITLE
Control+Shift+T (Termite) isn't working on zsh

### ISSUE THREAD

**Issue by JorgeDLG** [thestinger/termite#728]
Control+Shift+T isn't working on zsh(work on bash and fish), I don't know if is oh-my-zsh related.
[my zshrc](https://gist.github.com/JorgeDLG/cb980e3f98725f3b14f2ea966058ca9d)

**Comment by Jetfrog28** [comment]
Have you sourced `/etc/profile.d/vte.sh`?  It's not sourced anywhere in your zshrc.

See REMARKS/Current Directory in termite(1) manpage and https://wiki.archlinux.org/index.php/Termite#Troubleshooting .
