### ISSUE TITLE
[Feature] Send signal to reload config

### ISSUE THREAD

**Issue by dotcs** [thestinger/termite#730]
First of all thank you very much for developing termite. I really enjoy the terminal a lot! :)

I wondered if it's possible to send a signal to running terminal processes which forces them to reload the config (essentially execute the same code that `ctrl+shift+r` executes). This would allow to change colors in the config and then reload the config in all running processes.

Thanks in advance for your time! :+1:

**Comment by BarbUk** [comment]
Yes:

```bash
killall -USR1 termite || true
```

I use it in [a script](https://github.com/BarbUk/dotfiles/blob/master/bin/change_theme#L83) to change between light and dark theme, works perfectly

**Comment by dotcs** [comment]
Confirmed that this works. Thank you @BarbUk for your fast and precise answer!
