### ISSUE TITLE
New Design advise

### ISSUE THREAD

**Issue by happysmile12321** [thestinger/termite#732]
I love this project,but I just wonder it to be better.
Here is my advice:
Add 3D effect.
When you press command such as ```ls```  or ```pwd```,it will print something,right?And I want it print more beaufitul!
such as this:system's output just came out from the 
```
|--| -> |^-| -> |^^|
|-^|     |^^|     |^^|
```
And ```^``` stands for content of print.
And when the Animation come out,it come transparent , -> 50% transparent , -> display.
I would like to see this change!
Thanks.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
