### ISSUE TITLE
[Question] What does filter_unmatched_urls do?

### ISSUE THREAD

**Issue by nathanielevan** [thestinger/termite#733]
Hi,
I understand that the option `filter_unmatched_urls` determine "whether to hide url hints not matching input in url hints mode." (as stated in `man termite.config`). I tried enabling and disabling `filter_unmatched_urls` in the configuration file, and each time I opened up a file with URLs in it and pressed `Ctrl+Shift+x` to toggle url hints mode, but I fail to see any difference. What exactly does the option affect?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
