### ISSUE TITLE
Regex based click actions

### ISSUE THREAD

**Issue by noonien** [thestinger/termite#735]
I think this is in the spirit of #656, however, I have another use case.

When building projects, and there is an error, there is usually a /path/to/file:line line that describes where the error is. It would be great to be able to click that pattern, and be able to run a script on it, most probably to start an editor on that position.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
