### ISSUE TITLE
Customize position of scrollback completion popup

### ISSUE THREAD

**Issue by kelvints** [thestinger/termite#736]
Is it possible to configure where the ctrl-tab popup is displayed (currently the top right corner)? If not, where would a patch to change this need to be made?

**Comment by karate** [comment]
This makes sense.
Top right corner is not ideal since long suggestions will cover the window on the right, or worse, will continue on the next monitor.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
