### ISSUE TITLE
I Couldn't successfully compile "vte-ng" to install "termite", Both give errors.

### ISSUE THREAD

**Issue by Bey0ndB1nary** [thestinger/termite#740]
Hi 

     I am getting the error mentioned in attached file. 
Please check and suggest. 

[C_Error.txt](https://github.com/thestinger/termite/files/4689446/C_Error.txt)

Thanks.

**Comment by chrissxYT** [comment]
i was getting the same missing <gtk/gtk.h> error, the error seems to be in the makefile, if you add some flags manually, you can fix that one

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
