### ISSUE TITLE
% symbol spawns when you are using zsh and powerlevel10k

### ISSUE THREAD

**Issue by jfernandz** [thestinger/termite#741]
Apparently this is caused by the terminal itself:

![Captura de pantalla_2020-06-12_11-38-45](https://user-images.githubusercontent.com/4059108/84491961-acfc0400-aca5-11ea-9dc2-d644d82a9617.png)

As we were talking in https://github.com/romkatv/powerlevel10k/issues/543

Is there a solution/workaround? What could be causing the problem?

Thank you so much and sorry if this is a duplicate.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
