### ISSUE TITLE
Build issue On Fedora 2020

### ISSUE THREAD

**Issue by NicTanghe** [thestinger/termite#743]
when compiling i get the following error.

![image](https://user-images.githubusercontent.com/13624265/84582016-de301d80-ade6-11ea-9c34-e174af7af6f9.png)

I do have vte and gtk+ installed

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
