### ISSUE TITLE
wrong key binding for next/prev search match in selection mode

### ISSUE THREAD

**Issue by smartding** [thestinger/termite#744]
When I'm in selection mode, after I start the search with `/`, I can't jump to next/prev search match with `n`/`N`, but `alt-n`/`alt-N` works. How can I change it to `n`/`N`?

Also, there's another problem: when there's multiple match on the same line, I can only jump to the first one, never the second one.

**Comment by wlhlm** [comment]
> When I'm in selection mode, after I start the search with /, I can't jump to next/prev search match with n/N, but alt-n/alt-N works. How can I change it to n/N?

Works for me™ both with vte-ng based on 0.56.2 (Arch) and  0.60.3.

> Also, there's another problem: when there's multiple match on the same line, I can only jump to the first one, never the second one.

This is a [known problem](https://bugzilla.gnome.org/show_bug.cgi?id=627886) with the vte library that's best fixed upstream.

**Comment by smartding** [comment]
> > When I'm in selection mode, after I start the search with /, I can't jump to next/prev search match with n/N, but alt-n/alt-N works. How can I change it to n/N?
> 
> Works for me™ both with vte-ng based on 0.56.2 (Arch) and 0.60.3.
> 
> > Also, there's another problem: when there's multiple match on the same line, I can only jump to the first one, never the second one.
> 
> This is a [known problem](https://bugzilla.gnome.org/show_bug.cgi?id=627886) with the vte library that's best fixed upstream.

I installed termite by installing the termite package on Arch. The termite package depends on vte-common, not vte-ng.
Should I install the termite-git aur instead?  termite-git depends on vte-ng.

**Comment by smartding** [comment]
> > When I'm in selection mode, after I start the search with /, I can't jump to next/prev search match with n/N, but alt-n/alt-N works. How can I change it to n/N?
> 
> Works for me™ both with vte-ng based on 0.56.2 (Arch) and 0.60.3.
> 
> > Also, there's another problem: when there's multiple match on the same line, I can only jump to the first one, never the second one.
> 
> This is a [known problem](https://bugzilla.gnome.org/show_bug.cgi?id=627886) with the vte library that's best fixed upstream.

I installed the termite-git aur, still I can only jump to next/prev search match with `alt-n`/`alt-N`, not `n`/`N`

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
