### ISSUE TITLE
termite doesn't support the resize window escape sequence

### ISSUE THREAD

**Issue by foldfelis** [thestinger/termite#752]
According to the [XTerm documentation](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps;Ps;Ps-t:Ps-=-8;height;width.2519), the CSI sequences listed bellow should resize termite into given size.

* `echo -n "\e[8;20;80t"` should set form size to height=20, width=80
* `echo -n "\e[8;30t"` should set form size to height=30
* `echo -n "\e[8;;90t"` should set form size to width=90
* `echo -n "\e[8;0;0t"` should set form size to height=0, width=0

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
