### ISSUE TITLE
Fonts randomly appear bold

### ISSUE THREAD

**Issue by nathanielevan** [thestinger/termite#756]
Hi, I currently have this issue that happens only with Termite (or at least among terminals I've tested: Termite, urxvt, st): sometimes (but very occasionally), when I have a Termite window open, then open a browser in another workspace, I come back to the Termite window with some of the text appearing in bold where it shouldn't:

![2020-09-27-095336](https://user-images.githubusercontent.com/9361126/94484374-85a25600-0206-11eb-9cea-f6baf6920223.png)

You can kind of see the bold texts that appear slightly more jagged, those are the parts that aren't supposed to appear bold.

I use Arch Linux, running the latest kernels and software available in the official repos, using bspwm as window manager. This issue has occurred at least in spotify-tui (shown in picture), and vim.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
