### ISSUE TITLE
How to turn off Ctrl-C + Ctrl-D sequence that closes current terminal and opens a new window?

### ISSUE THREAD

**Issue by unclechu** [thestinger/termite#757]
I have a habit of terminating my terminal session by pressing `Ctrl-D`.

When I open a new terminal window if I press `Ctrl-C` and then `Ctrl-D` it will close current terminal window (as expected, since the shell exits) but also it opens a new terminal window after which is not desirable behavior for me.

- Is this known behavior?
- Is it intended to work this way? Or is it a side-effect of something else?
- Is this a part of **terminte** functionality?

Any ideas how to turn off this behavior?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
