### ISSUE TITLE
The -d option doesn't work.

### ISSUE THREAD

**Issue by PhineasGreene** [thestinger/termite#758]
Running termite with the -d option simply does nothing. The new terminal opens in my home directory.
Examples:
termite -d /home/user/Mail
termite -d /home/user/Mail/
termite -d ~/Mail
All start a new terminal in /home/user/. I have no idea what the relevant information for this problem would be, but I'm on Arch, I'm using bash, and my window manager is dwm. My installation is up to date.

**Comment by BarbUk** [comment]
The `-d` option works fine for me:

```
$ termite -v
termite v15-23-g8e1a9ee

# Works ok
$ termite -d $HOME/dev
$ termite -d ~/dev

# With a dir that does not exists
$ termite -d ~/Mail
chdir: No such file or directory
```

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
