### ISSUE TITLE
Add unsafe paste warning

### ISSUE THREAD

**Issue by norpol** [thestinger/termite#759]
It would be amazing if termite would warn in case you're trying to paste mutli-line strings and preview the text somehow. This way there would be protection against accidentally pasting dangerous code and it would also avoid accidentally pasting something that hits enter.

[xfce4-terminal](https://bugzilla.xfce.org/show_bug.cgi?id=13252) added this feature some time ago.

![Screenshot of unsafe paste demo, asking you in a dialog if you want to paste multiple lines and a preview of the text](https://i.imgur.com/vOtPoVk.png)

**Comment by laur89** [comment]
Shouldn't this be shell-dependent? Eg with bash/readline, you can add this to `inputrc`:

    set enable-bracketed-paste on

This would disable auto-executing commands with newline in the end

**Comment by norpol** [comment]
Thank you, that is a good pointer - though I believe the terminal emulator should help with such a thing since you don't always all shells configured/configurable everywhere (e.g. ssh).

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Comment by norpol** [comment]
Thanks for the great time with Termite so far!
