### ISSUE TITLE
Is termite dead ?

### ISSUE THREAD

**Issue by Atralb** [thestinger/termite#760]
The last commit is from 2019/06/14, which is almost a year and a half ago.

I've seen no discussion about the current maintenance status.

have you stopped development of the project @thestinger ?

Thanks in advance.

**Comment by thestinger** [comment]
The project needs a new maintainer/developer. I already handed it off to someone previously but they've stopped actively working on it. I wasn't the last person developing it.

**Comment by jelly** [comment]
Yeah sorry @thestinger, I simply don't have the time and energy anymore for maintaining it and the situation with vte regarding the custom patches isn't improving either.

**Comment by sim6** [comment]
First of all, thank you so much for your work. There are a lot of forks, so maybe there’s a volunteer. Please, could you @thestinger or @jelly make this situation more visible? E.g. Linking this issue from about secction of Github project.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
