### ISSUE TITLE
Non-latin keyboard layout not working for ctrl+shift+c and ctrl+shift+v

### ISSUE THREAD

**Issue by EmptyBucket** [thestinger/termite#761]
In the video, I first use hotkeys in the Latin layout, and then in the Cyrillic layout
![Peek 2020-11-03 18-31](https://user-images.githubusercontent.com/8377311/97991168-e07d2d80-1e02-11eb-8923-7ad657d44398.gif)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
