### ISSUE TITLE
How to copy without trailing spaces?

### ISSUE THREAD

**Issue by polm** [thestinger/termite#762]
Hello, I recently switched from urxvt to termite and everything is lovely except I can't figure out how to copy text without trailing spaces. I think I had a script in urxvt that would modify the clipboard when copying things but I haven't seen anything similar for termite. 

Is there some way to avoid getting trailing spaces when copying text from termite?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Comment by polm** [comment]
Thanks for the notice and the years of maintenance :heart:
