### ISSUE TITLE
Cursor Shape not changing

### ISSUE THREAD

**Issue by ReneganRonin** [thestinger/termite#764]
I have a problem changing the cursor shape of termite.
![image](https://user-images.githubusercontent.com/66054069/98891043-49863480-24d8-11eb-9c97-da20c19a868c.png)
The one of the left is the config. As you can see, the `cursor_shape` is set to `underline`. However, the one on the right which i reloaded using `CTRL + Shift + r` to reload the configs, the cursor shape stays the same. Any ideas what might caused the problem?

**Comment by BarbUk** [comment]
Cursor shape don't seem to change following a config reload, `CTRL + Shift + r`  or `killall -USR1 termite`.
Opening a new terminal give you the correct cursor shape.

You can also change it directly from your prompt:
```bash
echo -ne "\e[3 q"
```

**Comment by ReneganRonin** [comment]
Hello. I just realized that fish shell has its own cursor mode which defaults to block during Vim-mode
`set fish_vi_key_bindings`
and when i revert back to `set fish_default_key_bindings`, the cursor shape changed according to the config of termite.
Vi-mode bindings of fish also affects other terminal emulators as well. I just learnt it by reading when experimenting it. Sorry for the inconvenience. Termite is working now.
