### ISSUE TITLE
Non English Chars Not Displayed Properly

### ISSUE THREAD

**Issue by ahmedselim2017** [thestinger/termite#765]
When I enter non english chars (ü,ğ,ş etc.) it just displays ```<ffffffff>```.
My font is ```font = Hack Nerd Font Mono 9```

**Comment by BarbUk** [comment]
What are your locales ?

```
$ env | grep -i lc_
LC_ADDRESS=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
```

With the hack font:

![image](https://user-images.githubusercontent.com/64371/99630980-41884080-2a54-11eb-9115-35061ddb358d.png)

**Comment by ahmedselim2017** [comment]
Oops. I forgot the setting locale (i was doing a fresh install). When I set the locale the issue was solved.
