### ISSUE TITLE
terminfo: termite vs xterm-termite

### ISSUE THREAD

**Issue by michaelmyc** [thestinger/termite#766]
Hi, I see that the default terminfo from x includes `termite`, but `xterm-termite` was set automatically by termite (which also needs to be added through pacman). I'm wondering what's the differences between them. 

I'm using conda to manage my Python environments, and due to cross-platform concerns, conda ships their own terminfos, so pacman won't save me here. I'd have to soft link the `xterm-termite` terminfo to every single environment I create, which is too much of a hassle. 

My current hack is to set my zshrc to recognize `xterm-termite` and switch it to `termite`, which seems to work fairly well for the termite functionalities I use. However, there must be a reason why you guys use `xterm-termite`, so I'm curous what's different between the two. Is it possible to use an option in the config file to allow the use of other terminfo to ensure compatibility with some compromises on functionality? 

Also, [Arch wiki](https://wiki.archlinux.org/index.php/termite#Terminal_issues_with_SSH) suggested to use `xterm-color` to deal with ssh issues, and how is that different from `xterm-termite` and `termite`?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
