### ISSUE TITLE
Setting terminal to termite in pcmanfm doesn't work when opening files with vim.

### ISSUE THREAD

**Issue by zoj613** [thestinger/termite#767]
This seems to work just fine if the terminal is set to `urxvt` in pcmanfm. But if I change it `termite` in preferences->advanced->terminal emulator, then opening files with vim inside pcmanfm does not work. Is there an extra argument I must pass to the command? Even the instruction at https://wiki.archlinux.org/index.php/PCManFM#Set_the_terminal_emulator saying it should be `bash -c 'termite'` dont work.

**Comment by r00t-** [comment]
use:
```bash -c "termite -e "$*" --```
and hope that the filenames to edit never contain spaces.

**Comment by zoj613** [comment]
> bash -c 'termite -e "$*"' --

Did you try it on your end? The terminal won't even open running that command on mine.

**Comment by r00t-** [comment]
normally the "--" (the actual value does not matter) is needed because the shell will use the first argument as $0:
```
$ sh -c 'echo $0;echo $*' foo bar baz
foo
bar baz
$
```

i didn't check how pacman actually builds the commandline,
and i use neither program, so no, i did not try this.
