### ISSUE TITLE
How to make dependencies between colors

### ISSUE THREAD

**Issue by webcaptcha** [thestinger/termite#768]
Sorry for bothering you, I can't really understand how to bind colors between dir_colors and termite colors.

For example I have dir_colors (for ls command) which says to use 34 color for directories (34 color means blue, just blue)
But then, magically, that 34 color turns into color1 from termite config.

How to understand why color1? Do we have some linking table for that? And how I can figure out, for example color5 what responsible for?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
