### ISSUE TITLE
Is this project still active? I have not seen any updates :((

### ISSUE THREAD

**Issue by ReneganRonin** [thestinger/termite#770]

**Comment by tnfru** [comment]
I am wondering this too. Considering the last Commit is 1.5 years ago it isn't looking too well

**Comment by paddyoneill** [comment]
It isn't actively maintained, see this issue for reasons why. #760

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
