### ISSUE TITLE
Bug: Crashes when scroll with mouse wheel in selection mode

### ISSUE THREAD

**Issue by unclechu** [thestinger/termite#771]
How to reproduce:
1. Open `termite`
2. Make some output so it would be more than one page
3. Go to selection mode by `Ctrl+Shift+Space`
4. Scroll one page up by pressing `Ctrl+b` twice
5. Now scroll to the bottom with mouse wheel, if it didn’t crash also start scrolling histerically up and down
6. It crashes

```
λ termite
**
VTE:ERROR:../src/ringview.cc:299:const vte::base::BidiRow* vte::base::RingView::get_bidirow(vte::grid::row_t) const: assertion failed (row >= m_start): (44 >= 46)
Bail out! VTE:ERROR:../src/ringview.cc:299:const vte::base::BidiRow* vte::base::RingView::get_bidirow(vte::grid::row_t) const: assertion failed (row >= m_start): (44 >= 46)
Aborted (core dumped)
```

**termite** version:
```
λ nix repl <<< '(import <nixpkgs> {}).termite.version'
Welcome to Nix version 2.3.10. Type :? for help.

"15"
```
OS: NixOS 20.09

Reproduce **termite** build with Nix:
``` sh
nix-shell -I nixpkgs='https://github.com/NixOS/nixpkgs/archive/0e2832d592e999feb7b5df0e574a29c342970e4b.tar.gz' -p termite --run termite
```

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
