### ISSUE TITLE
make: *** [Makefile:43: install] Erro 1

### ISSUE THREAD

**Issue by lobatim** [thestinger/termite#780]
after I digit thi: sudo make install
i am getting this error:

mkdir -p /usr/local/share/terminfo
install -Dm755 termite /usr/local/bin/termite
install: omitindo o diretório 'termite'
make: *** [Makefile:43: install] Erro 1

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
