### ISSUE TITLE
Font sometimes gets messed up

### ISSUE THREAD

**Issue by emanuelep57** [thestinger/termite#782]
![image](https://user-images.githubusercontent.com/80958216/115553485-be427380-a2ad-11eb-857c-6e5a86f44942.png) This font should be monospace 11, for some reason it becomes italic suddenly, and if I change it with another font like Noto Sans or Hack the whole thing becomes unreadable. 

Here is my config of termite, even tho it worked fine until now..
https://pastebin.com/uYXSMibX

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
