### ISSUE TITLE
URL search sometimes selects '['

### ISSUE THREAD

**Issue by dkasak** [thestinger/termite#80]
Pressing 'u' in command mode with a terminal that is empty, except for a single prompt `[dkasak@telperion ~]% `, selects/highlights the first '[' of the prompt. 

A similar "runoff" behaviour of #76 still occurs in this scenario: if 'u' or 'U' is pressed multiple times, the previously selected '[' gets unselected and then I am unable to replicate the problem again in the same terminal instance.

However, if 'u' or 'U' are *not* pressed multiple times after '[' has been selected, and I simply exit the command mode, a 'u' or 'U' in a new command mode session selects '[' again.

**Comment by thestinger** [comment]
AFAIK, this is an inherent issue with the VTE search implementation. I'm not quite sure what's happening though so it's unclear if it's one of the many issues that are already reported.

**Comment by thestinger** [comment]
I don't think this is a Termite issue. It's the realm of VTE.
