### ISSUE TITLE
Setting window name

### ISSUE THREAD

**Issue by leonardt** [thestinger/termite#86]
Hi, I am trying to run a scratchpad using termite on DWM and it requires setting a specific window name.  I'm having no luck using 

```
termite --name=scratchpad
```

Possibly a bug? Or could we get non-gtk integration

**Comment by Isti115** [comment]
Leaving this here just for future reference by others maybe trying to get something like this working in i3.  
I had to use the `[instance="asdf"]` selector for `termite --name "asdf"`, `[class="name"]` did not work.  
The reasoning and some background can be found here:  
https://www.reddit.com/r/i3wm/comments/85scgq/for_window_and_multiple_wm_classes/
https://i3wm.org/docs/userguide.html#assign_workspace
