### ISSUE TITLE
Feature request: Enable a title per terminal with 'termite --title'

### ISSUE THREAD

**Issue by wimstefan** [thestinger/termite#91]
For my usage of a terminal it is very handy to make it possible to give a terminal window a specific title as for example lilyterm does (https://github.com/Tetralet/LilyTerm).

**Comment by udiboy1209** [comment]
is there a way to dynamically set title?

**Comment by jelly** [comment]
This doesn't have to do much with termite. It's mostly about how zsh/bash are configured. For example for bahs it's explained here https://stackoverflow.com/questions/5076127/bash-update-terminal-title-by-running-a-second-command/5080670#5080670
